# ####################################################################

#  Created by Genus(TM) Synthesis Solution 21.15-s080_1 on Tue Nov 04 16:27:52 MST 2025

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1000fF
set_units -time 1000ps

# Set the current design
current_design TopModule

create_clock -name "clk" -period 1.0 -waveform {0.0 0.5} [get_ports clk]
group_path -weight 1.000000 -name C2C -from [list \
  [get_cells spi_inst_miso_q_reg]  \
  [get_cells {spi_inst_shreg_out_reg[63]}]  \
  [get_cells {spi_inst_shreg_out_reg[62]}]  \
  [get_cells {spi_inst_shreg_out_reg[61]}]  \
  [get_cells {spi_inst_shreg_out_reg[60]}]  \
  [get_cells {spi_inst_shreg_out_reg[59]}]  \
  [get_cells {spi_inst_shreg_out_reg[58]}]  \
  [get_cells {spi_inst_shreg_out_reg[57]}]  \
  [get_cells {spi_inst_shreg_out_reg[56]}]  \
  [get_cells {spi_inst_shreg_out_reg[55]}]  \
  [get_cells {spi_inst_shreg_out_reg[54]}]  \
  [get_cells {spi_inst_shreg_out_reg[53]}]  \
  [get_cells {spi_inst_shreg_out_reg[52]}]  \
  [get_cells {spi_inst_shreg_out_reg[51]}]  \
  [get_cells {spi_inst_shreg_out_reg[50]}]  \
  [get_cells {spi_inst_shreg_out_reg[49]}]  \
  [get_cells {spi_inst_shreg_out_reg[48]}]  \
  [get_cells {spi_inst_shreg_out_reg[47]}]  \
  [get_cells {spi_inst_shreg_out_reg[46]}]  \
  [get_cells {spi_inst_shreg_out_reg[45]}]  \
  [get_cells {spi_inst_shreg_out_reg[44]}]  \
  [get_cells {spi_inst_shreg_out_reg[43]}]  \
  [get_cells {spi_inst_shreg_out_reg[42]}]  \
  [get_cells {spi_inst_shreg_out_reg[41]}]  \
  [get_cells {spi_inst_shreg_out_reg[40]}]  \
  [get_cells {spi_inst_shreg_out_reg[39]}]  \
  [get_cells {spi_inst_shreg_out_reg[38]}]  \
  [get_cells {spi_inst_shreg_out_reg[37]}]  \
  [get_cells {spi_inst_shreg_out_reg[36]}]  \
  [get_cells {spi_inst_shreg_out_reg[35]}]  \
  [get_cells {spi_inst_shreg_out_reg[34]}]  \
  [get_cells {spi_inst_shreg_out_reg[33]}]  \
  [get_cells {spi_inst_shreg_out_reg[32]}]  \
  [get_cells {spi_inst_shreg_out_reg[31]}]  \
  [get_cells {spi_inst_shreg_out_reg[30]}]  \
  [get_cells {spi_inst_shreg_out_reg[29]}]  \
  [get_cells {spi_inst_shreg_out_reg[28]}]  \
  [get_cells {spi_inst_shreg_out_reg[27]}]  \
  [get_cells {spi_inst_shreg_out_reg[26]}]  \
  [get_cells {spi_inst_shreg_out_reg[25]}]  \
  [get_cells {spi_inst_shreg_out_reg[24]}]  \
  [get_cells {spi_inst_shreg_out_reg[23]}]  \
  [get_cells {spi_inst_shreg_out_reg[22]}]  \
  [get_cells {spi_inst_shreg_out_reg[21]}]  \
  [get_cells {spi_inst_shreg_out_reg[20]}]  \
  [get_cells {spi_inst_shreg_out_reg[19]}]  \
  [get_cells {spi_inst_shreg_out_reg[18]}]  \
  [get_cells {spi_inst_shreg_out_reg[17]}]  \
  [get_cells {spi_inst_shreg_out_reg[16]}]  \
  [get_cells {spi_inst_shreg_out_reg[15]}]  \
  [get_cells {spi_inst_shreg_out_reg[14]}]  \
  [get_cells {spi_inst_shreg_out_reg[13]}]  \
  [get_cells {spi_inst_shreg_out_reg[12]}]  \
  [get_cells {spi_inst_shreg_out_reg[11]}]  \
  [get_cells {spi_inst_shreg_out_reg[10]}]  \
  [get_cells {spi_inst_shreg_out_reg[9]}]  \
  [get_cells {csm_inst_right_reg_reg[6]}]  \
  [get_cells {csm_inst_right_reg_reg[17]}]  \
  [get_cells {csm_inst_right_reg_reg[5]}]  \
  [get_cells {csm_inst_right_reg_reg[19]}]  \
  [get_cells {csm_inst_right_reg_reg[11]}]  \
  [get_cells {csm_inst_right_reg_reg[22]}]  \
  [get_cells {csm_inst_right_reg_reg[9]}]  \
  [get_cells {csm_inst_right_reg_reg[1]}]  \
  [get_cells {csm_inst_right_reg_reg[16]}]  \
  [get_cells {csm_inst_right_reg_reg[3]}]  \
  [get_cells {csm_inst_right_reg_reg[8]}]  \
  [get_cells {csm_inst_right_reg_reg[31]}]  \
  [get_cells {csm_inst_right_reg_reg[21]}]  \
  [get_cells {csm_inst_right_reg_reg[13]}]  \
  [get_cells {csm_inst_right_reg_reg[10]}]  \
  [get_cells {csm_inst_right_reg_reg[12]}]  \
  [get_cells {csm_inst_right_reg_reg[27]}]  \
  [get_cells {csm_inst_right_reg_reg[15]}]  \
  [get_cells {csm_inst_right_reg_reg[23]}]  \
  [get_cells {csm_inst_right_reg_reg[0]}]  \
  [get_cells {csm_inst_right_reg_reg[14]}]  \
  [get_cells {csm_inst_right_reg_reg[26]}]  \
  [get_cells {csm_inst_right_reg_reg[25]}]  \
  [get_cells {csm_inst_right_reg_reg[29]}]  \
  [get_cells {csm_inst_right_reg_reg[18]}]  \
  [get_cells {csm_inst_right_reg_reg[24]}]  \
  [get_cells {csm_inst_right_reg_reg[4]}]  \
  [get_cells {spi_inst_shreg_out_reg[8]}]  \
  [get_cells {csm_inst_right_reg_reg[7]}]  \
  [get_cells {csm_inst_right_reg_reg[2]}]  \
  [get_cells {csm_inst_right_reg_reg[30]}]  \
  [get_cells {csm_inst_right_reg_reg[20]}]  \
  [get_cells {csm_inst_right_reg_reg[28]}]  \
  [get_cells {spi_inst_shreg_out_reg[7]}]  \
  [get_cells {spi_inst_shreg_out_reg[6]}]  \
  [get_cells {spi_inst_shreg_out_reg[5]}]  \
  [get_cells {spi_inst_shreg_out_reg[4]}]  \
  [get_cells {spi_inst_shreg_out_reg[3]}]  \
  [get_cells start_encrypt_reg]  \
  [get_cells start_decrypt_reg]  \
  [get_cells {key_reg_reg[39]}]  \
  [get_cells {key_reg_reg[18]}]  \
  [get_cells {key_reg_reg[14]}]  \
  [get_cells {key_reg_reg[55]}]  \
  [get_cells {key_reg_reg[5]}]  \
  [get_cells {key_reg_reg[11]}]  \
  [get_cells {key_reg_reg[30]}]  \
  [get_cells {key_reg_reg[62]}]  \
  [get_cells {key_reg_reg[59]}]  \
  [get_cells {key_reg_reg[37]}]  \
  [get_cells {key_reg_reg[45]}]  \
  [get_cells {key_reg_reg[50]}]  \
  [get_cells {key_reg_reg[47]}]  \
  [get_cells {key_reg_reg[57]}]  \
  [get_cells {key_reg_reg[61]}]  \
  [get_cells {key_reg_reg[13]}]  \
  [get_cells {key_reg_reg[33]}]  \
  [get_cells {key_reg_reg[31]}]  \
  [get_cells {key_reg_reg[35]}]  \
  [get_cells {key_reg_reg[54]}]  \
  [get_cells {key_reg_reg[53]}]  \
  [get_cells {key_reg_reg[44]}]  \
  [get_cells {key_reg_reg[51]}]  \
  [get_cells {key_reg_reg[49]}]  \
  [get_cells {key_reg_reg[60]}]  \
  [get_cells {key_reg_reg[2]}]  \
  [get_cells {key_reg_reg[15]}]  \
  [get_cells {key_reg_reg[42]}]  \
  [get_cells {key_reg_reg[10]}]  \
  [get_cells {key_reg_reg[52]}]  \
  [get_cells {key_reg_reg[63]}]  \
  [get_cells {key_reg_reg[25]}]  \
  [get_cells {key_reg_reg[58]}]  \
  [get_cells {key_reg_reg[26]}]  \
  [get_cells {key_reg_reg[3]}]  \
  [get_cells {key_reg_reg[36]}]  \
  [get_cells {key_reg_reg[21]}]  \
  [get_cells {key_reg_reg[23]}]  \
  [get_cells {key_reg_reg[34]}]  \
  [get_cells {key_reg_reg[20]}]  \
  [get_cells {key_reg_reg[1]}]  \
  [get_cells {key_reg_reg[19]}]  \
  [get_cells {key_reg_reg[17]}]  \
  [get_cells {key_reg_reg[6]}]  \
  [get_cells {key_reg_reg[29]}]  \
  [get_cells {key_reg_reg[43]}]  \
  [get_cells {key_reg_reg[4]}]  \
  [get_cells {key_reg_reg[28]}]  \
  [get_cells {key_reg_reg[22]}]  \
  [get_cells {key_reg_reg[12]}]  \
  [get_cells {key_reg_reg[9]}]  \
  [get_cells {key_reg_reg[38]}]  \
  [get_cells {key_reg_reg[46]}]  \
  [get_cells {key_reg_reg[7]}]  \
  [get_cells {key_reg_reg[27]}]  \
  [get_cells {key_reg_reg[41]}]  \
  [get_cells {spi_inst_input_text_reg[24]}]  \
  [get_cells {spi_inst_input_text_reg[8]}]  \
  [get_cells {spi_inst_input_text_reg[40]}]  \
  [get_cells {spi_inst_input_text_reg[56]}]  \
  [get_cells done_decrypt_latched_reg]  \
  [get_cells done_encrypt_latched_reg]  \
  [get_cells {spi_inst_input_text_reg[4]}]  \
  [get_cells {spi_inst_input_text_reg[6]}]  \
  [get_cells {spi_inst_input_text_reg[0]}]  \
  [get_cells {spi_inst_input_text_reg[10]}]  \
  [get_cells {spi_inst_input_text_reg[12]}]  \
  [get_cells {spi_inst_input_text_reg[14]}]  \
  [get_cells {spi_inst_input_text_reg[15]}]  \
  [get_cells {spi_inst_input_text_reg[1]}]  \
  [get_cells {spi_inst_input_text_reg[18]}]  \
  [get_cells {spi_inst_input_text_reg[20]}]  \
  [get_cells {spi_inst_input_text_reg[22]}]  \
  [get_cells {spi_inst_input_text_reg[2]}]  \
  [get_cells {spi_inst_input_text_reg[26]}]  \
  [get_cells {spi_inst_input_text_reg[28]}]  \
  [get_cells {spi_inst_input_text_reg[30]}]  \
  [get_cells {spi_inst_input_text_reg[33]}]  \
  [get_cells {spi_inst_input_text_reg[34]}]  \
  [get_cells {spi_inst_input_text_reg[36]}]  \
  [get_cells {spi_inst_input_text_reg[44]}]  \
  [get_cells {spi_inst_input_text_reg[46]}]  \
  [get_cells {spi_inst_input_text_reg[52]}]  \
  [get_cells {spi_inst_input_text_reg[53]}]  \
  [get_cells {spi_inst_input_text_reg[54]}]  \
  [get_cells {spi_inst_input_text_reg[57]}]  \
  [get_cells {spi_inst_input_text_reg[38]}]  \
  [get_cells {spi_inst_input_text_reg[58]}]  \
  [get_cells {spi_inst_input_text_reg[60]}]  \
  [get_cells {spi_inst_input_text_reg[63]}]  \
  [get_cells {spi_inst_input_text_reg[41]}]  \
  [get_cells {spi_inst_input_text_reg[43]}]  \
  [get_cells {spi_inst_input_text_reg[45]}]  \
  [get_cells {spi_inst_input_text_reg[47]}]  \
  [get_cells {spi_inst_input_text_reg[39]}]  \
  [get_cells {spi_inst_input_text_reg[49]}]  \
  [get_cells {spi_inst_input_text_reg[31]}]  \
  [get_cells {spi_inst_input_text_reg[3]}]  \
  [get_cells {spi_inst_input_text_reg[42]}]  \
  [get_cells {spi_inst_input_text_reg[48]}]  \
  [get_cells {spi_inst_input_text_reg[32]}]  \
  [get_cells {spi_inst_input_text_reg[16]}]  \
  [get_cells {spi_inst_input_text_reg[7]}]  \
  [get_cells {spi_inst_input_text_reg[37]}]  \
  [get_cells {spi_inst_input_text_reg[5]}]  \
  [get_cells {spi_inst_input_text_reg[35]}]  \
  [get_cells {spi_inst_input_text_reg[23]}]  \
  [get_cells {spi_inst_input_text_reg[17]}]  \
  [get_cells {spi_inst_input_text_reg[55]}]  \
  [get_cells {spi_inst_input_text_reg[61]}]  \
  [get_cells {spi_inst_input_text_reg[25]}]  \
  [get_cells {spi_inst_input_text_reg[19]}]  \
  [get_cells {spi_inst_input_text_reg[21]}]  \
  [get_cells {spi_inst_input_text_reg[59]}]  \
  [get_cells crypt_reg]  \
  [get_cells {spi_inst_input_text_reg[9]}]  \
  [get_cells {spi_inst_input_text_reg[13]}]  \
  [get_cells {spi_inst_input_text_reg[50]}]  \
  [get_cells {spi_inst_input_text_reg[51]}]  \
  [get_cells {spi_inst_input_text_reg[62]}]  \
  [get_cells {spi_inst_input_text_reg[11]}]  \
  [get_cells {spi_inst_input_text_reg[27]}]  \
  [get_cells {spi_inst_input_text_reg[29]}]  \
  [get_cells {transaction_state_reg[1]}]  \
  [get_cells {transaction_state_reg[0]}]  \
  [get_cells {data_reg_reg[46]}]  \
  [get_cells {data_reg_reg[47]}]  \
  [get_cells {data_reg_reg[49]}]  \
  [get_cells {data_reg_reg[51]}]  \
  [get_cells {data_reg_reg[53]}]  \
  [get_cells {data_reg_reg[55]}]  \
  [get_cells {data_reg_reg[57]}]  \
  [get_cells {data_reg_reg[59]}]  \
  [get_cells {data_reg_reg[61]}]  \
  [get_cells {data_reg_reg[8]}]  \
  [get_cells {data_reg_reg[16]}]  \
  [get_cells {spi_inst_bit_cnt_reg[6]}]  \
  [get_cells {data_reg_reg[4]}]  \
  [get_cells {data_reg_reg[0]}]  \
  [get_cells {data_reg_reg[58]}]  \
  [get_cells {data_reg_reg[62]}]  \
  [get_cells {data_reg_reg[63]}]  \
  [get_cells {data_reg_reg[10]}]  \
  [get_cells {data_reg_reg[20]}]  \
  [get_cells {data_reg_reg[22]}]  \
  [get_cells {data_reg_reg[24]}]  \
  [get_cells {data_reg_reg[18]}]  \
  [get_cells {data_reg_reg[2]}]  \
  [get_cells {data_reg_reg[6]}]  \
  [get_cells {data_reg_reg[12]}]  \
  [get_cells {data_reg_reg[1]}]  \
  [get_cells {data_reg_reg[3]}]  \
  [get_cells {data_reg_reg[60]}]  \
  [get_cells {data_reg_reg[5]}]  \
  [get_cells {data_reg_reg[7]}]  \
  [get_cells {data_reg_reg[9]}]  \
  [get_cells {data_reg_reg[11]}]  \
  [get_cells {data_reg_reg[13]}]  \
  [get_cells {data_reg_reg[14]}]  \
  [get_cells {data_reg_reg[15]}]  \
  [get_cells {data_reg_reg[56]}]  \
  [get_cells {data_reg_reg[17]}]  \
  [get_cells {data_reg_reg[19]}]  \
  [get_cells {data_reg_reg[21]}]  \
  [get_cells {data_reg_reg[23]}]  \
  [get_cells {data_reg_reg[25]}]  \
  [get_cells {data_reg_reg[27]}]  \
  [get_cells {data_reg_reg[29]}]  \
  [get_cells {data_reg_reg[31]}]  \
  [get_cells {data_reg_reg[33]}]  \
  [get_cells {data_reg_reg[35]}]  \
  [get_cells {data_reg_reg[54]}]  \
  [get_cells {data_reg_reg[37]}]  \
  [get_cells {data_reg_reg[39]}]  \
  [get_cells {data_reg_reg[41]}]  \
  [get_cells {data_reg_reg[43]}]  \
  [get_cells {data_reg_reg[45]}]  \
  [get_cells {data_reg_reg[52]}]  \
  [get_cells {data_reg_reg[30]}]  \
  [get_cells {data_reg_reg[32]}]  \
  [get_cells {data_reg_reg[34]}]  \
  [get_cells {data_reg_reg[36]}]  \
  [get_cells {data_reg_reg[28]}]  \
  [get_cells {data_reg_reg[38]}]  \
  [get_cells {data_reg_reg[40]}]  \
  [get_cells {data_reg_reg[42]}]  \
  [get_cells {data_reg_reg[44]}]  \
  [get_cells {data_reg_reg[26]}]  \
  [get_cells {data_reg_reg[48]}]  \
  [get_cells {data_reg_reg[50]}]  \
  [get_cells {spi_inst_shreg_out_reg[2]}]  \
  [get_cells trigger_operation_reg]  \
  [get_cells {spi_inst_bit_cnt_reg[5]}]  \
  [get_cells {csm_inst_round_counter_reg[3]}]  \
  [get_cells {csm_inst_left_reg_reg[11]}]  \
  [get_cells {csm_inst_left_reg_reg[17]}]  \
  [get_cells {csm_inst_left_reg_reg[5]}]  \
  [get_cells {csm_inst_left_reg_reg[30]}]  \
  [get_cells {csm_inst_left_reg_reg[27]}]  \
  [get_cells {csm_inst_left_reg_reg[4]}]  \
  [get_cells {csm_inst_left_reg_reg[3]}]  \
  [get_cells {csm_inst_left_reg_reg[13]}]  \
  [get_cells {csm_inst_left_reg_reg[31]}]  \
  [get_cells {csm_inst_left_reg_reg[6]}]  \
  [get_cells {csm_inst_left_reg_reg[8]}]  \
  [get_cells {csm_inst_left_reg_reg[9]}]  \
  [get_cells {csm_inst_left_reg_reg[1]}]  \
  [get_cells {csm_inst_left_reg_reg[22]}]  \
  [get_cells {csm_inst_left_reg_reg[19]}]  \
  [get_cells {csm_inst_left_reg_reg[16]}]  \
  [get_cells {csm_inst_left_reg_reg[20]}]  \
  [get_cells {csm_inst_left_reg_reg[21]}]  \
  [get_cells {csm_inst_left_reg_reg[7]}]  \
  [get_cells {csm_inst_left_reg_reg[24]}]  \
  [get_cells {csm_inst_left_reg_reg[26]}]  \
  [get_cells {csm_inst_left_reg_reg[28]}]  \
  [get_cells {csm_inst_left_reg_reg[15]}]  \
  [get_cells {csm_inst_left_reg_reg[25]}]  \
  [get_cells {csm_inst_left_reg_reg[29]}]  \
  [get_cells {csm_inst_left_reg_reg[10]}]  \
  [get_cells {csm_inst_left_reg_reg[18]}]  \
  [get_cells {csm_inst_left_reg_reg[12]}]  \
  [get_cells {csm_inst_left_reg_reg[2]}]  \
  [get_cells {csm_inst_left_reg_reg[0]}]  \
  [get_cells {csm_inst_left_reg_reg[23]}]  \
  [get_cells {csm_inst_left_reg_reg[14]}]  \
  [get_cells {spi_inst_shreg_out_reg[1]}]  \
  [get_cells {spi_inst_bit_cnt_reg[4]}]  \
  [get_cells {csm_inst_round_counter_reg[2]}]  \
  [get_cells csm_inst_mode_reg]  \
  [get_cells {csm_inst_round_counter_reg[1]}]  \
  [get_cells {csm_inst_state_reg[0]}]  \
  [get_cells csm_inst_done_encrypt_reg]  \
  [get_cells csm_inst_done_decrypt_reg]  \
  [get_cells {csm_inst_round_counter_reg[0]}]  \
  [get_cells {csm_inst_output_text_reg[3]}]  \
  [get_cells {csm_inst_output_text_reg[55]}]  \
  [get_cells {csm_inst_output_text_reg[4]}]  \
  [get_cells {csm_inst_output_text_reg[50]}]  \
  [get_cells {csm_inst_output_text_reg[51]}]  \
  [get_cells {csm_inst_output_text_reg[2]}]  \
  [get_cells {csm_inst_output_text_reg[0]}]  \
  [get_cells {csm_inst_output_text_reg[40]}]  \
  [get_cells {csm_inst_output_text_reg[48]}]  \
  [get_cells {csm_inst_output_text_reg[5]}]  \
  [get_cells {csm_inst_output_text_reg[18]}]  \
  [get_cells {spi_inst_bit_cnt_reg[3]}]  \
  [get_cells {csm_inst_output_text_reg[49]}]  \
  [get_cells {csm_inst_output_text_reg[13]}]  \
  [get_cells {csm_inst_output_text_reg[33]}]  \
  [get_cells {csm_inst_output_text_reg[47]}]  \
  [get_cells {csm_inst_output_text_reg[56]}]  \
  [get_cells {csm_inst_output_text_reg[10]}]  \
  [get_cells {csm_inst_output_text_reg[41]}]  \
  [get_cells {csm_inst_output_text_reg[54]}]  \
  [get_cells {csm_inst_output_text_reg[20]}]  \
  [get_cells {csm_inst_output_text_reg[59]}]  \
  [get_cells {csm_inst_output_text_reg[25]}]  \
  [get_cells {csm_inst_output_text_reg[32]}]  \
  [get_cells {csm_inst_output_text_reg[6]}]  \
  [get_cells {csm_inst_output_text_reg[44]}]  \
  [get_cells {csm_inst_output_text_reg[8]}]  \
  [get_cells {csm_inst_output_text_reg[45]}]  \
  [get_cells {csm_inst_output_text_reg[36]}]  \
  [get_cells {csm_inst_output_text_reg[62]}]  \
  [get_cells {csm_inst_output_text_reg[16]}]  \
  [get_cells {csm_inst_output_text_reg[58]}]  \
  [get_cells {csm_inst_output_text_reg[17]}]  \
  [get_cells {csm_inst_output_text_reg[61]}]  \
  [get_cells {csm_inst_output_text_reg[63]}]  \
  [get_cells {csm_inst_output_text_reg[57]}]  \
  [get_cells {csm_inst_output_text_reg[1]}]  \
  [get_cells {csm_inst_output_text_reg[14]}]  \
  [get_cells {csm_inst_output_text_reg[11]}]  \
  [get_cells {csm_inst_output_text_reg[15]}]  \
  [get_cells {csm_inst_output_text_reg[53]}]  \
  [get_cells {csm_inst_output_text_reg[21]}]  \
  [get_cells cs_rise_delayed_reg]  \
  [get_cells {csm_inst_output_text_reg[7]}]  \
  [get_cells {csm_inst_output_text_reg[34]}]  \
  [get_cells {csm_inst_output_text_reg[42]}]  \
  [get_cells {csm_inst_output_text_reg[35]}]  \
  [get_cells {csm_inst_state_reg[2]}]  \
  [get_cells {csm_inst_output_text_reg[30]}]  \
  [get_cells {csm_inst_output_text_reg[29]}]  \
  [get_cells {csm_inst_output_text_reg[26]}]  \
  [get_cells {csm_inst_output_text_reg[31]}]  \
  [get_cells {csm_inst_output_text_reg[28]}]  \
  [get_cells {csm_inst_output_text_reg[9]}]  \
  [get_cells {csm_inst_output_text_reg[43]}]  \
  [get_cells {csm_inst_output_text_reg[27]}]  \
  [get_cells {csm_inst_output_text_reg[24]}]  \
  [get_cells {csm_inst_output_text_reg[60]}]  \
  [get_cells {csm_inst_output_text_reg[52]}]  \
  [get_cells {csm_inst_output_text_reg[23]}]  \
  [get_cells {csm_inst_output_text_reg[46]}]  \
  [get_cells {csm_inst_output_text_reg[39]}]  \
  [get_cells {csm_inst_output_text_reg[19]}]  \
  [get_cells {csm_inst_output_text_reg[37]}]  \
  [get_cells {csm_inst_output_text_reg[38]}]  \
  [get_cells {csm_inst_output_text_reg[12]}]  \
  [get_cells {csm_inst_output_text_reg[22]}]  \
  [get_cells {spi_tx_data_reg[41]}]  \
  [get_cells {spi_tx_data_reg[0]}]  \
  [get_cells {spi_tx_data_reg[42]}]  \
  [get_cells {spi_tx_data_reg[60]}]  \
  [get_cells {spi_tx_data_reg[23]}]  \
  [get_cells {spi_tx_data_reg[56]}]  \
  [get_cells {spi_tx_data_reg[50]}]  \
  [get_cells {spi_tx_data_reg[45]}]  \
  [get_cells {spi_tx_data_reg[37]}]  \
  [get_cells {spi_tx_data_reg[33]}]  \
  [get_cells {spi_tx_data_reg[26]}]  \
  [get_cells {spi_tx_data_reg[16]}]  \
  [get_cells {spi_tx_data_reg[13]}]  \
  [get_cells {spi_tx_data_reg[2]}]  \
  [get_cells {spi_tx_data_reg[32]}]  \
  [get_cells {spi_tx_data_reg[48]}]  \
  [get_cells {spi_tx_data_reg[39]}]  \
  [get_cells {spi_tx_data_reg[12]}]  \
  [get_cells {spi_tx_data_reg[7]}]  \
  [get_cells {spi_tx_data_reg[63]}]  \
  [get_cells {spi_tx_data_reg[11]}]  \
  [get_cells {spi_tx_data_reg[5]}]  \
  [get_cells {spi_tx_data_reg[8]}]  \
  [get_cells {spi_tx_data_reg[9]}]  \
  [get_cells {spi_tx_data_reg[27]}]  \
  [get_cells {spi_tx_data_reg[14]}]  \
  [get_cells {spi_tx_data_reg[15]}]  \
  [get_cells {spi_tx_data_reg[17]}]  \
  [get_cells {spi_tx_data_reg[18]}]  \
  [get_cells {spi_tx_data_reg[19]}]  \
  [get_cells {spi_tx_data_reg[21]}]  \
  [get_cells {spi_tx_data_reg[22]}]  \
  [get_cells {spi_tx_data_reg[24]}]  \
  [get_cells {spi_tx_data_reg[25]}]  \
  [get_cells {spi_tx_data_reg[58]}]  \
  [get_cells {spi_tx_data_reg[30]}]  \
  [get_cells {spi_tx_data_reg[31]}]  \
  [get_cells {spi_tx_data_reg[34]}]  \
  [get_cells {spi_tx_data_reg[35]}]  \
  [get_cells {spi_tx_data_reg[36]}]  \
  [get_cells {spi_tx_data_reg[40]}]  \
  [get_cells {spi_tx_data_reg[43]}]  \
  [get_cells {spi_tx_data_reg[46]}]  \
  [get_cells {spi_tx_data_reg[47]}]  \
  [get_cells {spi_tx_data_reg[49]}]  \
  [get_cells {spi_tx_data_reg[51]}]  \
  [get_cells {spi_tx_data_reg[53]}]  \
  [get_cells {spi_tx_data_reg[54]}]  \
  [get_cells {spi_tx_data_reg[57]}]  \
  [get_cells {spi_tx_data_reg[59]}]  \
  [get_cells {spi_tx_data_reg[62]}]  \
  [get_cells {spi_tx_data_reg[55]}]  \
  [get_cells {spi_tx_data_reg[29]}]  \
  [get_cells {spi_tx_data_reg[61]}]  \
  [get_cells {spi_tx_data_reg[52]}]  \
  [get_cells {spi_tx_data_reg[38]}]  \
  [get_cells {spi_tx_data_reg[20]}]  \
  [get_cells {spi_tx_data_reg[44]}]  \
  [get_cells {spi_tx_data_reg[28]}]  \
  [get_cells {spi_tx_data_reg[6]}]  \
  [get_cells {spi_tx_data_reg[3]}]  \
  [get_cells {spi_tx_data_reg[4]}]  \
  [get_cells {spi_tx_data_reg[10]}]  \
  [get_cells {spi_tx_data_reg[1]}]  \
  [get_cells {spi_inst_bit_cnt_reg[1]}]  \
  [get_cells {spi_inst_bit_cnt_reg[2]}]  \
  [get_cells cs_prev_reg]  \
  [get_cells active_reg]  \
  [get_cells {csm_inst_state_reg[1]}]  \
  [get_cells {spi_inst_shreg_in_reg[62]}]  \
  [get_cells cs_sync_reg]  \
  [get_cells {spi_inst_shreg_in_reg[34]}]  \
  [get_cells {spi_inst_shreg_in_reg[26]}]  \
  [get_cells {spi_inst_shreg_in_reg[30]}]  \
  [get_cells {spi_inst_shreg_in_reg[51]}]  \
  [get_cells {spi_inst_shreg_in_reg[0]}]  \
  [get_cells {spi_inst_shreg_in_reg[13]}]  \
  [get_cells {spi_inst_shreg_in_reg[18]}]  \
  [get_cells {spi_inst_shreg_in_reg[61]}]  \
  [get_cells {spi_inst_shreg_in_reg[9]}]  \
  [get_cells {spi_inst_shreg_in_reg[10]}]  \
  [get_cells {spi_inst_shreg_in_reg[16]}]  \
  [get_cells {spi_inst_shreg_in_reg[4]}]  \
  [get_cells {spi_inst_shreg_in_reg[57]}]  \
  [get_cells {spi_inst_shreg_in_reg[60]}]  \
  [get_cells {spi_inst_shreg_in_reg[48]}]  \
  [get_cells {spi_inst_shreg_in_reg[27]}]  \
  [get_cells {spi_inst_shreg_in_reg[58]}]  \
  [get_cells {spi_inst_shreg_in_reg[22]}]  \
  [get_cells {spi_inst_shreg_in_reg[45]}]  \
  [get_cells {spi_inst_shreg_in_reg[53]}]  \
  [get_cells {spi_inst_shreg_in_reg[1]}]  \
  [get_cells {spi_inst_shreg_in_reg[8]}]  \
  [get_cells {spi_inst_shreg_in_reg[56]}]  \
  [get_cells {spi_inst_shreg_in_reg[17]}]  \
  [get_cells {spi_inst_shreg_in_reg[21]}]  \
  [get_cells {spi_inst_shreg_in_reg[5]}]  \
  [get_cells {spi_inst_shreg_in_reg[55]}]  \
  [get_cells {spi_inst_shreg_in_reg[50]}]  \
  [get_cells {spi_inst_shreg_in_reg[54]}]  \
  [get_cells {spi_inst_shreg_in_reg[20]}]  \
  [get_cells {spi_inst_shreg_in_reg[29]}]  \
  [get_cells {spi_inst_shreg_in_reg[52]}]  \
  [get_cells {spi_inst_shreg_in_reg[40]}]  \
  [get_cells {spi_inst_shreg_in_reg[31]}]  \
  [get_cells {spi_inst_shreg_in_reg[14]}]  \
  [get_cells {spi_inst_shreg_in_reg[25]}]  \
  [get_cells {spi_inst_shreg_in_reg[46]}]  \
  [get_cells {spi_inst_shreg_in_reg[33]}]  \
  [get_cells {spi_inst_shreg_in_reg[7]}]  \
  [get_cells {spi_inst_shreg_in_reg[19]}]  \
  [get_cells {spi_inst_shreg_in_reg[37]}]  \
  [get_cells {spi_inst_shreg_in_reg[42]}]  \
  [get_cells {spi_inst_shreg_in_reg[28]}]  \
  [get_cells {spi_inst_shreg_in_reg[44]}]  \
  [get_cells {spi_inst_shreg_in_reg[24]}]  \
  [get_cells {spi_inst_shreg_in_reg[2]}]  \
  [get_cells {spi_inst_shreg_in_reg[35]}]  \
  [get_cells {spi_inst_shreg_in_reg[41]}]  \
  [get_cells {spi_inst_shreg_in_reg[47]}]  \
  [get_cells {spi_inst_shreg_in_reg[43]}]  \
  [get_cells {spi_inst_shreg_in_reg[3]}]  \
  [get_cells {spi_inst_shreg_in_reg[59]}]  \
  [get_cells {spi_inst_shreg_in_reg[23]}]  \
  [get_cells {spi_inst_shreg_in_reg[6]}]  \
  [get_cells {spi_inst_shreg_in_reg[32]}]  \
  [get_cells {spi_inst_shreg_in_reg[15]}]  \
  [get_cells {spi_inst_shreg_in_reg[11]}]  \
  [get_cells {spi_inst_shreg_in_reg[38]}]  \
  [get_cells {spi_inst_shreg_in_reg[36]}]  \
  [get_cells {spi_inst_shreg_in_reg[49]}]  \
  [get_cells {spi_inst_shreg_in_reg[12]}]  \
  [get_cells {spi_inst_shreg_in_reg[39]}]  \
  [get_cells cs_meta_reg]  \
  [get_cells {spi_inst_bit_cnt_reg[0]}] ] -to [list \
  [get_cells spi_inst_miso_q_reg]  \
  [get_cells {spi_inst_shreg_out_reg[63]}]  \
  [get_cells {spi_inst_shreg_out_reg[62]}]  \
  [get_cells {spi_inst_shreg_out_reg[61]}]  \
  [get_cells {spi_inst_shreg_out_reg[60]}]  \
  [get_cells {spi_inst_shreg_out_reg[59]}]  \
  [get_cells {spi_inst_shreg_out_reg[58]}]  \
  [get_cells {spi_inst_shreg_out_reg[57]}]  \
  [get_cells {spi_inst_shreg_out_reg[56]}]  \
  [get_cells {spi_inst_shreg_out_reg[55]}]  \
  [get_cells {spi_inst_shreg_out_reg[54]}]  \
  [get_cells {spi_inst_shreg_out_reg[53]}]  \
  [get_cells {spi_inst_shreg_out_reg[52]}]  \
  [get_cells {spi_inst_shreg_out_reg[51]}]  \
  [get_cells {spi_inst_shreg_out_reg[50]}]  \
  [get_cells {spi_inst_shreg_out_reg[49]}]  \
  [get_cells {spi_inst_shreg_out_reg[48]}]  \
  [get_cells {spi_inst_shreg_out_reg[47]}]  \
  [get_cells {spi_inst_shreg_out_reg[46]}]  \
  [get_cells {spi_inst_shreg_out_reg[45]}]  \
  [get_cells {spi_inst_shreg_out_reg[44]}]  \
  [get_cells {spi_inst_shreg_out_reg[43]}]  \
  [get_cells {spi_inst_shreg_out_reg[42]}]  \
  [get_cells {spi_inst_shreg_out_reg[41]}]  \
  [get_cells {spi_inst_shreg_out_reg[40]}]  \
  [get_cells {spi_inst_shreg_out_reg[39]}]  \
  [get_cells {spi_inst_shreg_out_reg[38]}]  \
  [get_cells {spi_inst_shreg_out_reg[37]}]  \
  [get_cells {spi_inst_shreg_out_reg[36]}]  \
  [get_cells {spi_inst_shreg_out_reg[35]}]  \
  [get_cells {spi_inst_shreg_out_reg[34]}]  \
  [get_cells {spi_inst_shreg_out_reg[33]}]  \
  [get_cells {spi_inst_shreg_out_reg[32]}]  \
  [get_cells {spi_inst_shreg_out_reg[31]}]  \
  [get_cells {spi_inst_shreg_out_reg[30]}]  \
  [get_cells {spi_inst_shreg_out_reg[29]}]  \
  [get_cells {spi_inst_shreg_out_reg[28]}]  \
  [get_cells {spi_inst_shreg_out_reg[27]}]  \
  [get_cells {spi_inst_shreg_out_reg[26]}]  \
  [get_cells {spi_inst_shreg_out_reg[25]}]  \
  [get_cells {spi_inst_shreg_out_reg[24]}]  \
  [get_cells {spi_inst_shreg_out_reg[23]}]  \
  [get_cells {spi_inst_shreg_out_reg[22]}]  \
  [get_cells {spi_inst_shreg_out_reg[21]}]  \
  [get_cells {spi_inst_shreg_out_reg[20]}]  \
  [get_cells {spi_inst_shreg_out_reg[19]}]  \
  [get_cells {spi_inst_shreg_out_reg[18]}]  \
  [get_cells {spi_inst_shreg_out_reg[17]}]  \
  [get_cells {spi_inst_shreg_out_reg[16]}]  \
  [get_cells {spi_inst_shreg_out_reg[15]}]  \
  [get_cells {spi_inst_shreg_out_reg[14]}]  \
  [get_cells {spi_inst_shreg_out_reg[13]}]  \
  [get_cells {spi_inst_shreg_out_reg[12]}]  \
  [get_cells {spi_inst_shreg_out_reg[11]}]  \
  [get_cells {spi_inst_shreg_out_reg[10]}]  \
  [get_cells {spi_inst_shreg_out_reg[9]}]  \
  [get_cells {csm_inst_right_reg_reg[6]}]  \
  [get_cells {csm_inst_right_reg_reg[17]}]  \
  [get_cells {csm_inst_right_reg_reg[5]}]  \
  [get_cells {csm_inst_right_reg_reg[19]}]  \
  [get_cells {csm_inst_right_reg_reg[11]}]  \
  [get_cells {csm_inst_right_reg_reg[22]}]  \
  [get_cells {csm_inst_right_reg_reg[9]}]  \
  [get_cells {csm_inst_right_reg_reg[1]}]  \
  [get_cells {csm_inst_right_reg_reg[16]}]  \
  [get_cells {csm_inst_right_reg_reg[3]}]  \
  [get_cells {csm_inst_right_reg_reg[8]}]  \
  [get_cells {csm_inst_right_reg_reg[31]}]  \
  [get_cells {csm_inst_right_reg_reg[21]}]  \
  [get_cells {csm_inst_right_reg_reg[13]}]  \
  [get_cells {csm_inst_right_reg_reg[10]}]  \
  [get_cells {csm_inst_right_reg_reg[12]}]  \
  [get_cells {csm_inst_right_reg_reg[27]}]  \
  [get_cells {csm_inst_right_reg_reg[15]}]  \
  [get_cells {csm_inst_right_reg_reg[23]}]  \
  [get_cells {csm_inst_right_reg_reg[0]}]  \
  [get_cells {csm_inst_right_reg_reg[14]}]  \
  [get_cells {csm_inst_right_reg_reg[26]}]  \
  [get_cells {csm_inst_right_reg_reg[25]}]  \
  [get_cells {csm_inst_right_reg_reg[29]}]  \
  [get_cells {csm_inst_right_reg_reg[18]}]  \
  [get_cells {csm_inst_right_reg_reg[24]}]  \
  [get_cells {csm_inst_right_reg_reg[4]}]  \
  [get_cells {spi_inst_shreg_out_reg[8]}]  \
  [get_cells {csm_inst_right_reg_reg[7]}]  \
  [get_cells {csm_inst_right_reg_reg[2]}]  \
  [get_cells {csm_inst_right_reg_reg[30]}]  \
  [get_cells {csm_inst_right_reg_reg[20]}]  \
  [get_cells {csm_inst_right_reg_reg[28]}]  \
  [get_cells {spi_inst_shreg_out_reg[7]}]  \
  [get_cells {spi_inst_shreg_out_reg[6]}]  \
  [get_cells {spi_inst_shreg_out_reg[5]}]  \
  [get_cells {spi_inst_shreg_out_reg[4]}]  \
  [get_cells {spi_inst_shreg_out_reg[3]}]  \
  [get_cells start_encrypt_reg]  \
  [get_cells start_decrypt_reg]  \
  [get_cells {key_reg_reg[39]}]  \
  [get_cells {key_reg_reg[18]}]  \
  [get_cells {key_reg_reg[14]}]  \
  [get_cells {key_reg_reg[55]}]  \
  [get_cells {key_reg_reg[5]}]  \
  [get_cells {key_reg_reg[11]}]  \
  [get_cells {key_reg_reg[30]}]  \
  [get_cells {key_reg_reg[62]}]  \
  [get_cells {key_reg_reg[59]}]  \
  [get_cells {key_reg_reg[37]}]  \
  [get_cells {key_reg_reg[45]}]  \
  [get_cells {key_reg_reg[50]}]  \
  [get_cells {key_reg_reg[47]}]  \
  [get_cells {key_reg_reg[57]}]  \
  [get_cells {key_reg_reg[61]}]  \
  [get_cells {key_reg_reg[13]}]  \
  [get_cells {key_reg_reg[33]}]  \
  [get_cells {key_reg_reg[31]}]  \
  [get_cells {key_reg_reg[35]}]  \
  [get_cells {key_reg_reg[54]}]  \
  [get_cells {key_reg_reg[53]}]  \
  [get_cells {key_reg_reg[44]}]  \
  [get_cells {key_reg_reg[51]}]  \
  [get_cells {key_reg_reg[49]}]  \
  [get_cells {key_reg_reg[60]}]  \
  [get_cells {key_reg_reg[2]}]  \
  [get_cells {key_reg_reg[15]}]  \
  [get_cells {key_reg_reg[42]}]  \
  [get_cells {key_reg_reg[10]}]  \
  [get_cells {key_reg_reg[52]}]  \
  [get_cells {key_reg_reg[63]}]  \
  [get_cells {key_reg_reg[25]}]  \
  [get_cells {key_reg_reg[58]}]  \
  [get_cells {key_reg_reg[26]}]  \
  [get_cells {key_reg_reg[3]}]  \
  [get_cells {key_reg_reg[36]}]  \
  [get_cells {key_reg_reg[21]}]  \
  [get_cells {key_reg_reg[23]}]  \
  [get_cells {key_reg_reg[34]}]  \
  [get_cells {key_reg_reg[20]}]  \
  [get_cells {key_reg_reg[1]}]  \
  [get_cells {key_reg_reg[19]}]  \
  [get_cells {key_reg_reg[17]}]  \
  [get_cells {key_reg_reg[6]}]  \
  [get_cells {key_reg_reg[29]}]  \
  [get_cells {key_reg_reg[43]}]  \
  [get_cells {key_reg_reg[4]}]  \
  [get_cells {key_reg_reg[28]}]  \
  [get_cells {key_reg_reg[22]}]  \
  [get_cells {key_reg_reg[12]}]  \
  [get_cells {key_reg_reg[9]}]  \
  [get_cells {key_reg_reg[38]}]  \
  [get_cells {key_reg_reg[46]}]  \
  [get_cells {key_reg_reg[7]}]  \
  [get_cells {key_reg_reg[27]}]  \
  [get_cells {key_reg_reg[41]}]  \
  [get_cells {spi_inst_input_text_reg[24]}]  \
  [get_cells {spi_inst_input_text_reg[8]}]  \
  [get_cells {spi_inst_input_text_reg[40]}]  \
  [get_cells {spi_inst_input_text_reg[56]}]  \
  [get_cells done_decrypt_latched_reg]  \
  [get_cells done_encrypt_latched_reg]  \
  [get_cells {spi_inst_input_text_reg[4]}]  \
  [get_cells {spi_inst_input_text_reg[6]}]  \
  [get_cells {spi_inst_input_text_reg[0]}]  \
  [get_cells {spi_inst_input_text_reg[10]}]  \
  [get_cells {spi_inst_input_text_reg[12]}]  \
  [get_cells {spi_inst_input_text_reg[14]}]  \
  [get_cells {spi_inst_input_text_reg[15]}]  \
  [get_cells {spi_inst_input_text_reg[1]}]  \
  [get_cells {spi_inst_input_text_reg[18]}]  \
  [get_cells {spi_inst_input_text_reg[20]}]  \
  [get_cells {spi_inst_input_text_reg[22]}]  \
  [get_cells {spi_inst_input_text_reg[2]}]  \
  [get_cells {spi_inst_input_text_reg[26]}]  \
  [get_cells {spi_inst_input_text_reg[28]}]  \
  [get_cells {spi_inst_input_text_reg[30]}]  \
  [get_cells {spi_inst_input_text_reg[33]}]  \
  [get_cells {spi_inst_input_text_reg[34]}]  \
  [get_cells {spi_inst_input_text_reg[36]}]  \
  [get_cells {spi_inst_input_text_reg[44]}]  \
  [get_cells {spi_inst_input_text_reg[46]}]  \
  [get_cells {spi_inst_input_text_reg[52]}]  \
  [get_cells {spi_inst_input_text_reg[53]}]  \
  [get_cells {spi_inst_input_text_reg[54]}]  \
  [get_cells {spi_inst_input_text_reg[57]}]  \
  [get_cells {spi_inst_input_text_reg[38]}]  \
  [get_cells {spi_inst_input_text_reg[58]}]  \
  [get_cells {spi_inst_input_text_reg[60]}]  \
  [get_cells {spi_inst_input_text_reg[63]}]  \
  [get_cells {spi_inst_input_text_reg[41]}]  \
  [get_cells {spi_inst_input_text_reg[43]}]  \
  [get_cells {spi_inst_input_text_reg[45]}]  \
  [get_cells {spi_inst_input_text_reg[47]}]  \
  [get_cells {spi_inst_input_text_reg[39]}]  \
  [get_cells {spi_inst_input_text_reg[49]}]  \
  [get_cells {spi_inst_input_text_reg[31]}]  \
  [get_cells {spi_inst_input_text_reg[3]}]  \
  [get_cells {spi_inst_input_text_reg[42]}]  \
  [get_cells {spi_inst_input_text_reg[48]}]  \
  [get_cells {spi_inst_input_text_reg[32]}]  \
  [get_cells {spi_inst_input_text_reg[16]}]  \
  [get_cells {spi_inst_input_text_reg[7]}]  \
  [get_cells {spi_inst_input_text_reg[37]}]  \
  [get_cells {spi_inst_input_text_reg[5]}]  \
  [get_cells {spi_inst_input_text_reg[35]}]  \
  [get_cells {spi_inst_input_text_reg[23]}]  \
  [get_cells {spi_inst_input_text_reg[17]}]  \
  [get_cells {spi_inst_input_text_reg[55]}]  \
  [get_cells {spi_inst_input_text_reg[61]}]  \
  [get_cells {spi_inst_input_text_reg[25]}]  \
  [get_cells {spi_inst_input_text_reg[19]}]  \
  [get_cells {spi_inst_input_text_reg[21]}]  \
  [get_cells {spi_inst_input_text_reg[59]}]  \
  [get_cells crypt_reg]  \
  [get_cells {spi_inst_input_text_reg[9]}]  \
  [get_cells {spi_inst_input_text_reg[13]}]  \
  [get_cells {spi_inst_input_text_reg[50]}]  \
  [get_cells {spi_inst_input_text_reg[51]}]  \
  [get_cells {spi_inst_input_text_reg[62]}]  \
  [get_cells {spi_inst_input_text_reg[11]}]  \
  [get_cells {spi_inst_input_text_reg[27]}]  \
  [get_cells {spi_inst_input_text_reg[29]}]  \
  [get_cells {transaction_state_reg[1]}]  \
  [get_cells {transaction_state_reg[0]}]  \
  [get_cells {data_reg_reg[46]}]  \
  [get_cells {data_reg_reg[47]}]  \
  [get_cells {data_reg_reg[49]}]  \
  [get_cells {data_reg_reg[51]}]  \
  [get_cells {data_reg_reg[53]}]  \
  [get_cells {data_reg_reg[55]}]  \
  [get_cells {data_reg_reg[57]}]  \
  [get_cells {data_reg_reg[59]}]  \
  [get_cells {data_reg_reg[61]}]  \
  [get_cells {data_reg_reg[8]}]  \
  [get_cells {data_reg_reg[16]}]  \
  [get_cells {spi_inst_bit_cnt_reg[6]}]  \
  [get_cells {data_reg_reg[4]}]  \
  [get_cells {data_reg_reg[0]}]  \
  [get_cells {data_reg_reg[58]}]  \
  [get_cells {data_reg_reg[62]}]  \
  [get_cells {data_reg_reg[63]}]  \
  [get_cells {data_reg_reg[10]}]  \
  [get_cells {data_reg_reg[20]}]  \
  [get_cells {data_reg_reg[22]}]  \
  [get_cells {data_reg_reg[24]}]  \
  [get_cells {data_reg_reg[18]}]  \
  [get_cells {data_reg_reg[2]}]  \
  [get_cells {data_reg_reg[6]}]  \
  [get_cells {data_reg_reg[12]}]  \
  [get_cells {data_reg_reg[1]}]  \
  [get_cells {data_reg_reg[3]}]  \
  [get_cells {data_reg_reg[60]}]  \
  [get_cells {data_reg_reg[5]}]  \
  [get_cells {data_reg_reg[7]}]  \
  [get_cells {data_reg_reg[9]}]  \
  [get_cells {data_reg_reg[11]}]  \
  [get_cells {data_reg_reg[13]}]  \
  [get_cells {data_reg_reg[14]}]  \
  [get_cells {data_reg_reg[15]}]  \
  [get_cells {data_reg_reg[56]}]  \
  [get_cells {data_reg_reg[17]}]  \
  [get_cells {data_reg_reg[19]}]  \
  [get_cells {data_reg_reg[21]}]  \
  [get_cells {data_reg_reg[23]}]  \
  [get_cells {data_reg_reg[25]}]  \
  [get_cells {data_reg_reg[27]}]  \
  [get_cells {data_reg_reg[29]}]  \
  [get_cells {data_reg_reg[31]}]  \
  [get_cells {data_reg_reg[33]}]  \
  [get_cells {data_reg_reg[35]}]  \
  [get_cells {data_reg_reg[54]}]  \
  [get_cells {data_reg_reg[37]}]  \
  [get_cells {data_reg_reg[39]}]  \
  [get_cells {data_reg_reg[41]}]  \
  [get_cells {data_reg_reg[43]}]  \
  [get_cells {data_reg_reg[45]}]  \
  [get_cells {data_reg_reg[52]}]  \
  [get_cells {data_reg_reg[30]}]  \
  [get_cells {data_reg_reg[32]}]  \
  [get_cells {data_reg_reg[34]}]  \
  [get_cells {data_reg_reg[36]}]  \
  [get_cells {data_reg_reg[28]}]  \
  [get_cells {data_reg_reg[38]}]  \
  [get_cells {data_reg_reg[40]}]  \
  [get_cells {data_reg_reg[42]}]  \
  [get_cells {data_reg_reg[44]}]  \
  [get_cells {data_reg_reg[26]}]  \
  [get_cells {data_reg_reg[48]}]  \
  [get_cells {data_reg_reg[50]}]  \
  [get_cells {spi_inst_shreg_out_reg[2]}]  \
  [get_cells trigger_operation_reg]  \
  [get_cells {spi_inst_bit_cnt_reg[5]}]  \
  [get_cells {csm_inst_round_counter_reg[3]}]  \
  [get_cells {csm_inst_left_reg_reg[11]}]  \
  [get_cells {csm_inst_left_reg_reg[17]}]  \
  [get_cells {csm_inst_left_reg_reg[5]}]  \
  [get_cells {csm_inst_left_reg_reg[30]}]  \
  [get_cells {csm_inst_left_reg_reg[27]}]  \
  [get_cells {csm_inst_left_reg_reg[4]}]  \
  [get_cells {csm_inst_left_reg_reg[3]}]  \
  [get_cells {csm_inst_left_reg_reg[13]}]  \
  [get_cells {csm_inst_left_reg_reg[31]}]  \
  [get_cells {csm_inst_left_reg_reg[6]}]  \
  [get_cells {csm_inst_left_reg_reg[8]}]  \
  [get_cells {csm_inst_left_reg_reg[9]}]  \
  [get_cells {csm_inst_left_reg_reg[1]}]  \
  [get_cells {csm_inst_left_reg_reg[22]}]  \
  [get_cells {csm_inst_left_reg_reg[19]}]  \
  [get_cells {csm_inst_left_reg_reg[16]}]  \
  [get_cells {csm_inst_left_reg_reg[20]}]  \
  [get_cells {csm_inst_left_reg_reg[21]}]  \
  [get_cells {csm_inst_left_reg_reg[7]}]  \
  [get_cells {csm_inst_left_reg_reg[24]}]  \
  [get_cells {csm_inst_left_reg_reg[26]}]  \
  [get_cells {csm_inst_left_reg_reg[28]}]  \
  [get_cells {csm_inst_left_reg_reg[15]}]  \
  [get_cells {csm_inst_left_reg_reg[25]}]  \
  [get_cells {csm_inst_left_reg_reg[29]}]  \
  [get_cells {csm_inst_left_reg_reg[10]}]  \
  [get_cells {csm_inst_left_reg_reg[18]}]  \
  [get_cells {csm_inst_left_reg_reg[12]}]  \
  [get_cells {csm_inst_left_reg_reg[2]}]  \
  [get_cells {csm_inst_left_reg_reg[0]}]  \
  [get_cells {csm_inst_left_reg_reg[23]}]  \
  [get_cells {csm_inst_left_reg_reg[14]}]  \
  [get_cells {spi_inst_shreg_out_reg[1]}]  \
  [get_cells {spi_inst_bit_cnt_reg[4]}]  \
  [get_cells {csm_inst_round_counter_reg[2]}]  \
  [get_cells csm_inst_mode_reg]  \
  [get_cells {csm_inst_round_counter_reg[1]}]  \
  [get_cells {csm_inst_state_reg[0]}]  \
  [get_cells csm_inst_done_encrypt_reg]  \
  [get_cells csm_inst_done_decrypt_reg]  \
  [get_cells {csm_inst_round_counter_reg[0]}]  \
  [get_cells {csm_inst_output_text_reg[3]}]  \
  [get_cells {csm_inst_output_text_reg[55]}]  \
  [get_cells {csm_inst_output_text_reg[4]}]  \
  [get_cells {csm_inst_output_text_reg[50]}]  \
  [get_cells {csm_inst_output_text_reg[51]}]  \
  [get_cells {csm_inst_output_text_reg[2]}]  \
  [get_cells {csm_inst_output_text_reg[0]}]  \
  [get_cells {csm_inst_output_text_reg[40]}]  \
  [get_cells {csm_inst_output_text_reg[48]}]  \
  [get_cells {csm_inst_output_text_reg[5]}]  \
  [get_cells {csm_inst_output_text_reg[18]}]  \
  [get_cells {spi_inst_bit_cnt_reg[3]}]  \
  [get_cells {csm_inst_output_text_reg[49]}]  \
  [get_cells {csm_inst_output_text_reg[13]}]  \
  [get_cells {csm_inst_output_text_reg[33]}]  \
  [get_cells {csm_inst_output_text_reg[47]}]  \
  [get_cells {csm_inst_output_text_reg[56]}]  \
  [get_cells {csm_inst_output_text_reg[10]}]  \
  [get_cells {csm_inst_output_text_reg[41]}]  \
  [get_cells {csm_inst_output_text_reg[54]}]  \
  [get_cells {csm_inst_output_text_reg[20]}]  \
  [get_cells {csm_inst_output_text_reg[59]}]  \
  [get_cells {csm_inst_output_text_reg[25]}]  \
  [get_cells {csm_inst_output_text_reg[32]}]  \
  [get_cells {csm_inst_output_text_reg[6]}]  \
  [get_cells {csm_inst_output_text_reg[44]}]  \
  [get_cells {csm_inst_output_text_reg[8]}]  \
  [get_cells {csm_inst_output_text_reg[45]}]  \
  [get_cells {csm_inst_output_text_reg[36]}]  \
  [get_cells {csm_inst_output_text_reg[62]}]  \
  [get_cells {csm_inst_output_text_reg[16]}]  \
  [get_cells {csm_inst_output_text_reg[58]}]  \
  [get_cells {csm_inst_output_text_reg[17]}]  \
  [get_cells {csm_inst_output_text_reg[61]}]  \
  [get_cells {csm_inst_output_text_reg[63]}]  \
  [get_cells {csm_inst_output_text_reg[57]}]  \
  [get_cells {csm_inst_output_text_reg[1]}]  \
  [get_cells {csm_inst_output_text_reg[14]}]  \
  [get_cells {csm_inst_output_text_reg[11]}]  \
  [get_cells {csm_inst_output_text_reg[15]}]  \
  [get_cells {csm_inst_output_text_reg[53]}]  \
  [get_cells {csm_inst_output_text_reg[21]}]  \
  [get_cells cs_rise_delayed_reg]  \
  [get_cells {csm_inst_output_text_reg[7]}]  \
  [get_cells {csm_inst_output_text_reg[34]}]  \
  [get_cells {csm_inst_output_text_reg[42]}]  \
  [get_cells {csm_inst_output_text_reg[35]}]  \
  [get_cells {csm_inst_state_reg[2]}]  \
  [get_cells {csm_inst_output_text_reg[30]}]  \
  [get_cells {csm_inst_output_text_reg[29]}]  \
  [get_cells {csm_inst_output_text_reg[26]}]  \
  [get_cells {csm_inst_output_text_reg[31]}]  \
  [get_cells {csm_inst_output_text_reg[28]}]  \
  [get_cells {csm_inst_output_text_reg[9]}]  \
  [get_cells {csm_inst_output_text_reg[43]}]  \
  [get_cells {csm_inst_output_text_reg[27]}]  \
  [get_cells {csm_inst_output_text_reg[24]}]  \
  [get_cells {csm_inst_output_text_reg[60]}]  \
  [get_cells {csm_inst_output_text_reg[52]}]  \
  [get_cells {csm_inst_output_text_reg[23]}]  \
  [get_cells {csm_inst_output_text_reg[46]}]  \
  [get_cells {csm_inst_output_text_reg[39]}]  \
  [get_cells {csm_inst_output_text_reg[19]}]  \
  [get_cells {csm_inst_output_text_reg[37]}]  \
  [get_cells {csm_inst_output_text_reg[38]}]  \
  [get_cells {csm_inst_output_text_reg[12]}]  \
  [get_cells {csm_inst_output_text_reg[22]}]  \
  [get_cells {spi_tx_data_reg[41]}]  \
  [get_cells {spi_tx_data_reg[0]}]  \
  [get_cells {spi_tx_data_reg[42]}]  \
  [get_cells {spi_tx_data_reg[60]}]  \
  [get_cells {spi_tx_data_reg[23]}]  \
  [get_cells {spi_tx_data_reg[56]}]  \
  [get_cells {spi_tx_data_reg[50]}]  \
  [get_cells {spi_tx_data_reg[45]}]  \
  [get_cells {spi_tx_data_reg[37]}]  \
  [get_cells {spi_tx_data_reg[33]}]  \
  [get_cells {spi_tx_data_reg[26]}]  \
  [get_cells {spi_tx_data_reg[16]}]  \
  [get_cells {spi_tx_data_reg[13]}]  \
  [get_cells {spi_tx_data_reg[2]}]  \
  [get_cells {spi_tx_data_reg[32]}]  \
  [get_cells {spi_tx_data_reg[48]}]  \
  [get_cells {spi_tx_data_reg[39]}]  \
  [get_cells {spi_tx_data_reg[12]}]  \
  [get_cells {spi_tx_data_reg[7]}]  \
  [get_cells {spi_tx_data_reg[63]}]  \
  [get_cells {spi_tx_data_reg[11]}]  \
  [get_cells {spi_tx_data_reg[5]}]  \
  [get_cells {spi_tx_data_reg[8]}]  \
  [get_cells {spi_tx_data_reg[9]}]  \
  [get_cells {spi_tx_data_reg[27]}]  \
  [get_cells {spi_tx_data_reg[14]}]  \
  [get_cells {spi_tx_data_reg[15]}]  \
  [get_cells {spi_tx_data_reg[17]}]  \
  [get_cells {spi_tx_data_reg[18]}]  \
  [get_cells {spi_tx_data_reg[19]}]  \
  [get_cells {spi_tx_data_reg[21]}]  \
  [get_cells {spi_tx_data_reg[22]}]  \
  [get_cells {spi_tx_data_reg[24]}]  \
  [get_cells {spi_tx_data_reg[25]}]  \
  [get_cells {spi_tx_data_reg[58]}]  \
  [get_cells {spi_tx_data_reg[30]}]  \
  [get_cells {spi_tx_data_reg[31]}]  \
  [get_cells {spi_tx_data_reg[34]}]  \
  [get_cells {spi_tx_data_reg[35]}]  \
  [get_cells {spi_tx_data_reg[36]}]  \
  [get_cells {spi_tx_data_reg[40]}]  \
  [get_cells {spi_tx_data_reg[43]}]  \
  [get_cells {spi_tx_data_reg[46]}]  \
  [get_cells {spi_tx_data_reg[47]}]  \
  [get_cells {spi_tx_data_reg[49]}]  \
  [get_cells {spi_tx_data_reg[51]}]  \
  [get_cells {spi_tx_data_reg[53]}]  \
  [get_cells {spi_tx_data_reg[54]}]  \
  [get_cells {spi_tx_data_reg[57]}]  \
  [get_cells {spi_tx_data_reg[59]}]  \
  [get_cells {spi_tx_data_reg[62]}]  \
  [get_cells {spi_tx_data_reg[55]}]  \
  [get_cells {spi_tx_data_reg[29]}]  \
  [get_cells {spi_tx_data_reg[61]}]  \
  [get_cells {spi_tx_data_reg[52]}]  \
  [get_cells {spi_tx_data_reg[38]}]  \
  [get_cells {spi_tx_data_reg[20]}]  \
  [get_cells {spi_tx_data_reg[44]}]  \
  [get_cells {spi_tx_data_reg[28]}]  \
  [get_cells {spi_tx_data_reg[6]}]  \
  [get_cells {spi_tx_data_reg[3]}]  \
  [get_cells {spi_tx_data_reg[4]}]  \
  [get_cells {spi_tx_data_reg[10]}]  \
  [get_cells {spi_tx_data_reg[1]}]  \
  [get_cells {spi_inst_bit_cnt_reg[1]}]  \
  [get_cells {spi_inst_bit_cnt_reg[2]}]  \
  [get_cells cs_prev_reg]  \
  [get_cells active_reg]  \
  [get_cells {csm_inst_state_reg[1]}]  \
  [get_cells {spi_inst_shreg_in_reg[62]}]  \
  [get_cells cs_sync_reg]  \
  [get_cells {spi_inst_shreg_in_reg[34]}]  \
  [get_cells {spi_inst_shreg_in_reg[26]}]  \
  [get_cells {spi_inst_shreg_in_reg[30]}]  \
  [get_cells {spi_inst_shreg_in_reg[51]}]  \
  [get_cells {spi_inst_shreg_in_reg[0]}]  \
  [get_cells {spi_inst_shreg_in_reg[13]}]  \
  [get_cells {spi_inst_shreg_in_reg[18]}]  \
  [get_cells {spi_inst_shreg_in_reg[61]}]  \
  [get_cells {spi_inst_shreg_in_reg[9]}]  \
  [get_cells {spi_inst_shreg_in_reg[10]}]  \
  [get_cells {spi_inst_shreg_in_reg[16]}]  \
  [get_cells {spi_inst_shreg_in_reg[4]}]  \
  [get_cells {spi_inst_shreg_in_reg[57]}]  \
  [get_cells {spi_inst_shreg_in_reg[60]}]  \
  [get_cells {spi_inst_shreg_in_reg[48]}]  \
  [get_cells {spi_inst_shreg_in_reg[27]}]  \
  [get_cells {spi_inst_shreg_in_reg[58]}]  \
  [get_cells {spi_inst_shreg_in_reg[22]}]  \
  [get_cells {spi_inst_shreg_in_reg[45]}]  \
  [get_cells {spi_inst_shreg_in_reg[53]}]  \
  [get_cells {spi_inst_shreg_in_reg[1]}]  \
  [get_cells {spi_inst_shreg_in_reg[8]}]  \
  [get_cells {spi_inst_shreg_in_reg[56]}]  \
  [get_cells {spi_inst_shreg_in_reg[17]}]  \
  [get_cells {spi_inst_shreg_in_reg[21]}]  \
  [get_cells {spi_inst_shreg_in_reg[5]}]  \
  [get_cells {spi_inst_shreg_in_reg[55]}]  \
  [get_cells {spi_inst_shreg_in_reg[50]}]  \
  [get_cells {spi_inst_shreg_in_reg[54]}]  \
  [get_cells {spi_inst_shreg_in_reg[20]}]  \
  [get_cells {spi_inst_shreg_in_reg[29]}]  \
  [get_cells {spi_inst_shreg_in_reg[52]}]  \
  [get_cells {spi_inst_shreg_in_reg[40]}]  \
  [get_cells {spi_inst_shreg_in_reg[31]}]  \
  [get_cells {spi_inst_shreg_in_reg[14]}]  \
  [get_cells {spi_inst_shreg_in_reg[25]}]  \
  [get_cells {spi_inst_shreg_in_reg[46]}]  \
  [get_cells {spi_inst_shreg_in_reg[33]}]  \
  [get_cells {spi_inst_shreg_in_reg[7]}]  \
  [get_cells {spi_inst_shreg_in_reg[19]}]  \
  [get_cells {spi_inst_shreg_in_reg[37]}]  \
  [get_cells {spi_inst_shreg_in_reg[42]}]  \
  [get_cells {spi_inst_shreg_in_reg[28]}]  \
  [get_cells {spi_inst_shreg_in_reg[44]}]  \
  [get_cells {spi_inst_shreg_in_reg[24]}]  \
  [get_cells {spi_inst_shreg_in_reg[2]}]  \
  [get_cells {spi_inst_shreg_in_reg[35]}]  \
  [get_cells {spi_inst_shreg_in_reg[41]}]  \
  [get_cells {spi_inst_shreg_in_reg[47]}]  \
  [get_cells {spi_inst_shreg_in_reg[43]}]  \
  [get_cells {spi_inst_shreg_in_reg[3]}]  \
  [get_cells {spi_inst_shreg_in_reg[59]}]  \
  [get_cells {spi_inst_shreg_in_reg[23]}]  \
  [get_cells {spi_inst_shreg_in_reg[6]}]  \
  [get_cells {spi_inst_shreg_in_reg[32]}]  \
  [get_cells {spi_inst_shreg_in_reg[15]}]  \
  [get_cells {spi_inst_shreg_in_reg[11]}]  \
  [get_cells {spi_inst_shreg_in_reg[38]}]  \
  [get_cells {spi_inst_shreg_in_reg[36]}]  \
  [get_cells {spi_inst_shreg_in_reg[49]}]  \
  [get_cells {spi_inst_shreg_in_reg[12]}]  \
  [get_cells {spi_inst_shreg_in_reg[39]}]  \
  [get_cells cs_meta_reg]  \
  [get_cells {spi_inst_bit_cnt_reg[0]}] ]
group_path -weight 1.000000 -name C2O -from [list \
  [get_cells spi_inst_miso_q_reg]  \
  [get_cells {spi_inst_shreg_out_reg[63]}]  \
  [get_cells {spi_inst_shreg_out_reg[62]}]  \
  [get_cells {spi_inst_shreg_out_reg[61]}]  \
  [get_cells {spi_inst_shreg_out_reg[60]}]  \
  [get_cells {spi_inst_shreg_out_reg[59]}]  \
  [get_cells {spi_inst_shreg_out_reg[58]}]  \
  [get_cells {spi_inst_shreg_out_reg[57]}]  \
  [get_cells {spi_inst_shreg_out_reg[56]}]  \
  [get_cells {spi_inst_shreg_out_reg[55]}]  \
  [get_cells {spi_inst_shreg_out_reg[54]}]  \
  [get_cells {spi_inst_shreg_out_reg[53]}]  \
  [get_cells {spi_inst_shreg_out_reg[52]}]  \
  [get_cells {spi_inst_shreg_out_reg[51]}]  \
  [get_cells {spi_inst_shreg_out_reg[50]}]  \
  [get_cells {spi_inst_shreg_out_reg[49]}]  \
  [get_cells {spi_inst_shreg_out_reg[48]}]  \
  [get_cells {spi_inst_shreg_out_reg[47]}]  \
  [get_cells {spi_inst_shreg_out_reg[46]}]  \
  [get_cells {spi_inst_shreg_out_reg[45]}]  \
  [get_cells {spi_inst_shreg_out_reg[44]}]  \
  [get_cells {spi_inst_shreg_out_reg[43]}]  \
  [get_cells {spi_inst_shreg_out_reg[42]}]  \
  [get_cells {spi_inst_shreg_out_reg[41]}]  \
  [get_cells {spi_inst_shreg_out_reg[40]}]  \
  [get_cells {spi_inst_shreg_out_reg[39]}]  \
  [get_cells {spi_inst_shreg_out_reg[38]}]  \
  [get_cells {spi_inst_shreg_out_reg[37]}]  \
  [get_cells {spi_inst_shreg_out_reg[36]}]  \
  [get_cells {spi_inst_shreg_out_reg[35]}]  \
  [get_cells {spi_inst_shreg_out_reg[34]}]  \
  [get_cells {spi_inst_shreg_out_reg[33]}]  \
  [get_cells {spi_inst_shreg_out_reg[32]}]  \
  [get_cells {spi_inst_shreg_out_reg[31]}]  \
  [get_cells {spi_inst_shreg_out_reg[30]}]  \
  [get_cells {spi_inst_shreg_out_reg[29]}]  \
  [get_cells {spi_inst_shreg_out_reg[28]}]  \
  [get_cells {spi_inst_shreg_out_reg[27]}]  \
  [get_cells {spi_inst_shreg_out_reg[26]}]  \
  [get_cells {spi_inst_shreg_out_reg[25]}]  \
  [get_cells {spi_inst_shreg_out_reg[24]}]  \
  [get_cells {spi_inst_shreg_out_reg[23]}]  \
  [get_cells {spi_inst_shreg_out_reg[22]}]  \
  [get_cells {spi_inst_shreg_out_reg[21]}]  \
  [get_cells {spi_inst_shreg_out_reg[20]}]  \
  [get_cells {spi_inst_shreg_out_reg[19]}]  \
  [get_cells {spi_inst_shreg_out_reg[18]}]  \
  [get_cells {spi_inst_shreg_out_reg[17]}]  \
  [get_cells {spi_inst_shreg_out_reg[16]}]  \
  [get_cells {spi_inst_shreg_out_reg[15]}]  \
  [get_cells {spi_inst_shreg_out_reg[14]}]  \
  [get_cells {spi_inst_shreg_out_reg[13]}]  \
  [get_cells {spi_inst_shreg_out_reg[12]}]  \
  [get_cells {spi_inst_shreg_out_reg[11]}]  \
  [get_cells {spi_inst_shreg_out_reg[10]}]  \
  [get_cells {spi_inst_shreg_out_reg[9]}]  \
  [get_cells {csm_inst_right_reg_reg[6]}]  \
  [get_cells {csm_inst_right_reg_reg[17]}]  \
  [get_cells {csm_inst_right_reg_reg[5]}]  \
  [get_cells {csm_inst_right_reg_reg[19]}]  \
  [get_cells {csm_inst_right_reg_reg[11]}]  \
  [get_cells {csm_inst_right_reg_reg[22]}]  \
  [get_cells {csm_inst_right_reg_reg[9]}]  \
  [get_cells {csm_inst_right_reg_reg[1]}]  \
  [get_cells {csm_inst_right_reg_reg[16]}]  \
  [get_cells {csm_inst_right_reg_reg[3]}]  \
  [get_cells {csm_inst_right_reg_reg[8]}]  \
  [get_cells {csm_inst_right_reg_reg[31]}]  \
  [get_cells {csm_inst_right_reg_reg[21]}]  \
  [get_cells {csm_inst_right_reg_reg[13]}]  \
  [get_cells {csm_inst_right_reg_reg[10]}]  \
  [get_cells {csm_inst_right_reg_reg[12]}]  \
  [get_cells {csm_inst_right_reg_reg[27]}]  \
  [get_cells {csm_inst_right_reg_reg[15]}]  \
  [get_cells {csm_inst_right_reg_reg[23]}]  \
  [get_cells {csm_inst_right_reg_reg[0]}]  \
  [get_cells {csm_inst_right_reg_reg[14]}]  \
  [get_cells {csm_inst_right_reg_reg[26]}]  \
  [get_cells {csm_inst_right_reg_reg[25]}]  \
  [get_cells {csm_inst_right_reg_reg[29]}]  \
  [get_cells {csm_inst_right_reg_reg[18]}]  \
  [get_cells {csm_inst_right_reg_reg[24]}]  \
  [get_cells {csm_inst_right_reg_reg[4]}]  \
  [get_cells {spi_inst_shreg_out_reg[8]}]  \
  [get_cells {csm_inst_right_reg_reg[7]}]  \
  [get_cells {csm_inst_right_reg_reg[2]}]  \
  [get_cells {csm_inst_right_reg_reg[30]}]  \
  [get_cells {csm_inst_right_reg_reg[20]}]  \
  [get_cells {csm_inst_right_reg_reg[28]}]  \
  [get_cells {spi_inst_shreg_out_reg[7]}]  \
  [get_cells {spi_inst_shreg_out_reg[6]}]  \
  [get_cells {spi_inst_shreg_out_reg[5]}]  \
  [get_cells {spi_inst_shreg_out_reg[4]}]  \
  [get_cells {spi_inst_shreg_out_reg[3]}]  \
  [get_cells start_encrypt_reg]  \
  [get_cells start_decrypt_reg]  \
  [get_cells {key_reg_reg[39]}]  \
  [get_cells {key_reg_reg[18]}]  \
  [get_cells {key_reg_reg[14]}]  \
  [get_cells {key_reg_reg[55]}]  \
  [get_cells {key_reg_reg[5]}]  \
  [get_cells {key_reg_reg[11]}]  \
  [get_cells {key_reg_reg[30]}]  \
  [get_cells {key_reg_reg[62]}]  \
  [get_cells {key_reg_reg[59]}]  \
  [get_cells {key_reg_reg[37]}]  \
  [get_cells {key_reg_reg[45]}]  \
  [get_cells {key_reg_reg[50]}]  \
  [get_cells {key_reg_reg[47]}]  \
  [get_cells {key_reg_reg[57]}]  \
  [get_cells {key_reg_reg[61]}]  \
  [get_cells {key_reg_reg[13]}]  \
  [get_cells {key_reg_reg[33]}]  \
  [get_cells {key_reg_reg[31]}]  \
  [get_cells {key_reg_reg[35]}]  \
  [get_cells {key_reg_reg[54]}]  \
  [get_cells {key_reg_reg[53]}]  \
  [get_cells {key_reg_reg[44]}]  \
  [get_cells {key_reg_reg[51]}]  \
  [get_cells {key_reg_reg[49]}]  \
  [get_cells {key_reg_reg[60]}]  \
  [get_cells {key_reg_reg[2]}]  \
  [get_cells {key_reg_reg[15]}]  \
  [get_cells {key_reg_reg[42]}]  \
  [get_cells {key_reg_reg[10]}]  \
  [get_cells {key_reg_reg[52]}]  \
  [get_cells {key_reg_reg[63]}]  \
  [get_cells {key_reg_reg[25]}]  \
  [get_cells {key_reg_reg[58]}]  \
  [get_cells {key_reg_reg[26]}]  \
  [get_cells {key_reg_reg[3]}]  \
  [get_cells {key_reg_reg[36]}]  \
  [get_cells {key_reg_reg[21]}]  \
  [get_cells {key_reg_reg[23]}]  \
  [get_cells {key_reg_reg[34]}]  \
  [get_cells {key_reg_reg[20]}]  \
  [get_cells {key_reg_reg[1]}]  \
  [get_cells {key_reg_reg[19]}]  \
  [get_cells {key_reg_reg[17]}]  \
  [get_cells {key_reg_reg[6]}]  \
  [get_cells {key_reg_reg[29]}]  \
  [get_cells {key_reg_reg[43]}]  \
  [get_cells {key_reg_reg[4]}]  \
  [get_cells {key_reg_reg[28]}]  \
  [get_cells {key_reg_reg[22]}]  \
  [get_cells {key_reg_reg[12]}]  \
  [get_cells {key_reg_reg[9]}]  \
  [get_cells {key_reg_reg[38]}]  \
  [get_cells {key_reg_reg[46]}]  \
  [get_cells {key_reg_reg[7]}]  \
  [get_cells {key_reg_reg[27]}]  \
  [get_cells {key_reg_reg[41]}]  \
  [get_cells {spi_inst_input_text_reg[24]}]  \
  [get_cells {spi_inst_input_text_reg[8]}]  \
  [get_cells {spi_inst_input_text_reg[40]}]  \
  [get_cells {spi_inst_input_text_reg[56]}]  \
  [get_cells done_decrypt_latched_reg]  \
  [get_cells done_encrypt_latched_reg]  \
  [get_cells {spi_inst_input_text_reg[4]}]  \
  [get_cells {spi_inst_input_text_reg[6]}]  \
  [get_cells {spi_inst_input_text_reg[0]}]  \
  [get_cells {spi_inst_input_text_reg[10]}]  \
  [get_cells {spi_inst_input_text_reg[12]}]  \
  [get_cells {spi_inst_input_text_reg[14]}]  \
  [get_cells {spi_inst_input_text_reg[15]}]  \
  [get_cells {spi_inst_input_text_reg[1]}]  \
  [get_cells {spi_inst_input_text_reg[18]}]  \
  [get_cells {spi_inst_input_text_reg[20]}]  \
  [get_cells {spi_inst_input_text_reg[22]}]  \
  [get_cells {spi_inst_input_text_reg[2]}]  \
  [get_cells {spi_inst_input_text_reg[26]}]  \
  [get_cells {spi_inst_input_text_reg[28]}]  \
  [get_cells {spi_inst_input_text_reg[30]}]  \
  [get_cells {spi_inst_input_text_reg[33]}]  \
  [get_cells {spi_inst_input_text_reg[34]}]  \
  [get_cells {spi_inst_input_text_reg[36]}]  \
  [get_cells {spi_inst_input_text_reg[44]}]  \
  [get_cells {spi_inst_input_text_reg[46]}]  \
  [get_cells {spi_inst_input_text_reg[52]}]  \
  [get_cells {spi_inst_input_text_reg[53]}]  \
  [get_cells {spi_inst_input_text_reg[54]}]  \
  [get_cells {spi_inst_input_text_reg[57]}]  \
  [get_cells {spi_inst_input_text_reg[38]}]  \
  [get_cells {spi_inst_input_text_reg[58]}]  \
  [get_cells {spi_inst_input_text_reg[60]}]  \
  [get_cells {spi_inst_input_text_reg[63]}]  \
  [get_cells {spi_inst_input_text_reg[41]}]  \
  [get_cells {spi_inst_input_text_reg[43]}]  \
  [get_cells {spi_inst_input_text_reg[45]}]  \
  [get_cells {spi_inst_input_text_reg[47]}]  \
  [get_cells {spi_inst_input_text_reg[39]}]  \
  [get_cells {spi_inst_input_text_reg[49]}]  \
  [get_cells {spi_inst_input_text_reg[31]}]  \
  [get_cells {spi_inst_input_text_reg[3]}]  \
  [get_cells {spi_inst_input_text_reg[42]}]  \
  [get_cells {spi_inst_input_text_reg[48]}]  \
  [get_cells {spi_inst_input_text_reg[32]}]  \
  [get_cells {spi_inst_input_text_reg[16]}]  \
  [get_cells {spi_inst_input_text_reg[7]}]  \
  [get_cells {spi_inst_input_text_reg[37]}]  \
  [get_cells {spi_inst_input_text_reg[5]}]  \
  [get_cells {spi_inst_input_text_reg[35]}]  \
  [get_cells {spi_inst_input_text_reg[23]}]  \
  [get_cells {spi_inst_input_text_reg[17]}]  \
  [get_cells {spi_inst_input_text_reg[55]}]  \
  [get_cells {spi_inst_input_text_reg[61]}]  \
  [get_cells {spi_inst_input_text_reg[25]}]  \
  [get_cells {spi_inst_input_text_reg[19]}]  \
  [get_cells {spi_inst_input_text_reg[21]}]  \
  [get_cells {spi_inst_input_text_reg[59]}]  \
  [get_cells crypt_reg]  \
  [get_cells {spi_inst_input_text_reg[9]}]  \
  [get_cells {spi_inst_input_text_reg[13]}]  \
  [get_cells {spi_inst_input_text_reg[50]}]  \
  [get_cells {spi_inst_input_text_reg[51]}]  \
  [get_cells {spi_inst_input_text_reg[62]}]  \
  [get_cells {spi_inst_input_text_reg[11]}]  \
  [get_cells {spi_inst_input_text_reg[27]}]  \
  [get_cells {spi_inst_input_text_reg[29]}]  \
  [get_cells {transaction_state_reg[1]}]  \
  [get_cells {transaction_state_reg[0]}]  \
  [get_cells {data_reg_reg[46]}]  \
  [get_cells {data_reg_reg[47]}]  \
  [get_cells {data_reg_reg[49]}]  \
  [get_cells {data_reg_reg[51]}]  \
  [get_cells {data_reg_reg[53]}]  \
  [get_cells {data_reg_reg[55]}]  \
  [get_cells {data_reg_reg[57]}]  \
  [get_cells {data_reg_reg[59]}]  \
  [get_cells {data_reg_reg[61]}]  \
  [get_cells {data_reg_reg[8]}]  \
  [get_cells {data_reg_reg[16]}]  \
  [get_cells {spi_inst_bit_cnt_reg[6]}]  \
  [get_cells {data_reg_reg[4]}]  \
  [get_cells {data_reg_reg[0]}]  \
  [get_cells {data_reg_reg[58]}]  \
  [get_cells {data_reg_reg[62]}]  \
  [get_cells {data_reg_reg[63]}]  \
  [get_cells {data_reg_reg[10]}]  \
  [get_cells {data_reg_reg[20]}]  \
  [get_cells {data_reg_reg[22]}]  \
  [get_cells {data_reg_reg[24]}]  \
  [get_cells {data_reg_reg[18]}]  \
  [get_cells {data_reg_reg[2]}]  \
  [get_cells {data_reg_reg[6]}]  \
  [get_cells {data_reg_reg[12]}]  \
  [get_cells {data_reg_reg[1]}]  \
  [get_cells {data_reg_reg[3]}]  \
  [get_cells {data_reg_reg[60]}]  \
  [get_cells {data_reg_reg[5]}]  \
  [get_cells {data_reg_reg[7]}]  \
  [get_cells {data_reg_reg[9]}]  \
  [get_cells {data_reg_reg[11]}]  \
  [get_cells {data_reg_reg[13]}]  \
  [get_cells {data_reg_reg[14]}]  \
  [get_cells {data_reg_reg[15]}]  \
  [get_cells {data_reg_reg[56]}]  \
  [get_cells {data_reg_reg[17]}]  \
  [get_cells {data_reg_reg[19]}]  \
  [get_cells {data_reg_reg[21]}]  \
  [get_cells {data_reg_reg[23]}]  \
  [get_cells {data_reg_reg[25]}]  \
  [get_cells {data_reg_reg[27]}]  \
  [get_cells {data_reg_reg[29]}]  \
  [get_cells {data_reg_reg[31]}]  \
  [get_cells {data_reg_reg[33]}]  \
  [get_cells {data_reg_reg[35]}]  \
  [get_cells {data_reg_reg[54]}]  \
  [get_cells {data_reg_reg[37]}]  \
  [get_cells {data_reg_reg[39]}]  \
  [get_cells {data_reg_reg[41]}]  \
  [get_cells {data_reg_reg[43]}]  \
  [get_cells {data_reg_reg[45]}]  \
  [get_cells {data_reg_reg[52]}]  \
  [get_cells {data_reg_reg[30]}]  \
  [get_cells {data_reg_reg[32]}]  \
  [get_cells {data_reg_reg[34]}]  \
  [get_cells {data_reg_reg[36]}]  \
  [get_cells {data_reg_reg[28]}]  \
  [get_cells {data_reg_reg[38]}]  \
  [get_cells {data_reg_reg[40]}]  \
  [get_cells {data_reg_reg[42]}]  \
  [get_cells {data_reg_reg[44]}]  \
  [get_cells {data_reg_reg[26]}]  \
  [get_cells {data_reg_reg[48]}]  \
  [get_cells {data_reg_reg[50]}]  \
  [get_cells {spi_inst_shreg_out_reg[2]}]  \
  [get_cells trigger_operation_reg]  \
  [get_cells {spi_inst_bit_cnt_reg[5]}]  \
  [get_cells {csm_inst_round_counter_reg[3]}]  \
  [get_cells {csm_inst_left_reg_reg[11]}]  \
  [get_cells {csm_inst_left_reg_reg[17]}]  \
  [get_cells {csm_inst_left_reg_reg[5]}]  \
  [get_cells {csm_inst_left_reg_reg[30]}]  \
  [get_cells {csm_inst_left_reg_reg[27]}]  \
  [get_cells {csm_inst_left_reg_reg[4]}]  \
  [get_cells {csm_inst_left_reg_reg[3]}]  \
  [get_cells {csm_inst_left_reg_reg[13]}]  \
  [get_cells {csm_inst_left_reg_reg[31]}]  \
  [get_cells {csm_inst_left_reg_reg[6]}]  \
  [get_cells {csm_inst_left_reg_reg[8]}]  \
  [get_cells {csm_inst_left_reg_reg[9]}]  \
  [get_cells {csm_inst_left_reg_reg[1]}]  \
  [get_cells {csm_inst_left_reg_reg[22]}]  \
  [get_cells {csm_inst_left_reg_reg[19]}]  \
  [get_cells {csm_inst_left_reg_reg[16]}]  \
  [get_cells {csm_inst_left_reg_reg[20]}]  \
  [get_cells {csm_inst_left_reg_reg[21]}]  \
  [get_cells {csm_inst_left_reg_reg[7]}]  \
  [get_cells {csm_inst_left_reg_reg[24]}]  \
  [get_cells {csm_inst_left_reg_reg[26]}]  \
  [get_cells {csm_inst_left_reg_reg[28]}]  \
  [get_cells {csm_inst_left_reg_reg[15]}]  \
  [get_cells {csm_inst_left_reg_reg[25]}]  \
  [get_cells {csm_inst_left_reg_reg[29]}]  \
  [get_cells {csm_inst_left_reg_reg[10]}]  \
  [get_cells {csm_inst_left_reg_reg[18]}]  \
  [get_cells {csm_inst_left_reg_reg[12]}]  \
  [get_cells {csm_inst_left_reg_reg[2]}]  \
  [get_cells {csm_inst_left_reg_reg[0]}]  \
  [get_cells {csm_inst_left_reg_reg[23]}]  \
  [get_cells {csm_inst_left_reg_reg[14]}]  \
  [get_cells {spi_inst_shreg_out_reg[1]}]  \
  [get_cells {spi_inst_bit_cnt_reg[4]}]  \
  [get_cells {csm_inst_round_counter_reg[2]}]  \
  [get_cells csm_inst_mode_reg]  \
  [get_cells {csm_inst_round_counter_reg[1]}]  \
  [get_cells {csm_inst_state_reg[0]}]  \
  [get_cells csm_inst_done_encrypt_reg]  \
  [get_cells csm_inst_done_decrypt_reg]  \
  [get_cells {csm_inst_round_counter_reg[0]}]  \
  [get_cells {csm_inst_output_text_reg[3]}]  \
  [get_cells {csm_inst_output_text_reg[55]}]  \
  [get_cells {csm_inst_output_text_reg[4]}]  \
  [get_cells {csm_inst_output_text_reg[50]}]  \
  [get_cells {csm_inst_output_text_reg[51]}]  \
  [get_cells {csm_inst_output_text_reg[2]}]  \
  [get_cells {csm_inst_output_text_reg[0]}]  \
  [get_cells {csm_inst_output_text_reg[40]}]  \
  [get_cells {csm_inst_output_text_reg[48]}]  \
  [get_cells {csm_inst_output_text_reg[5]}]  \
  [get_cells {csm_inst_output_text_reg[18]}]  \
  [get_cells {spi_inst_bit_cnt_reg[3]}]  \
  [get_cells {csm_inst_output_text_reg[49]}]  \
  [get_cells {csm_inst_output_text_reg[13]}]  \
  [get_cells {csm_inst_output_text_reg[33]}]  \
  [get_cells {csm_inst_output_text_reg[47]}]  \
  [get_cells {csm_inst_output_text_reg[56]}]  \
  [get_cells {csm_inst_output_text_reg[10]}]  \
  [get_cells {csm_inst_output_text_reg[41]}]  \
  [get_cells {csm_inst_output_text_reg[54]}]  \
  [get_cells {csm_inst_output_text_reg[20]}]  \
  [get_cells {csm_inst_output_text_reg[59]}]  \
  [get_cells {csm_inst_output_text_reg[25]}]  \
  [get_cells {csm_inst_output_text_reg[32]}]  \
  [get_cells {csm_inst_output_text_reg[6]}]  \
  [get_cells {csm_inst_output_text_reg[44]}]  \
  [get_cells {csm_inst_output_text_reg[8]}]  \
  [get_cells {csm_inst_output_text_reg[45]}]  \
  [get_cells {csm_inst_output_text_reg[36]}]  \
  [get_cells {csm_inst_output_text_reg[62]}]  \
  [get_cells {csm_inst_output_text_reg[16]}]  \
  [get_cells {csm_inst_output_text_reg[58]}]  \
  [get_cells {csm_inst_output_text_reg[17]}]  \
  [get_cells {csm_inst_output_text_reg[61]}]  \
  [get_cells {csm_inst_output_text_reg[63]}]  \
  [get_cells {csm_inst_output_text_reg[57]}]  \
  [get_cells {csm_inst_output_text_reg[1]}]  \
  [get_cells {csm_inst_output_text_reg[14]}]  \
  [get_cells {csm_inst_output_text_reg[11]}]  \
  [get_cells {csm_inst_output_text_reg[15]}]  \
  [get_cells {csm_inst_output_text_reg[53]}]  \
  [get_cells {csm_inst_output_text_reg[21]}]  \
  [get_cells cs_rise_delayed_reg]  \
  [get_cells {csm_inst_output_text_reg[7]}]  \
  [get_cells {csm_inst_output_text_reg[34]}]  \
  [get_cells {csm_inst_output_text_reg[42]}]  \
  [get_cells {csm_inst_output_text_reg[35]}]  \
  [get_cells {csm_inst_state_reg[2]}]  \
  [get_cells {csm_inst_output_text_reg[30]}]  \
  [get_cells {csm_inst_output_text_reg[29]}]  \
  [get_cells {csm_inst_output_text_reg[26]}]  \
  [get_cells {csm_inst_output_text_reg[31]}]  \
  [get_cells {csm_inst_output_text_reg[28]}]  \
  [get_cells {csm_inst_output_text_reg[9]}]  \
  [get_cells {csm_inst_output_text_reg[43]}]  \
  [get_cells {csm_inst_output_text_reg[27]}]  \
  [get_cells {csm_inst_output_text_reg[24]}]  \
  [get_cells {csm_inst_output_text_reg[60]}]  \
  [get_cells {csm_inst_output_text_reg[52]}]  \
  [get_cells {csm_inst_output_text_reg[23]}]  \
  [get_cells {csm_inst_output_text_reg[46]}]  \
  [get_cells {csm_inst_output_text_reg[39]}]  \
  [get_cells {csm_inst_output_text_reg[19]}]  \
  [get_cells {csm_inst_output_text_reg[37]}]  \
  [get_cells {csm_inst_output_text_reg[38]}]  \
  [get_cells {csm_inst_output_text_reg[12]}]  \
  [get_cells {csm_inst_output_text_reg[22]}]  \
  [get_cells {spi_tx_data_reg[41]}]  \
  [get_cells {spi_tx_data_reg[0]}]  \
  [get_cells {spi_tx_data_reg[42]}]  \
  [get_cells {spi_tx_data_reg[60]}]  \
  [get_cells {spi_tx_data_reg[23]}]  \
  [get_cells {spi_tx_data_reg[56]}]  \
  [get_cells {spi_tx_data_reg[50]}]  \
  [get_cells {spi_tx_data_reg[45]}]  \
  [get_cells {spi_tx_data_reg[37]}]  \
  [get_cells {spi_tx_data_reg[33]}]  \
  [get_cells {spi_tx_data_reg[26]}]  \
  [get_cells {spi_tx_data_reg[16]}]  \
  [get_cells {spi_tx_data_reg[13]}]  \
  [get_cells {spi_tx_data_reg[2]}]  \
  [get_cells {spi_tx_data_reg[32]}]  \
  [get_cells {spi_tx_data_reg[48]}]  \
  [get_cells {spi_tx_data_reg[39]}]  \
  [get_cells {spi_tx_data_reg[12]}]  \
  [get_cells {spi_tx_data_reg[7]}]  \
  [get_cells {spi_tx_data_reg[63]}]  \
  [get_cells {spi_tx_data_reg[11]}]  \
  [get_cells {spi_tx_data_reg[5]}]  \
  [get_cells {spi_tx_data_reg[8]}]  \
  [get_cells {spi_tx_data_reg[9]}]  \
  [get_cells {spi_tx_data_reg[27]}]  \
  [get_cells {spi_tx_data_reg[14]}]  \
  [get_cells {spi_tx_data_reg[15]}]  \
  [get_cells {spi_tx_data_reg[17]}]  \
  [get_cells {spi_tx_data_reg[18]}]  \
  [get_cells {spi_tx_data_reg[19]}]  \
  [get_cells {spi_tx_data_reg[21]}]  \
  [get_cells {spi_tx_data_reg[22]}]  \
  [get_cells {spi_tx_data_reg[24]}]  \
  [get_cells {spi_tx_data_reg[25]}]  \
  [get_cells {spi_tx_data_reg[58]}]  \
  [get_cells {spi_tx_data_reg[30]}]  \
  [get_cells {spi_tx_data_reg[31]}]  \
  [get_cells {spi_tx_data_reg[34]}]  \
  [get_cells {spi_tx_data_reg[35]}]  \
  [get_cells {spi_tx_data_reg[36]}]  \
  [get_cells {spi_tx_data_reg[40]}]  \
  [get_cells {spi_tx_data_reg[43]}]  \
  [get_cells {spi_tx_data_reg[46]}]  \
  [get_cells {spi_tx_data_reg[47]}]  \
  [get_cells {spi_tx_data_reg[49]}]  \
  [get_cells {spi_tx_data_reg[51]}]  \
  [get_cells {spi_tx_data_reg[53]}]  \
  [get_cells {spi_tx_data_reg[54]}]  \
  [get_cells {spi_tx_data_reg[57]}]  \
  [get_cells {spi_tx_data_reg[59]}]  \
  [get_cells {spi_tx_data_reg[62]}]  \
  [get_cells {spi_tx_data_reg[55]}]  \
  [get_cells {spi_tx_data_reg[29]}]  \
  [get_cells {spi_tx_data_reg[61]}]  \
  [get_cells {spi_tx_data_reg[52]}]  \
  [get_cells {spi_tx_data_reg[38]}]  \
  [get_cells {spi_tx_data_reg[20]}]  \
  [get_cells {spi_tx_data_reg[44]}]  \
  [get_cells {spi_tx_data_reg[28]}]  \
  [get_cells {spi_tx_data_reg[6]}]  \
  [get_cells {spi_tx_data_reg[3]}]  \
  [get_cells {spi_tx_data_reg[4]}]  \
  [get_cells {spi_tx_data_reg[10]}]  \
  [get_cells {spi_tx_data_reg[1]}]  \
  [get_cells {spi_inst_bit_cnt_reg[1]}]  \
  [get_cells {spi_inst_bit_cnt_reg[2]}]  \
  [get_cells cs_prev_reg]  \
  [get_cells active_reg]  \
  [get_cells {csm_inst_state_reg[1]}]  \
  [get_cells {spi_inst_shreg_in_reg[62]}]  \
  [get_cells cs_sync_reg]  \
  [get_cells {spi_inst_shreg_in_reg[34]}]  \
  [get_cells {spi_inst_shreg_in_reg[26]}]  \
  [get_cells {spi_inst_shreg_in_reg[30]}]  \
  [get_cells {spi_inst_shreg_in_reg[51]}]  \
  [get_cells {spi_inst_shreg_in_reg[0]}]  \
  [get_cells {spi_inst_shreg_in_reg[13]}]  \
  [get_cells {spi_inst_shreg_in_reg[18]}]  \
  [get_cells {spi_inst_shreg_in_reg[61]}]  \
  [get_cells {spi_inst_shreg_in_reg[9]}]  \
  [get_cells {spi_inst_shreg_in_reg[10]}]  \
  [get_cells {spi_inst_shreg_in_reg[16]}]  \
  [get_cells {spi_inst_shreg_in_reg[4]}]  \
  [get_cells {spi_inst_shreg_in_reg[57]}]  \
  [get_cells {spi_inst_shreg_in_reg[60]}]  \
  [get_cells {spi_inst_shreg_in_reg[48]}]  \
  [get_cells {spi_inst_shreg_in_reg[27]}]  \
  [get_cells {spi_inst_shreg_in_reg[58]}]  \
  [get_cells {spi_inst_shreg_in_reg[22]}]  \
  [get_cells {spi_inst_shreg_in_reg[45]}]  \
  [get_cells {spi_inst_shreg_in_reg[53]}]  \
  [get_cells {spi_inst_shreg_in_reg[1]}]  \
  [get_cells {spi_inst_shreg_in_reg[8]}]  \
  [get_cells {spi_inst_shreg_in_reg[56]}]  \
  [get_cells {spi_inst_shreg_in_reg[17]}]  \
  [get_cells {spi_inst_shreg_in_reg[21]}]  \
  [get_cells {spi_inst_shreg_in_reg[5]}]  \
  [get_cells {spi_inst_shreg_in_reg[55]}]  \
  [get_cells {spi_inst_shreg_in_reg[50]}]  \
  [get_cells {spi_inst_shreg_in_reg[54]}]  \
  [get_cells {spi_inst_shreg_in_reg[20]}]  \
  [get_cells {spi_inst_shreg_in_reg[29]}]  \
  [get_cells {spi_inst_shreg_in_reg[52]}]  \
  [get_cells {spi_inst_shreg_in_reg[40]}]  \
  [get_cells {spi_inst_shreg_in_reg[31]}]  \
  [get_cells {spi_inst_shreg_in_reg[14]}]  \
  [get_cells {spi_inst_shreg_in_reg[25]}]  \
  [get_cells {spi_inst_shreg_in_reg[46]}]  \
  [get_cells {spi_inst_shreg_in_reg[33]}]  \
  [get_cells {spi_inst_shreg_in_reg[7]}]  \
  [get_cells {spi_inst_shreg_in_reg[19]}]  \
  [get_cells {spi_inst_shreg_in_reg[37]}]  \
  [get_cells {spi_inst_shreg_in_reg[42]}]  \
  [get_cells {spi_inst_shreg_in_reg[28]}]  \
  [get_cells {spi_inst_shreg_in_reg[44]}]  \
  [get_cells {spi_inst_shreg_in_reg[24]}]  \
  [get_cells {spi_inst_shreg_in_reg[2]}]  \
  [get_cells {spi_inst_shreg_in_reg[35]}]  \
  [get_cells {spi_inst_shreg_in_reg[41]}]  \
  [get_cells {spi_inst_shreg_in_reg[47]}]  \
  [get_cells {spi_inst_shreg_in_reg[43]}]  \
  [get_cells {spi_inst_shreg_in_reg[3]}]  \
  [get_cells {spi_inst_shreg_in_reg[59]}]  \
  [get_cells {spi_inst_shreg_in_reg[23]}]  \
  [get_cells {spi_inst_shreg_in_reg[6]}]  \
  [get_cells {spi_inst_shreg_in_reg[32]}]  \
  [get_cells {spi_inst_shreg_in_reg[15]}]  \
  [get_cells {spi_inst_shreg_in_reg[11]}]  \
  [get_cells {spi_inst_shreg_in_reg[38]}]  \
  [get_cells {spi_inst_shreg_in_reg[36]}]  \
  [get_cells {spi_inst_shreg_in_reg[49]}]  \
  [get_cells {spi_inst_shreg_in_reg[12]}]  \
  [get_cells {spi_inst_shreg_in_reg[39]}]  \
  [get_cells cs_meta_reg]  \
  [get_cells {spi_inst_bit_cnt_reg[0]}] ] -to [get_ports miso]
group_path -weight 1.000000 -name I2C -from [list \
  [get_ports clk]  \
  [get_ports rst]  \
  [get_ports sclk]  \
  [get_ports cs_n]  \
  [get_ports mosi] ] -to [list \
  [get_cells spi_inst_miso_q_reg]  \
  [get_cells {spi_inst_shreg_out_reg[63]}]  \
  [get_cells {spi_inst_shreg_out_reg[62]}]  \
  [get_cells {spi_inst_shreg_out_reg[61]}]  \
  [get_cells {spi_inst_shreg_out_reg[60]}]  \
  [get_cells {spi_inst_shreg_out_reg[59]}]  \
  [get_cells {spi_inst_shreg_out_reg[58]}]  \
  [get_cells {spi_inst_shreg_out_reg[57]}]  \
  [get_cells {spi_inst_shreg_out_reg[56]}]  \
  [get_cells {spi_inst_shreg_out_reg[55]}]  \
  [get_cells {spi_inst_shreg_out_reg[54]}]  \
  [get_cells {spi_inst_shreg_out_reg[53]}]  \
  [get_cells {spi_inst_shreg_out_reg[52]}]  \
  [get_cells {spi_inst_shreg_out_reg[51]}]  \
  [get_cells {spi_inst_shreg_out_reg[50]}]  \
  [get_cells {spi_inst_shreg_out_reg[49]}]  \
  [get_cells {spi_inst_shreg_out_reg[48]}]  \
  [get_cells {spi_inst_shreg_out_reg[47]}]  \
  [get_cells {spi_inst_shreg_out_reg[46]}]  \
  [get_cells {spi_inst_shreg_out_reg[45]}]  \
  [get_cells {spi_inst_shreg_out_reg[44]}]  \
  [get_cells {spi_inst_shreg_out_reg[43]}]  \
  [get_cells {spi_inst_shreg_out_reg[42]}]  \
  [get_cells {spi_inst_shreg_out_reg[41]}]  \
  [get_cells {spi_inst_shreg_out_reg[40]}]  \
  [get_cells {spi_inst_shreg_out_reg[39]}]  \
  [get_cells {spi_inst_shreg_out_reg[38]}]  \
  [get_cells {spi_inst_shreg_out_reg[37]}]  \
  [get_cells {spi_inst_shreg_out_reg[36]}]  \
  [get_cells {spi_inst_shreg_out_reg[35]}]  \
  [get_cells {spi_inst_shreg_out_reg[34]}]  \
  [get_cells {spi_inst_shreg_out_reg[33]}]  \
  [get_cells {spi_inst_shreg_out_reg[32]}]  \
  [get_cells {spi_inst_shreg_out_reg[31]}]  \
  [get_cells {spi_inst_shreg_out_reg[30]}]  \
  [get_cells {spi_inst_shreg_out_reg[29]}]  \
  [get_cells {spi_inst_shreg_out_reg[28]}]  \
  [get_cells {spi_inst_shreg_out_reg[27]}]  \
  [get_cells {spi_inst_shreg_out_reg[26]}]  \
  [get_cells {spi_inst_shreg_out_reg[25]}]  \
  [get_cells {spi_inst_shreg_out_reg[24]}]  \
  [get_cells {spi_inst_shreg_out_reg[23]}]  \
  [get_cells {spi_inst_shreg_out_reg[22]}]  \
  [get_cells {spi_inst_shreg_out_reg[21]}]  \
  [get_cells {spi_inst_shreg_out_reg[20]}]  \
  [get_cells {spi_inst_shreg_out_reg[19]}]  \
  [get_cells {spi_inst_shreg_out_reg[18]}]  \
  [get_cells {spi_inst_shreg_out_reg[17]}]  \
  [get_cells {spi_inst_shreg_out_reg[16]}]  \
  [get_cells {spi_inst_shreg_out_reg[15]}]  \
  [get_cells {spi_inst_shreg_out_reg[14]}]  \
  [get_cells {spi_inst_shreg_out_reg[13]}]  \
  [get_cells {spi_inst_shreg_out_reg[12]}]  \
  [get_cells {spi_inst_shreg_out_reg[11]}]  \
  [get_cells {spi_inst_shreg_out_reg[10]}]  \
  [get_cells {spi_inst_shreg_out_reg[9]}]  \
  [get_cells {csm_inst_right_reg_reg[6]}]  \
  [get_cells {csm_inst_right_reg_reg[17]}]  \
  [get_cells {csm_inst_right_reg_reg[5]}]  \
  [get_cells {csm_inst_right_reg_reg[19]}]  \
  [get_cells {csm_inst_right_reg_reg[11]}]  \
  [get_cells {csm_inst_right_reg_reg[22]}]  \
  [get_cells {csm_inst_right_reg_reg[9]}]  \
  [get_cells {csm_inst_right_reg_reg[1]}]  \
  [get_cells {csm_inst_right_reg_reg[16]}]  \
  [get_cells {csm_inst_right_reg_reg[3]}]  \
  [get_cells {csm_inst_right_reg_reg[8]}]  \
  [get_cells {csm_inst_right_reg_reg[31]}]  \
  [get_cells {csm_inst_right_reg_reg[21]}]  \
  [get_cells {csm_inst_right_reg_reg[13]}]  \
  [get_cells {csm_inst_right_reg_reg[10]}]  \
  [get_cells {csm_inst_right_reg_reg[12]}]  \
  [get_cells {csm_inst_right_reg_reg[27]}]  \
  [get_cells {csm_inst_right_reg_reg[15]}]  \
  [get_cells {csm_inst_right_reg_reg[23]}]  \
  [get_cells {csm_inst_right_reg_reg[0]}]  \
  [get_cells {csm_inst_right_reg_reg[14]}]  \
  [get_cells {csm_inst_right_reg_reg[26]}]  \
  [get_cells {csm_inst_right_reg_reg[25]}]  \
  [get_cells {csm_inst_right_reg_reg[29]}]  \
  [get_cells {csm_inst_right_reg_reg[18]}]  \
  [get_cells {csm_inst_right_reg_reg[24]}]  \
  [get_cells {csm_inst_right_reg_reg[4]}]  \
  [get_cells {spi_inst_shreg_out_reg[8]}]  \
  [get_cells {csm_inst_right_reg_reg[7]}]  \
  [get_cells {csm_inst_right_reg_reg[2]}]  \
  [get_cells {csm_inst_right_reg_reg[30]}]  \
  [get_cells {csm_inst_right_reg_reg[20]}]  \
  [get_cells {csm_inst_right_reg_reg[28]}]  \
  [get_cells {spi_inst_shreg_out_reg[7]}]  \
  [get_cells {spi_inst_shreg_out_reg[6]}]  \
  [get_cells {spi_inst_shreg_out_reg[5]}]  \
  [get_cells {spi_inst_shreg_out_reg[4]}]  \
  [get_cells {spi_inst_shreg_out_reg[3]}]  \
  [get_cells start_encrypt_reg]  \
  [get_cells start_decrypt_reg]  \
  [get_cells {key_reg_reg[39]}]  \
  [get_cells {key_reg_reg[18]}]  \
  [get_cells {key_reg_reg[14]}]  \
  [get_cells {key_reg_reg[55]}]  \
  [get_cells {key_reg_reg[5]}]  \
  [get_cells {key_reg_reg[11]}]  \
  [get_cells {key_reg_reg[30]}]  \
  [get_cells {key_reg_reg[62]}]  \
  [get_cells {key_reg_reg[59]}]  \
  [get_cells {key_reg_reg[37]}]  \
  [get_cells {key_reg_reg[45]}]  \
  [get_cells {key_reg_reg[50]}]  \
  [get_cells {key_reg_reg[47]}]  \
  [get_cells {key_reg_reg[57]}]  \
  [get_cells {key_reg_reg[61]}]  \
  [get_cells {key_reg_reg[13]}]  \
  [get_cells {key_reg_reg[33]}]  \
  [get_cells {key_reg_reg[31]}]  \
  [get_cells {key_reg_reg[35]}]  \
  [get_cells {key_reg_reg[54]}]  \
  [get_cells {key_reg_reg[53]}]  \
  [get_cells {key_reg_reg[44]}]  \
  [get_cells {key_reg_reg[51]}]  \
  [get_cells {key_reg_reg[49]}]  \
  [get_cells {key_reg_reg[60]}]  \
  [get_cells {key_reg_reg[2]}]  \
  [get_cells {key_reg_reg[15]}]  \
  [get_cells {key_reg_reg[42]}]  \
  [get_cells {key_reg_reg[10]}]  \
  [get_cells {key_reg_reg[52]}]  \
  [get_cells {key_reg_reg[63]}]  \
  [get_cells {key_reg_reg[25]}]  \
  [get_cells {key_reg_reg[58]}]  \
  [get_cells {key_reg_reg[26]}]  \
  [get_cells {key_reg_reg[3]}]  \
  [get_cells {key_reg_reg[36]}]  \
  [get_cells {key_reg_reg[21]}]  \
  [get_cells {key_reg_reg[23]}]  \
  [get_cells {key_reg_reg[34]}]  \
  [get_cells {key_reg_reg[20]}]  \
  [get_cells {key_reg_reg[1]}]  \
  [get_cells {key_reg_reg[19]}]  \
  [get_cells {key_reg_reg[17]}]  \
  [get_cells {key_reg_reg[6]}]  \
  [get_cells {key_reg_reg[29]}]  \
  [get_cells {key_reg_reg[43]}]  \
  [get_cells {key_reg_reg[4]}]  \
  [get_cells {key_reg_reg[28]}]  \
  [get_cells {key_reg_reg[22]}]  \
  [get_cells {key_reg_reg[12]}]  \
  [get_cells {key_reg_reg[9]}]  \
  [get_cells {key_reg_reg[38]}]  \
  [get_cells {key_reg_reg[46]}]  \
  [get_cells {key_reg_reg[7]}]  \
  [get_cells {key_reg_reg[27]}]  \
  [get_cells {key_reg_reg[41]}]  \
  [get_cells {spi_inst_input_text_reg[24]}]  \
  [get_cells {spi_inst_input_text_reg[8]}]  \
  [get_cells {spi_inst_input_text_reg[40]}]  \
  [get_cells {spi_inst_input_text_reg[56]}]  \
  [get_cells done_decrypt_latched_reg]  \
  [get_cells done_encrypt_latched_reg]  \
  [get_cells {spi_inst_input_text_reg[4]}]  \
  [get_cells {spi_inst_input_text_reg[6]}]  \
  [get_cells {spi_inst_input_text_reg[0]}]  \
  [get_cells {spi_inst_input_text_reg[10]}]  \
  [get_cells {spi_inst_input_text_reg[12]}]  \
  [get_cells {spi_inst_input_text_reg[14]}]  \
  [get_cells {spi_inst_input_text_reg[15]}]  \
  [get_cells {spi_inst_input_text_reg[1]}]  \
  [get_cells {spi_inst_input_text_reg[18]}]  \
  [get_cells {spi_inst_input_text_reg[20]}]  \
  [get_cells {spi_inst_input_text_reg[22]}]  \
  [get_cells {spi_inst_input_text_reg[2]}]  \
  [get_cells {spi_inst_input_text_reg[26]}]  \
  [get_cells {spi_inst_input_text_reg[28]}]  \
  [get_cells {spi_inst_input_text_reg[30]}]  \
  [get_cells {spi_inst_input_text_reg[33]}]  \
  [get_cells {spi_inst_input_text_reg[34]}]  \
  [get_cells {spi_inst_input_text_reg[36]}]  \
  [get_cells {spi_inst_input_text_reg[44]}]  \
  [get_cells {spi_inst_input_text_reg[46]}]  \
  [get_cells {spi_inst_input_text_reg[52]}]  \
  [get_cells {spi_inst_input_text_reg[53]}]  \
  [get_cells {spi_inst_input_text_reg[54]}]  \
  [get_cells {spi_inst_input_text_reg[57]}]  \
  [get_cells {spi_inst_input_text_reg[38]}]  \
  [get_cells {spi_inst_input_text_reg[58]}]  \
  [get_cells {spi_inst_input_text_reg[60]}]  \
  [get_cells {spi_inst_input_text_reg[63]}]  \
  [get_cells {spi_inst_input_text_reg[41]}]  \
  [get_cells {spi_inst_input_text_reg[43]}]  \
  [get_cells {spi_inst_input_text_reg[45]}]  \
  [get_cells {spi_inst_input_text_reg[47]}]  \
  [get_cells {spi_inst_input_text_reg[39]}]  \
  [get_cells {spi_inst_input_text_reg[49]}]  \
  [get_cells {spi_inst_input_text_reg[31]}]  \
  [get_cells {spi_inst_input_text_reg[3]}]  \
  [get_cells {spi_inst_input_text_reg[42]}]  \
  [get_cells {spi_inst_input_text_reg[48]}]  \
  [get_cells {spi_inst_input_text_reg[32]}]  \
  [get_cells {spi_inst_input_text_reg[16]}]  \
  [get_cells {spi_inst_input_text_reg[7]}]  \
  [get_cells {spi_inst_input_text_reg[37]}]  \
  [get_cells {spi_inst_input_text_reg[5]}]  \
  [get_cells {spi_inst_input_text_reg[35]}]  \
  [get_cells {spi_inst_input_text_reg[23]}]  \
  [get_cells {spi_inst_input_text_reg[17]}]  \
  [get_cells {spi_inst_input_text_reg[55]}]  \
  [get_cells {spi_inst_input_text_reg[61]}]  \
  [get_cells {spi_inst_input_text_reg[25]}]  \
  [get_cells {spi_inst_input_text_reg[19]}]  \
  [get_cells {spi_inst_input_text_reg[21]}]  \
  [get_cells {spi_inst_input_text_reg[59]}]  \
  [get_cells crypt_reg]  \
  [get_cells {spi_inst_input_text_reg[9]}]  \
  [get_cells {spi_inst_input_text_reg[13]}]  \
  [get_cells {spi_inst_input_text_reg[50]}]  \
  [get_cells {spi_inst_input_text_reg[51]}]  \
  [get_cells {spi_inst_input_text_reg[62]}]  \
  [get_cells {spi_inst_input_text_reg[11]}]  \
  [get_cells {spi_inst_input_text_reg[27]}]  \
  [get_cells {spi_inst_input_text_reg[29]}]  \
  [get_cells {transaction_state_reg[1]}]  \
  [get_cells {transaction_state_reg[0]}]  \
  [get_cells {data_reg_reg[46]}]  \
  [get_cells {data_reg_reg[47]}]  \
  [get_cells {data_reg_reg[49]}]  \
  [get_cells {data_reg_reg[51]}]  \
  [get_cells {data_reg_reg[53]}]  \
  [get_cells {data_reg_reg[55]}]  \
  [get_cells {data_reg_reg[57]}]  \
  [get_cells {data_reg_reg[59]}]  \
  [get_cells {data_reg_reg[61]}]  \
  [get_cells {data_reg_reg[8]}]  \
  [get_cells {data_reg_reg[16]}]  \
  [get_cells {spi_inst_bit_cnt_reg[6]}]  \
  [get_cells {data_reg_reg[4]}]  \
  [get_cells {data_reg_reg[0]}]  \
  [get_cells {data_reg_reg[58]}]  \
  [get_cells {data_reg_reg[62]}]  \
  [get_cells {data_reg_reg[63]}]  \
  [get_cells {data_reg_reg[10]}]  \
  [get_cells {data_reg_reg[20]}]  \
  [get_cells {data_reg_reg[22]}]  \
  [get_cells {data_reg_reg[24]}]  \
  [get_cells {data_reg_reg[18]}]  \
  [get_cells {data_reg_reg[2]}]  \
  [get_cells {data_reg_reg[6]}]  \
  [get_cells {data_reg_reg[12]}]  \
  [get_cells {data_reg_reg[1]}]  \
  [get_cells {data_reg_reg[3]}]  \
  [get_cells {data_reg_reg[60]}]  \
  [get_cells {data_reg_reg[5]}]  \
  [get_cells {data_reg_reg[7]}]  \
  [get_cells {data_reg_reg[9]}]  \
  [get_cells {data_reg_reg[11]}]  \
  [get_cells {data_reg_reg[13]}]  \
  [get_cells {data_reg_reg[14]}]  \
  [get_cells {data_reg_reg[15]}]  \
  [get_cells {data_reg_reg[56]}]  \
  [get_cells {data_reg_reg[17]}]  \
  [get_cells {data_reg_reg[19]}]  \
  [get_cells {data_reg_reg[21]}]  \
  [get_cells {data_reg_reg[23]}]  \
  [get_cells {data_reg_reg[25]}]  \
  [get_cells {data_reg_reg[27]}]  \
  [get_cells {data_reg_reg[29]}]  \
  [get_cells {data_reg_reg[31]}]  \
  [get_cells {data_reg_reg[33]}]  \
  [get_cells {data_reg_reg[35]}]  \
  [get_cells {data_reg_reg[54]}]  \
  [get_cells {data_reg_reg[37]}]  \
  [get_cells {data_reg_reg[39]}]  \
  [get_cells {data_reg_reg[41]}]  \
  [get_cells {data_reg_reg[43]}]  \
  [get_cells {data_reg_reg[45]}]  \
  [get_cells {data_reg_reg[52]}]  \
  [get_cells {data_reg_reg[30]}]  \
  [get_cells {data_reg_reg[32]}]  \
  [get_cells {data_reg_reg[34]}]  \
  [get_cells {data_reg_reg[36]}]  \
  [get_cells {data_reg_reg[28]}]  \
  [get_cells {data_reg_reg[38]}]  \
  [get_cells {data_reg_reg[40]}]  \
  [get_cells {data_reg_reg[42]}]  \
  [get_cells {data_reg_reg[44]}]  \
  [get_cells {data_reg_reg[26]}]  \
  [get_cells {data_reg_reg[48]}]  \
  [get_cells {data_reg_reg[50]}]  \
  [get_cells {spi_inst_shreg_out_reg[2]}]  \
  [get_cells trigger_operation_reg]  \
  [get_cells {spi_inst_bit_cnt_reg[5]}]  \
  [get_cells {csm_inst_round_counter_reg[3]}]  \
  [get_cells {csm_inst_left_reg_reg[11]}]  \
  [get_cells {csm_inst_left_reg_reg[17]}]  \
  [get_cells {csm_inst_left_reg_reg[5]}]  \
  [get_cells {csm_inst_left_reg_reg[30]}]  \
  [get_cells {csm_inst_left_reg_reg[27]}]  \
  [get_cells {csm_inst_left_reg_reg[4]}]  \
  [get_cells {csm_inst_left_reg_reg[3]}]  \
  [get_cells {csm_inst_left_reg_reg[13]}]  \
  [get_cells {csm_inst_left_reg_reg[31]}]  \
  [get_cells {csm_inst_left_reg_reg[6]}]  \
  [get_cells {csm_inst_left_reg_reg[8]}]  \
  [get_cells {csm_inst_left_reg_reg[9]}]  \
  [get_cells {csm_inst_left_reg_reg[1]}]  \
  [get_cells {csm_inst_left_reg_reg[22]}]  \
  [get_cells {csm_inst_left_reg_reg[19]}]  \
  [get_cells {csm_inst_left_reg_reg[16]}]  \
  [get_cells {csm_inst_left_reg_reg[20]}]  \
  [get_cells {csm_inst_left_reg_reg[21]}]  \
  [get_cells {csm_inst_left_reg_reg[7]}]  \
  [get_cells {csm_inst_left_reg_reg[24]}]  \
  [get_cells {csm_inst_left_reg_reg[26]}]  \
  [get_cells {csm_inst_left_reg_reg[28]}]  \
  [get_cells {csm_inst_left_reg_reg[15]}]  \
  [get_cells {csm_inst_left_reg_reg[25]}]  \
  [get_cells {csm_inst_left_reg_reg[29]}]  \
  [get_cells {csm_inst_left_reg_reg[10]}]  \
  [get_cells {csm_inst_left_reg_reg[18]}]  \
  [get_cells {csm_inst_left_reg_reg[12]}]  \
  [get_cells {csm_inst_left_reg_reg[2]}]  \
  [get_cells {csm_inst_left_reg_reg[0]}]  \
  [get_cells {csm_inst_left_reg_reg[23]}]  \
  [get_cells {csm_inst_left_reg_reg[14]}]  \
  [get_cells {spi_inst_shreg_out_reg[1]}]  \
  [get_cells {spi_inst_bit_cnt_reg[4]}]  \
  [get_cells {csm_inst_round_counter_reg[2]}]  \
  [get_cells csm_inst_mode_reg]  \
  [get_cells {csm_inst_round_counter_reg[1]}]  \
  [get_cells {csm_inst_state_reg[0]}]  \
  [get_cells csm_inst_done_encrypt_reg]  \
  [get_cells csm_inst_done_decrypt_reg]  \
  [get_cells {csm_inst_round_counter_reg[0]}]  \
  [get_cells {csm_inst_output_text_reg[3]}]  \
  [get_cells {csm_inst_output_text_reg[55]}]  \
  [get_cells {csm_inst_output_text_reg[4]}]  \
  [get_cells {csm_inst_output_text_reg[50]}]  \
  [get_cells {csm_inst_output_text_reg[51]}]  \
  [get_cells {csm_inst_output_text_reg[2]}]  \
  [get_cells {csm_inst_output_text_reg[0]}]  \
  [get_cells {csm_inst_output_text_reg[40]}]  \
  [get_cells {csm_inst_output_text_reg[48]}]  \
  [get_cells {csm_inst_output_text_reg[5]}]  \
  [get_cells {csm_inst_output_text_reg[18]}]  \
  [get_cells {spi_inst_bit_cnt_reg[3]}]  \
  [get_cells {csm_inst_output_text_reg[49]}]  \
  [get_cells {csm_inst_output_text_reg[13]}]  \
  [get_cells {csm_inst_output_text_reg[33]}]  \
  [get_cells {csm_inst_output_text_reg[47]}]  \
  [get_cells {csm_inst_output_text_reg[56]}]  \
  [get_cells {csm_inst_output_text_reg[10]}]  \
  [get_cells {csm_inst_output_text_reg[41]}]  \
  [get_cells {csm_inst_output_text_reg[54]}]  \
  [get_cells {csm_inst_output_text_reg[20]}]  \
  [get_cells {csm_inst_output_text_reg[59]}]  \
  [get_cells {csm_inst_output_text_reg[25]}]  \
  [get_cells {csm_inst_output_text_reg[32]}]  \
  [get_cells {csm_inst_output_text_reg[6]}]  \
  [get_cells {csm_inst_output_text_reg[44]}]  \
  [get_cells {csm_inst_output_text_reg[8]}]  \
  [get_cells {csm_inst_output_text_reg[45]}]  \
  [get_cells {csm_inst_output_text_reg[36]}]  \
  [get_cells {csm_inst_output_text_reg[62]}]  \
  [get_cells {csm_inst_output_text_reg[16]}]  \
  [get_cells {csm_inst_output_text_reg[58]}]  \
  [get_cells {csm_inst_output_text_reg[17]}]  \
  [get_cells {csm_inst_output_text_reg[61]}]  \
  [get_cells {csm_inst_output_text_reg[63]}]  \
  [get_cells {csm_inst_output_text_reg[57]}]  \
  [get_cells {csm_inst_output_text_reg[1]}]  \
  [get_cells {csm_inst_output_text_reg[14]}]  \
  [get_cells {csm_inst_output_text_reg[11]}]  \
  [get_cells {csm_inst_output_text_reg[15]}]  \
  [get_cells {csm_inst_output_text_reg[53]}]  \
  [get_cells {csm_inst_output_text_reg[21]}]  \
  [get_cells cs_rise_delayed_reg]  \
  [get_cells {csm_inst_output_text_reg[7]}]  \
  [get_cells {csm_inst_output_text_reg[34]}]  \
  [get_cells {csm_inst_output_text_reg[42]}]  \
  [get_cells {csm_inst_output_text_reg[35]}]  \
  [get_cells {csm_inst_state_reg[2]}]  \
  [get_cells {csm_inst_output_text_reg[30]}]  \
  [get_cells {csm_inst_output_text_reg[29]}]  \
  [get_cells {csm_inst_output_text_reg[26]}]  \
  [get_cells {csm_inst_output_text_reg[31]}]  \
  [get_cells {csm_inst_output_text_reg[28]}]  \
  [get_cells {csm_inst_output_text_reg[9]}]  \
  [get_cells {csm_inst_output_text_reg[43]}]  \
  [get_cells {csm_inst_output_text_reg[27]}]  \
  [get_cells {csm_inst_output_text_reg[24]}]  \
  [get_cells {csm_inst_output_text_reg[60]}]  \
  [get_cells {csm_inst_output_text_reg[52]}]  \
  [get_cells {csm_inst_output_text_reg[23]}]  \
  [get_cells {csm_inst_output_text_reg[46]}]  \
  [get_cells {csm_inst_output_text_reg[39]}]  \
  [get_cells {csm_inst_output_text_reg[19]}]  \
  [get_cells {csm_inst_output_text_reg[37]}]  \
  [get_cells {csm_inst_output_text_reg[38]}]  \
  [get_cells {csm_inst_output_text_reg[12]}]  \
  [get_cells {csm_inst_output_text_reg[22]}]  \
  [get_cells {spi_tx_data_reg[41]}]  \
  [get_cells {spi_tx_data_reg[0]}]  \
  [get_cells {spi_tx_data_reg[42]}]  \
  [get_cells {spi_tx_data_reg[60]}]  \
  [get_cells {spi_tx_data_reg[23]}]  \
  [get_cells {spi_tx_data_reg[56]}]  \
  [get_cells {spi_tx_data_reg[50]}]  \
  [get_cells {spi_tx_data_reg[45]}]  \
  [get_cells {spi_tx_data_reg[37]}]  \
  [get_cells {spi_tx_data_reg[33]}]  \
  [get_cells {spi_tx_data_reg[26]}]  \
  [get_cells {spi_tx_data_reg[16]}]  \
  [get_cells {spi_tx_data_reg[13]}]  \
  [get_cells {spi_tx_data_reg[2]}]  \
  [get_cells {spi_tx_data_reg[32]}]  \
  [get_cells {spi_tx_data_reg[48]}]  \
  [get_cells {spi_tx_data_reg[39]}]  \
  [get_cells {spi_tx_data_reg[12]}]  \
  [get_cells {spi_tx_data_reg[7]}]  \
  [get_cells {spi_tx_data_reg[63]}]  \
  [get_cells {spi_tx_data_reg[11]}]  \
  [get_cells {spi_tx_data_reg[5]}]  \
  [get_cells {spi_tx_data_reg[8]}]  \
  [get_cells {spi_tx_data_reg[9]}]  \
  [get_cells {spi_tx_data_reg[27]}]  \
  [get_cells {spi_tx_data_reg[14]}]  \
  [get_cells {spi_tx_data_reg[15]}]  \
  [get_cells {spi_tx_data_reg[17]}]  \
  [get_cells {spi_tx_data_reg[18]}]  \
  [get_cells {spi_tx_data_reg[19]}]  \
  [get_cells {spi_tx_data_reg[21]}]  \
  [get_cells {spi_tx_data_reg[22]}]  \
  [get_cells {spi_tx_data_reg[24]}]  \
  [get_cells {spi_tx_data_reg[25]}]  \
  [get_cells {spi_tx_data_reg[58]}]  \
  [get_cells {spi_tx_data_reg[30]}]  \
  [get_cells {spi_tx_data_reg[31]}]  \
  [get_cells {spi_tx_data_reg[34]}]  \
  [get_cells {spi_tx_data_reg[35]}]  \
  [get_cells {spi_tx_data_reg[36]}]  \
  [get_cells {spi_tx_data_reg[40]}]  \
  [get_cells {spi_tx_data_reg[43]}]  \
  [get_cells {spi_tx_data_reg[46]}]  \
  [get_cells {spi_tx_data_reg[47]}]  \
  [get_cells {spi_tx_data_reg[49]}]  \
  [get_cells {spi_tx_data_reg[51]}]  \
  [get_cells {spi_tx_data_reg[53]}]  \
  [get_cells {spi_tx_data_reg[54]}]  \
  [get_cells {spi_tx_data_reg[57]}]  \
  [get_cells {spi_tx_data_reg[59]}]  \
  [get_cells {spi_tx_data_reg[62]}]  \
  [get_cells {spi_tx_data_reg[55]}]  \
  [get_cells {spi_tx_data_reg[29]}]  \
  [get_cells {spi_tx_data_reg[61]}]  \
  [get_cells {spi_tx_data_reg[52]}]  \
  [get_cells {spi_tx_data_reg[38]}]  \
  [get_cells {spi_tx_data_reg[20]}]  \
  [get_cells {spi_tx_data_reg[44]}]  \
  [get_cells {spi_tx_data_reg[28]}]  \
  [get_cells {spi_tx_data_reg[6]}]  \
  [get_cells {spi_tx_data_reg[3]}]  \
  [get_cells {spi_tx_data_reg[4]}]  \
  [get_cells {spi_tx_data_reg[10]}]  \
  [get_cells {spi_tx_data_reg[1]}]  \
  [get_cells {spi_inst_bit_cnt_reg[1]}]  \
  [get_cells {spi_inst_bit_cnt_reg[2]}]  \
  [get_cells cs_prev_reg]  \
  [get_cells active_reg]  \
  [get_cells {csm_inst_state_reg[1]}]  \
  [get_cells {spi_inst_shreg_in_reg[62]}]  \
  [get_cells cs_sync_reg]  \
  [get_cells {spi_inst_shreg_in_reg[34]}]  \
  [get_cells {spi_inst_shreg_in_reg[26]}]  \
  [get_cells {spi_inst_shreg_in_reg[30]}]  \
  [get_cells {spi_inst_shreg_in_reg[51]}]  \
  [get_cells {spi_inst_shreg_in_reg[0]}]  \
  [get_cells {spi_inst_shreg_in_reg[13]}]  \
  [get_cells {spi_inst_shreg_in_reg[18]}]  \
  [get_cells {spi_inst_shreg_in_reg[61]}]  \
  [get_cells {spi_inst_shreg_in_reg[9]}]  \
  [get_cells {spi_inst_shreg_in_reg[10]}]  \
  [get_cells {spi_inst_shreg_in_reg[16]}]  \
  [get_cells {spi_inst_shreg_in_reg[4]}]  \
  [get_cells {spi_inst_shreg_in_reg[57]}]  \
  [get_cells {spi_inst_shreg_in_reg[60]}]  \
  [get_cells {spi_inst_shreg_in_reg[48]}]  \
  [get_cells {spi_inst_shreg_in_reg[27]}]  \
  [get_cells {spi_inst_shreg_in_reg[58]}]  \
  [get_cells {spi_inst_shreg_in_reg[22]}]  \
  [get_cells {spi_inst_shreg_in_reg[45]}]  \
  [get_cells {spi_inst_shreg_in_reg[53]}]  \
  [get_cells {spi_inst_shreg_in_reg[1]}]  \
  [get_cells {spi_inst_shreg_in_reg[8]}]  \
  [get_cells {spi_inst_shreg_in_reg[56]}]  \
  [get_cells {spi_inst_shreg_in_reg[17]}]  \
  [get_cells {spi_inst_shreg_in_reg[21]}]  \
  [get_cells {spi_inst_shreg_in_reg[5]}]  \
  [get_cells {spi_inst_shreg_in_reg[55]}]  \
  [get_cells {spi_inst_shreg_in_reg[50]}]  \
  [get_cells {spi_inst_shreg_in_reg[54]}]  \
  [get_cells {spi_inst_shreg_in_reg[20]}]  \
  [get_cells {spi_inst_shreg_in_reg[29]}]  \
  [get_cells {spi_inst_shreg_in_reg[52]}]  \
  [get_cells {spi_inst_shreg_in_reg[40]}]  \
  [get_cells {spi_inst_shreg_in_reg[31]}]  \
  [get_cells {spi_inst_shreg_in_reg[14]}]  \
  [get_cells {spi_inst_shreg_in_reg[25]}]  \
  [get_cells {spi_inst_shreg_in_reg[46]}]  \
  [get_cells {spi_inst_shreg_in_reg[33]}]  \
  [get_cells {spi_inst_shreg_in_reg[7]}]  \
  [get_cells {spi_inst_shreg_in_reg[19]}]  \
  [get_cells {spi_inst_shreg_in_reg[37]}]  \
  [get_cells {spi_inst_shreg_in_reg[42]}]  \
  [get_cells {spi_inst_shreg_in_reg[28]}]  \
  [get_cells {spi_inst_shreg_in_reg[44]}]  \
  [get_cells {spi_inst_shreg_in_reg[24]}]  \
  [get_cells {spi_inst_shreg_in_reg[2]}]  \
  [get_cells {spi_inst_shreg_in_reg[35]}]  \
  [get_cells {spi_inst_shreg_in_reg[41]}]  \
  [get_cells {spi_inst_shreg_in_reg[47]}]  \
  [get_cells {spi_inst_shreg_in_reg[43]}]  \
  [get_cells {spi_inst_shreg_in_reg[3]}]  \
  [get_cells {spi_inst_shreg_in_reg[59]}]  \
  [get_cells {spi_inst_shreg_in_reg[23]}]  \
  [get_cells {spi_inst_shreg_in_reg[6]}]  \
  [get_cells {spi_inst_shreg_in_reg[32]}]  \
  [get_cells {spi_inst_shreg_in_reg[15]}]  \
  [get_cells {spi_inst_shreg_in_reg[11]}]  \
  [get_cells {spi_inst_shreg_in_reg[38]}]  \
  [get_cells {spi_inst_shreg_in_reg[36]}]  \
  [get_cells {spi_inst_shreg_in_reg[49]}]  \
  [get_cells {spi_inst_shreg_in_reg[12]}]  \
  [get_cells {spi_inst_shreg_in_reg[39]}]  \
  [get_cells cs_meta_reg]  \
  [get_cells {spi_inst_bit_cnt_reg[0]}] ]
group_path -weight 1.000000 -name I2O -from [list \
  [get_ports clk]  \
  [get_ports rst]  \
  [get_ports sclk]  \
  [get_ports cs_n]  \
  [get_ports mosi] ] -to [get_ports miso]
set_clock_gating_check -setup 0.0 
