
//input ports
add mapped point clk clk -type PI PI
add mapped point rst rst -type PI PI
add mapped point sclk sclk -type PI PI
add mapped point cs_n cs_n -type PI PI
add mapped point mosi mosi -type PI PI

//output ports
add mapped point miso miso -type PO PO

//inout ports




//Sequential Pins
add mapped point spi_inst/miso_q/q spi_inst_miso_q_reg/Q -type DFF DFF
add mapped point spi_inst/shreg_out[63]/q spi_inst_shreg_out_reg[63]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[62]/q spi_inst_shreg_out_reg[62]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[61]/q spi_inst_shreg_out_reg[61]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[60]/q spi_inst_shreg_out_reg[60]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[59]/q spi_inst_shreg_out_reg[59]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[58]/q spi_inst_shreg_out_reg[58]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[57]/q spi_inst_shreg_out_reg[57]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[56]/q spi_inst_shreg_out_reg[56]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[55]/q spi_inst_shreg_out_reg[55]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[54]/q spi_inst_shreg_out_reg[54]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[53]/q spi_inst_shreg_out_reg[53]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[52]/q spi_inst_shreg_out_reg[52]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[51]/q spi_inst_shreg_out_reg[51]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[50]/q spi_inst_shreg_out_reg[50]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[49]/q spi_inst_shreg_out_reg[49]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[48]/q spi_inst_shreg_out_reg[48]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[47]/q spi_inst_shreg_out_reg[47]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[46]/q spi_inst_shreg_out_reg[46]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[45]/q spi_inst_shreg_out_reg[45]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[44]/q spi_inst_shreg_out_reg[44]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[43]/q spi_inst_shreg_out_reg[43]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[42]/q spi_inst_shreg_out_reg[42]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[41]/q spi_inst_shreg_out_reg[41]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[40]/q spi_inst_shreg_out_reg[40]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[39]/q spi_inst_shreg_out_reg[39]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[38]/q spi_inst_shreg_out_reg[38]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[37]/q spi_inst_shreg_out_reg[37]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[36]/q spi_inst_shreg_out_reg[36]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[35]/q spi_inst_shreg_out_reg[35]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[34]/q spi_inst_shreg_out_reg[34]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[33]/q spi_inst_shreg_out_reg[33]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[32]/q spi_inst_shreg_out_reg[32]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[31]/q spi_inst_shreg_out_reg[31]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[30]/q spi_inst_shreg_out_reg[30]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[29]/q spi_inst_shreg_out_reg[29]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[28]/q spi_inst_shreg_out_reg[28]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[27]/q spi_inst_shreg_out_reg[27]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[26]/q spi_inst_shreg_out_reg[26]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[25]/q spi_inst_shreg_out_reg[25]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[24]/q spi_inst_shreg_out_reg[24]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[23]/q spi_inst_shreg_out_reg[23]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[22]/q spi_inst_shreg_out_reg[22]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[21]/q spi_inst_shreg_out_reg[21]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[20]/q spi_inst_shreg_out_reg[20]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[19]/q spi_inst_shreg_out_reg[19]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[18]/q spi_inst_shreg_out_reg[18]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[17]/q spi_inst_shreg_out_reg[17]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[16]/q spi_inst_shreg_out_reg[16]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[15]/q spi_inst_shreg_out_reg[15]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[14]/q spi_inst_shreg_out_reg[14]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[13]/q spi_inst_shreg_out_reg[13]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[12]/q spi_inst_shreg_out_reg[12]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[11]/q spi_inst_shreg_out_reg[11]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[10]/q spi_inst_shreg_out_reg[10]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[9]/q spi_inst_shreg_out_reg[9]/Q -type DFF DFF
add mapped point csm_inst/right_reg[6]/q csm_inst_right_reg_reg[6]/Q -type DFF DFF
add mapped point csm_inst/right_reg[17]/q csm_inst_right_reg_reg[17]/Q -type DFF DFF
add mapped point csm_inst/right_reg[5]/q csm_inst_right_reg_reg[5]/Q -type DFF DFF
add mapped point csm_inst/right_reg[19]/q csm_inst_right_reg_reg[19]/Q -type DFF DFF
add mapped point csm_inst/right_reg[11]/q csm_inst_right_reg_reg[11]/Q -type DFF DFF
add mapped point csm_inst/right_reg[22]/q csm_inst_right_reg_reg[22]/Q -type DFF DFF
add mapped point csm_inst/right_reg[9]/q csm_inst_right_reg_reg[9]/Q -type DFF DFF
add mapped point csm_inst/right_reg[1]/q csm_inst_right_reg_reg[1]/Q -type DFF DFF
add mapped point csm_inst/right_reg[16]/q csm_inst_right_reg_reg[16]/Q -type DFF DFF
add mapped point csm_inst/right_reg[3]/q csm_inst_right_reg_reg[3]/Q -type DFF DFF
add mapped point csm_inst/right_reg[8]/q csm_inst_right_reg_reg[8]/Q -type DFF DFF
add mapped point csm_inst/right_reg[31]/q csm_inst_right_reg_reg[31]/Q -type DFF DFF
add mapped point csm_inst/right_reg[21]/q csm_inst_right_reg_reg[21]/Q -type DFF DFF
add mapped point csm_inst/right_reg[13]/q csm_inst_right_reg_reg[13]/Q -type DFF DFF
add mapped point csm_inst/right_reg[10]/q csm_inst_right_reg_reg[10]/Q -type DFF DFF
add mapped point csm_inst/right_reg[12]/q csm_inst_right_reg_reg[12]/Q -type DFF DFF
add mapped point csm_inst/right_reg[27]/q csm_inst_right_reg_reg[27]/Q -type DFF DFF
add mapped point csm_inst/right_reg[15]/q csm_inst_right_reg_reg[15]/Q -type DFF DFF
add mapped point csm_inst/right_reg[23]/q csm_inst_right_reg_reg[23]/Q -type DFF DFF
add mapped point csm_inst/right_reg[0]/q csm_inst_right_reg_reg[0]/Q -type DFF DFF
add mapped point csm_inst/right_reg[14]/q csm_inst_right_reg_reg[14]/Q -type DFF DFF
add mapped point csm_inst/right_reg[26]/q csm_inst_right_reg_reg[26]/Q -type DFF DFF
add mapped point csm_inst/right_reg[25]/q csm_inst_right_reg_reg[25]/Q -type DFF DFF
add mapped point csm_inst/right_reg[29]/q csm_inst_right_reg_reg[29]/Q -type DFF DFF
add mapped point csm_inst/right_reg[18]/q csm_inst_right_reg_reg[18]/Q -type DFF DFF
add mapped point csm_inst/right_reg[24]/q csm_inst_right_reg_reg[24]/Q -type DFF DFF
add mapped point csm_inst/right_reg[4]/q csm_inst_right_reg_reg[4]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[8]/q spi_inst_shreg_out_reg[8]/Q -type DFF DFF
add mapped point csm_inst/right_reg[7]/q csm_inst_right_reg_reg[7]/Q -type DFF DFF
add mapped point csm_inst/right_reg[2]/q csm_inst_right_reg_reg[2]/Q -type DFF DFF
add mapped point csm_inst/right_reg[30]/q csm_inst_right_reg_reg[30]/Q -type DFF DFF
add mapped point csm_inst/right_reg[20]/q csm_inst_right_reg_reg[20]/Q -type DFF DFF
add mapped point csm_inst/right_reg[28]/q csm_inst_right_reg_reg[28]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[7]/q spi_inst_shreg_out_reg[7]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[6]/q spi_inst_shreg_out_reg[6]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[5]/q spi_inst_shreg_out_reg[5]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[4]/q spi_inst_shreg_out_reg[4]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[3]/q spi_inst_shreg_out_reg[3]/Q -type DFF DFF
add mapped point start_encrypt/q start_encrypt_reg/Q -type DFF DFF
add mapped point start_decrypt/q start_decrypt_reg/Q -type DFF DFF
add mapped point key_reg[39]/q key_reg_reg[39]/Q -type DFF DFF
add mapped point key_reg[18]/q key_reg_reg[18]/Q -type DFF DFF
add mapped point key_reg[14]/q key_reg_reg[14]/Q -type DFF DFF
add mapped point key_reg[55]/q key_reg_reg[55]/Q -type DFF DFF
add mapped point key_reg[5]/q key_reg_reg[5]/Q -type DFF DFF
add mapped point key_reg[11]/q key_reg_reg[11]/Q -type DFF DFF
add mapped point key_reg[30]/q key_reg_reg[30]/Q -type DFF DFF
add mapped point key_reg[62]/q key_reg_reg[62]/Q -type DFF DFF
add mapped point key_reg[59]/q key_reg_reg[59]/Q -type DFF DFF
add mapped point key_reg[37]/q key_reg_reg[37]/Q -type DFF DFF
add mapped point key_reg[45]/q key_reg_reg[45]/Q -type DFF DFF
add mapped point key_reg[50]/q key_reg_reg[50]/Q -type DFF DFF
add mapped point key_reg[47]/q key_reg_reg[47]/Q -type DFF DFF
add mapped point key_reg[57]/q key_reg_reg[57]/Q -type DFF DFF
add mapped point key_reg[61]/q key_reg_reg[61]/Q -type DFF DFF
add mapped point key_reg[13]/q key_reg_reg[13]/Q -type DFF DFF
add mapped point key_reg[33]/q key_reg_reg[33]/Q -type DFF DFF
add mapped point key_reg[31]/q key_reg_reg[31]/Q -type DFF DFF
add mapped point key_reg[35]/q key_reg_reg[35]/Q -type DFF DFF
add mapped point key_reg[54]/q key_reg_reg[54]/Q -type DFF DFF
add mapped point key_reg[53]/q key_reg_reg[53]/Q -type DFF DFF
add mapped point key_reg[44]/q key_reg_reg[44]/Q -type DFF DFF
add mapped point key_reg[51]/q key_reg_reg[51]/Q -type DFF DFF
add mapped point key_reg[49]/q key_reg_reg[49]/Q -type DFF DFF
add mapped point key_reg[60]/q key_reg_reg[60]/Q -type DFF DFF
add mapped point key_reg[2]/q key_reg_reg[2]/Q -type DFF DFF
add mapped point key_reg[15]/q key_reg_reg[15]/Q -type DFF DFF
add mapped point key_reg[42]/q key_reg_reg[42]/Q -type DFF DFF
add mapped point key_reg[10]/q key_reg_reg[10]/Q -type DFF DFF
add mapped point key_reg[52]/q key_reg_reg[52]/Q -type DFF DFF
add mapped point key_reg[63]/q key_reg_reg[63]/Q -type DFF DFF
add mapped point key_reg[25]/q key_reg_reg[25]/Q -type DFF DFF
add mapped point key_reg[58]/q key_reg_reg[58]/Q -type DFF DFF
add mapped point key_reg[26]/q key_reg_reg[26]/Q -type DFF DFF
add mapped point key_reg[3]/q key_reg_reg[3]/Q -type DFF DFF
add mapped point key_reg[36]/q key_reg_reg[36]/Q -type DFF DFF
add mapped point key_reg[21]/q key_reg_reg[21]/Q -type DFF DFF
add mapped point key_reg[23]/q key_reg_reg[23]/Q -type DFF DFF
add mapped point key_reg[34]/q key_reg_reg[34]/Q -type DFF DFF
add mapped point key_reg[20]/q key_reg_reg[20]/Q -type DFF DFF
add mapped point key_reg[1]/q key_reg_reg[1]/Q -type DFF DFF
add mapped point key_reg[19]/q key_reg_reg[19]/Q -type DFF DFF
add mapped point key_reg[17]/q key_reg_reg[17]/Q -type DFF DFF
add mapped point key_reg[6]/q key_reg_reg[6]/Q -type DFF DFF
add mapped point key_reg[29]/q key_reg_reg[29]/Q -type DFF DFF
add mapped point key_reg[43]/q key_reg_reg[43]/Q -type DFF DFF
add mapped point key_reg[4]/q key_reg_reg[4]/Q -type DFF DFF
add mapped point key_reg[28]/q key_reg_reg[28]/Q -type DFF DFF
add mapped point key_reg[22]/q key_reg_reg[22]/Q -type DFF DFF
add mapped point key_reg[12]/q key_reg_reg[12]/Q -type DFF DFF
add mapped point key_reg[9]/q key_reg_reg[9]/Q -type DFF DFF
add mapped point key_reg[38]/q key_reg_reg[38]/Q -type DFF DFF
add mapped point key_reg[46]/q key_reg_reg[46]/Q -type DFF DFF
add mapped point key_reg[7]/q key_reg_reg[7]/Q -type DFF DFF
add mapped point key_reg[27]/q key_reg_reg[27]/Q -type DFF DFF
add mapped point key_reg[41]/q key_reg_reg[41]/Q -type DFF DFF
add mapped point spi_inst/input_text[24]/q spi_inst_input_text_reg[24]/Q -type DFF DFF
add mapped point spi_inst/input_text[8]/q spi_inst_input_text_reg[8]/Q -type DFF DFF
add mapped point spi_inst/input_text[40]/q spi_inst_input_text_reg[40]/Q -type DFF DFF
add mapped point spi_inst/input_text[56]/q spi_inst_input_text_reg[56]/Q -type DFF DFF
add mapped point done_decrypt_latched/q done_decrypt_latched_reg/Q -type DFF DFF
add mapped point done_encrypt_latched/q done_encrypt_latched_reg/Q -type DFF DFF
add mapped point spi_inst/input_text[4]/q spi_inst_input_text_reg[4]/Q -type DFF DFF
add mapped point spi_inst/input_text[6]/q spi_inst_input_text_reg[6]/Q -type DFF DFF
add mapped point spi_inst/input_text[0]/q spi_inst_input_text_reg[0]/Q -type DFF DFF
add mapped point spi_inst/input_text[10]/q spi_inst_input_text_reg[10]/Q -type DFF DFF
add mapped point spi_inst/input_text[12]/q spi_inst_input_text_reg[12]/Q -type DFF DFF
add mapped point spi_inst/input_text[14]/q spi_inst_input_text_reg[14]/Q -type DFF DFF
add mapped point spi_inst/input_text[15]/q spi_inst_input_text_reg[15]/Q -type DFF DFF
add mapped point spi_inst/input_text[1]/q spi_inst_input_text_reg[1]/Q -type DFF DFF
add mapped point spi_inst/input_text[18]/q spi_inst_input_text_reg[18]/Q -type DFF DFF
add mapped point spi_inst/input_text[20]/q spi_inst_input_text_reg[20]/Q -type DFF DFF
add mapped point spi_inst/input_text[22]/q spi_inst_input_text_reg[22]/Q -type DFF DFF
add mapped point spi_inst/input_text[2]/q spi_inst_input_text_reg[2]/Q -type DFF DFF
add mapped point spi_inst/input_text[26]/q spi_inst_input_text_reg[26]/Q -type DFF DFF
add mapped point spi_inst/input_text[28]/q spi_inst_input_text_reg[28]/Q -type DFF DFF
add mapped point spi_inst/input_text[30]/q spi_inst_input_text_reg[30]/Q -type DFF DFF
add mapped point spi_inst/input_text[33]/q spi_inst_input_text_reg[33]/Q -type DFF DFF
add mapped point spi_inst/input_text[34]/q spi_inst_input_text_reg[34]/Q -type DFF DFF
add mapped point spi_inst/input_text[36]/q spi_inst_input_text_reg[36]/Q -type DFF DFF
add mapped point spi_inst/input_text[44]/q spi_inst_input_text_reg[44]/Q -type DFF DFF
add mapped point spi_inst/input_text[46]/q spi_inst_input_text_reg[46]/Q -type DFF DFF
add mapped point spi_inst/input_text[52]/q spi_inst_input_text_reg[52]/Q -type DFF DFF
add mapped point spi_inst/input_text[53]/q spi_inst_input_text_reg[53]/Q -type DFF DFF
add mapped point spi_inst/input_text[54]/q spi_inst_input_text_reg[54]/Q -type DFF DFF
add mapped point spi_inst/input_text[57]/q spi_inst_input_text_reg[57]/Q -type DFF DFF
add mapped point spi_inst/input_text[38]/q spi_inst_input_text_reg[38]/Q -type DFF DFF
add mapped point spi_inst/input_text[58]/q spi_inst_input_text_reg[58]/Q -type DFF DFF
add mapped point spi_inst/input_text[60]/q spi_inst_input_text_reg[60]/Q -type DFF DFF
add mapped point spi_inst/input_text[63]/q spi_inst_input_text_reg[63]/Q -type DFF DFF
add mapped point spi_inst/input_text[41]/q spi_inst_input_text_reg[41]/Q -type DFF DFF
add mapped point spi_inst/input_text[43]/q spi_inst_input_text_reg[43]/Q -type DFF DFF
add mapped point spi_inst/input_text[45]/q spi_inst_input_text_reg[45]/Q -type DFF DFF
add mapped point spi_inst/input_text[47]/q spi_inst_input_text_reg[47]/Q -type DFF DFF
add mapped point spi_inst/input_text[39]/q spi_inst_input_text_reg[39]/Q -type DFF DFF
add mapped point spi_inst/input_text[49]/q spi_inst_input_text_reg[49]/Q -type DFF DFF
add mapped point spi_inst/input_text[31]/q spi_inst_input_text_reg[31]/Q -type DFF DFF
add mapped point spi_inst/input_text[3]/q spi_inst_input_text_reg[3]/Q -type DFF DFF
add mapped point spi_inst/input_text[42]/q spi_inst_input_text_reg[42]/Q -type DFF DFF
add mapped point spi_inst/input_text[48]/q spi_inst_input_text_reg[48]/Q -type DFF DFF
add mapped point spi_inst/input_text[32]/q spi_inst_input_text_reg[32]/Q -type DFF DFF
add mapped point spi_inst/input_text[16]/q spi_inst_input_text_reg[16]/Q -type DFF DFF
add mapped point spi_inst/input_text[7]/q spi_inst_input_text_reg[7]/Q -type DFF DFF
add mapped point spi_inst/input_text[37]/q spi_inst_input_text_reg[37]/Q -type DFF DFF
add mapped point spi_inst/input_text[5]/q spi_inst_input_text_reg[5]/Q -type DFF DFF
add mapped point spi_inst/input_text[35]/q spi_inst_input_text_reg[35]/Q -type DFF DFF
add mapped point spi_inst/input_text[23]/q spi_inst_input_text_reg[23]/Q -type DFF DFF
add mapped point spi_inst/input_text[17]/q spi_inst_input_text_reg[17]/Q -type DFF DFF
add mapped point spi_inst/input_text[55]/q spi_inst_input_text_reg[55]/Q -type DFF DFF
add mapped point spi_inst/input_text[61]/q spi_inst_input_text_reg[61]/Q -type DFF DFF
add mapped point spi_inst/input_text[25]/q spi_inst_input_text_reg[25]/Q -type DFF DFF
add mapped point spi_inst/input_text[19]/q spi_inst_input_text_reg[19]/Q -type DFF DFF
add mapped point spi_inst/input_text[21]/q spi_inst_input_text_reg[21]/Q -type DFF DFF
add mapped point spi_inst/input_text[59]/q spi_inst_input_text_reg[59]/Q -type DFF DFF
add mapped point crypt/q crypt_reg/Q -type DFF DFF
add mapped point spi_inst/input_text[9]/q spi_inst_input_text_reg[9]/Q -type DFF DFF
add mapped point spi_inst/input_text[13]/q spi_inst_input_text_reg[13]/Q -type DFF DFF
add mapped point spi_inst/input_text[50]/q spi_inst_input_text_reg[50]/Q -type DFF DFF
add mapped point spi_inst/input_text[51]/q spi_inst_input_text_reg[51]/Q -type DFF DFF
add mapped point spi_inst/input_text[62]/q spi_inst_input_text_reg[62]/Q -type DFF DFF
add mapped point spi_inst/input_text[11]/q spi_inst_input_text_reg[11]/Q -type DFF DFF
add mapped point spi_inst/input_text[27]/q spi_inst_input_text_reg[27]/Q -type DFF DFF
add mapped point spi_inst/input_text[29]/q spi_inst_input_text_reg[29]/Q -type DFF DFF
add mapped point transaction_state[1]/q transaction_state_reg[1]/Q -type DFF DFF
add mapped point transaction_state[0]/q transaction_state_reg[0]/Q -type DFF DFF
add mapped point data_reg[46]/q data_reg_reg[46]/Q -type DFF DFF
add mapped point data_reg[47]/q data_reg_reg[47]/Q -type DFF DFF
add mapped point data_reg[49]/q data_reg_reg[49]/Q -type DFF DFF
add mapped point data_reg[51]/q data_reg_reg[51]/Q -type DFF DFF
add mapped point data_reg[53]/q data_reg_reg[53]/Q -type DFF DFF
add mapped point data_reg[55]/q data_reg_reg[55]/Q -type DFF DFF
add mapped point data_reg[57]/q data_reg_reg[57]/Q -type DFF DFF
add mapped point data_reg[59]/q data_reg_reg[59]/Q -type DFF DFF
add mapped point data_reg[61]/q data_reg_reg[61]/Q -type DFF DFF
add mapped point data_reg[8]/q data_reg_reg[8]/Q -type DFF DFF
add mapped point data_reg[16]/q data_reg_reg[16]/Q -type DFF DFF
add mapped point spi_inst/bit_cnt[6]/q spi_inst_bit_cnt_reg[6]/Q -type DFF DFF
add mapped point data_reg[4]/q data_reg_reg[4]/Q -type DFF DFF
add mapped point data_reg[0]/q data_reg_reg[0]/Q -type DFF DFF
add mapped point data_reg[58]/q data_reg_reg[58]/Q -type DFF DFF
add mapped point data_reg[62]/q data_reg_reg[62]/Q -type DFF DFF
add mapped point data_reg[63]/q data_reg_reg[63]/Q -type DFF DFF
add mapped point data_reg[10]/q data_reg_reg[10]/Q -type DFF DFF
add mapped point data_reg[20]/q data_reg_reg[20]/Q -type DFF DFF
add mapped point data_reg[22]/q data_reg_reg[22]/Q -type DFF DFF
add mapped point data_reg[24]/q data_reg_reg[24]/Q -type DFF DFF
add mapped point data_reg[18]/q data_reg_reg[18]/Q -type DFF DFF
add mapped point data_reg[2]/q data_reg_reg[2]/Q -type DFF DFF
add mapped point data_reg[6]/q data_reg_reg[6]/Q -type DFF DFF
add mapped point data_reg[12]/q data_reg_reg[12]/Q -type DFF DFF
add mapped point data_reg[1]/q data_reg_reg[1]/Q -type DFF DFF
add mapped point data_reg[3]/q data_reg_reg[3]/Q -type DFF DFF
add mapped point data_reg[60]/q data_reg_reg[60]/Q -type DFF DFF
add mapped point data_reg[5]/q data_reg_reg[5]/Q -type DFF DFF
add mapped point data_reg[7]/q data_reg_reg[7]/Q -type DFF DFF
add mapped point data_reg[9]/q data_reg_reg[9]/Q -type DFF DFF
add mapped point data_reg[11]/q data_reg_reg[11]/Q -type DFF DFF
add mapped point data_reg[13]/q data_reg_reg[13]/Q -type DFF DFF
add mapped point data_reg[14]/q data_reg_reg[14]/Q -type DFF DFF
add mapped point data_reg[15]/q data_reg_reg[15]/Q -type DFF DFF
add mapped point data_reg[56]/q data_reg_reg[56]/Q -type DFF DFF
add mapped point data_reg[17]/q data_reg_reg[17]/Q -type DFF DFF
add mapped point data_reg[19]/q data_reg_reg[19]/Q -type DFF DFF
add mapped point data_reg[21]/q data_reg_reg[21]/Q -type DFF DFF
add mapped point data_reg[23]/q data_reg_reg[23]/Q -type DFF DFF
add mapped point data_reg[25]/q data_reg_reg[25]/Q -type DFF DFF
add mapped point data_reg[27]/q data_reg_reg[27]/Q -type DFF DFF
add mapped point data_reg[29]/q data_reg_reg[29]/Q -type DFF DFF
add mapped point data_reg[31]/q data_reg_reg[31]/Q -type DFF DFF
add mapped point data_reg[33]/q data_reg_reg[33]/Q -type DFF DFF
add mapped point data_reg[35]/q data_reg_reg[35]/Q -type DFF DFF
add mapped point data_reg[54]/q data_reg_reg[54]/Q -type DFF DFF
add mapped point data_reg[37]/q data_reg_reg[37]/Q -type DFF DFF
add mapped point data_reg[39]/q data_reg_reg[39]/Q -type DFF DFF
add mapped point data_reg[41]/q data_reg_reg[41]/Q -type DFF DFF
add mapped point data_reg[43]/q data_reg_reg[43]/Q -type DFF DFF
add mapped point data_reg[45]/q data_reg_reg[45]/Q -type DFF DFF
add mapped point data_reg[52]/q data_reg_reg[52]/Q -type DFF DFF
add mapped point data_reg[30]/q data_reg_reg[30]/Q -type DFF DFF
add mapped point data_reg[32]/q data_reg_reg[32]/Q -type DFF DFF
add mapped point data_reg[34]/q data_reg_reg[34]/Q -type DFF DFF
add mapped point data_reg[36]/q data_reg_reg[36]/Q -type DFF DFF
add mapped point data_reg[28]/q data_reg_reg[28]/Q -type DFF DFF
add mapped point data_reg[38]/q data_reg_reg[38]/Q -type DFF DFF
add mapped point data_reg[40]/q data_reg_reg[40]/Q -type DFF DFF
add mapped point data_reg[42]/q data_reg_reg[42]/Q -type DFF DFF
add mapped point data_reg[44]/q data_reg_reg[44]/Q -type DFF DFF
add mapped point data_reg[26]/q data_reg_reg[26]/Q -type DFF DFF
add mapped point data_reg[48]/q data_reg_reg[48]/Q -type DFF DFF
add mapped point data_reg[50]/q data_reg_reg[50]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[2]/q spi_inst_shreg_out_reg[2]/Q -type DFF DFF
add mapped point trigger_operation/q trigger_operation_reg/Q -type DFF DFF
add mapped point spi_inst/bit_cnt[5]/q spi_inst_bit_cnt_reg[5]/Q -type DFF DFF
add mapped point csm_inst/round_counter[3]/q csm_inst_round_counter_reg[3]/Q -type DFF DFF
add mapped point csm_inst/left_reg[11]/q csm_inst_left_reg_reg[11]/Q -type DFF DFF
add mapped point csm_inst/left_reg[17]/q csm_inst_left_reg_reg[17]/Q -type DFF DFF
add mapped point csm_inst/left_reg[5]/q csm_inst_left_reg_reg[5]/Q -type DFF DFF
add mapped point csm_inst/left_reg[30]/q csm_inst_left_reg_reg[30]/Q -type DFF DFF
add mapped point csm_inst/left_reg[27]/q csm_inst_left_reg_reg[27]/Q -type DFF DFF
add mapped point csm_inst/left_reg[4]/q csm_inst_left_reg_reg[4]/Q -type DFF DFF
add mapped point csm_inst/left_reg[3]/q csm_inst_left_reg_reg[3]/Q -type DFF DFF
add mapped point csm_inst/left_reg[13]/q csm_inst_left_reg_reg[13]/Q -type DFF DFF
add mapped point csm_inst/left_reg[31]/q csm_inst_left_reg_reg[31]/Q -type DFF DFF
add mapped point csm_inst/left_reg[6]/q csm_inst_left_reg_reg[6]/Q -type DFF DFF
add mapped point csm_inst/left_reg[8]/q csm_inst_left_reg_reg[8]/Q -type DFF DFF
add mapped point csm_inst/left_reg[9]/q csm_inst_left_reg_reg[9]/Q -type DFF DFF
add mapped point csm_inst/left_reg[1]/q csm_inst_left_reg_reg[1]/Q -type DFF DFF
add mapped point csm_inst/left_reg[22]/q csm_inst_left_reg_reg[22]/Q -type DFF DFF
add mapped point csm_inst/left_reg[19]/q csm_inst_left_reg_reg[19]/Q -type DFF DFF
add mapped point csm_inst/left_reg[16]/q csm_inst_left_reg_reg[16]/Q -type DFF DFF
add mapped point csm_inst/left_reg[20]/q csm_inst_left_reg_reg[20]/Q -type DFF DFF
add mapped point csm_inst/left_reg[21]/q csm_inst_left_reg_reg[21]/Q -type DFF DFF
add mapped point csm_inst/left_reg[7]/q csm_inst_left_reg_reg[7]/Q -type DFF DFF
add mapped point csm_inst/left_reg[24]/q csm_inst_left_reg_reg[24]/Q -type DFF DFF
add mapped point csm_inst/left_reg[26]/q csm_inst_left_reg_reg[26]/Q -type DFF DFF
add mapped point csm_inst/left_reg[28]/q csm_inst_left_reg_reg[28]/Q -type DFF DFF
add mapped point csm_inst/left_reg[15]/q csm_inst_left_reg_reg[15]/Q -type DFF DFF
add mapped point csm_inst/left_reg[25]/q csm_inst_left_reg_reg[25]/Q -type DFF DFF
add mapped point csm_inst/left_reg[29]/q csm_inst_left_reg_reg[29]/Q -type DFF DFF
add mapped point csm_inst/left_reg[10]/q csm_inst_left_reg_reg[10]/Q -type DFF DFF
add mapped point csm_inst/left_reg[18]/q csm_inst_left_reg_reg[18]/Q -type DFF DFF
add mapped point csm_inst/left_reg[12]/q csm_inst_left_reg_reg[12]/Q -type DFF DFF
add mapped point csm_inst/left_reg[2]/q csm_inst_left_reg_reg[2]/Q -type DFF DFF
add mapped point csm_inst/left_reg[0]/q csm_inst_left_reg_reg[0]/Q -type DFF DFF
add mapped point csm_inst/left_reg[23]/q csm_inst_left_reg_reg[23]/Q -type DFF DFF
add mapped point csm_inst/left_reg[14]/q csm_inst_left_reg_reg[14]/Q -type DFF DFF
add mapped point spi_inst/shreg_out[1]/q spi_inst_shreg_out_reg[1]/Q -type DFF DFF
add mapped point spi_inst/bit_cnt[4]/q spi_inst_bit_cnt_reg[4]/Q -type DFF DFF
add mapped point csm_inst/round_counter[2]/q csm_inst_round_counter_reg[2]/Q -type DFF DFF
add mapped point csm_inst/mode/q csm_inst_mode_reg/Q -type DFF DFF
add mapped point csm_inst/round_counter[1]/q csm_inst_round_counter_reg[1]/Q -type DFF DFF
add mapped point csm_inst/state[0]/q csm_inst_state_reg[0]/Q -type DFF DFF
add mapped point csm_inst/done_encrypt/q csm_inst_done_encrypt_reg/Q -type DFF DFF
add mapped point csm_inst/done_decrypt/q csm_inst_done_decrypt_reg/Q -type DFF DFF
add mapped point csm_inst/round_counter[0]/q csm_inst_round_counter_reg[0]/Q -type DFF DFF
add mapped point csm_inst/output_text[3]/q csm_inst_output_text_reg[3]/Q -type DFF DFF
add mapped point csm_inst/output_text[55]/q csm_inst_output_text_reg[55]/Q -type DFF DFF
add mapped point csm_inst/output_text[4]/q csm_inst_output_text_reg[4]/Q -type DFF DFF
add mapped point csm_inst/output_text[50]/q csm_inst_output_text_reg[50]/Q -type DFF DFF
add mapped point csm_inst/output_text[51]/q csm_inst_output_text_reg[51]/Q -type DFF DFF
add mapped point csm_inst/output_text[2]/q csm_inst_output_text_reg[2]/Q -type DFF DFF
add mapped point csm_inst/output_text[0]/q csm_inst_output_text_reg[0]/Q -type DFF DFF
add mapped point csm_inst/output_text[40]/q csm_inst_output_text_reg[40]/Q -type DFF DFF
add mapped point csm_inst/output_text[48]/q csm_inst_output_text_reg[48]/Q -type DFF DFF
add mapped point csm_inst/output_text[5]/q csm_inst_output_text_reg[5]/Q -type DFF DFF
add mapped point csm_inst/output_text[18]/q csm_inst_output_text_reg[18]/Q -type DFF DFF
add mapped point spi_inst/bit_cnt[3]/q spi_inst_bit_cnt_reg[3]/Q -type DFF DFF
add mapped point csm_inst/output_text[49]/q csm_inst_output_text_reg[49]/Q -type DFF DFF
add mapped point csm_inst/output_text[13]/q csm_inst_output_text_reg[13]/Q -type DFF DFF
add mapped point csm_inst/output_text[33]/q csm_inst_output_text_reg[33]/Q -type DFF DFF
add mapped point csm_inst/output_text[47]/q csm_inst_output_text_reg[47]/Q -type DFF DFF
add mapped point csm_inst/output_text[56]/q csm_inst_output_text_reg[56]/Q -type DFF DFF
add mapped point csm_inst/output_text[10]/q csm_inst_output_text_reg[10]/Q -type DFF DFF
add mapped point csm_inst/output_text[41]/q csm_inst_output_text_reg[41]/Q -type DFF DFF
add mapped point csm_inst/output_text[54]/q csm_inst_output_text_reg[54]/Q -type DFF DFF
add mapped point csm_inst/output_text[20]/q csm_inst_output_text_reg[20]/Q -type DFF DFF
add mapped point csm_inst/output_text[59]/q csm_inst_output_text_reg[59]/Q -type DFF DFF
add mapped point csm_inst/output_text[25]/q csm_inst_output_text_reg[25]/Q -type DFF DFF
add mapped point csm_inst/output_text[32]/q csm_inst_output_text_reg[32]/Q -type DFF DFF
add mapped point csm_inst/output_text[6]/q csm_inst_output_text_reg[6]/Q -type DFF DFF
add mapped point csm_inst/output_text[44]/q csm_inst_output_text_reg[44]/Q -type DFF DFF
add mapped point csm_inst/output_text[8]/q csm_inst_output_text_reg[8]/Q -type DFF DFF
add mapped point csm_inst/output_text[45]/q csm_inst_output_text_reg[45]/Q -type DFF DFF
add mapped point csm_inst/output_text[36]/q csm_inst_output_text_reg[36]/Q -type DFF DFF
add mapped point csm_inst/output_text[62]/q csm_inst_output_text_reg[62]/Q -type DFF DFF
add mapped point csm_inst/output_text[16]/q csm_inst_output_text_reg[16]/Q -type DFF DFF
add mapped point csm_inst/output_text[58]/q csm_inst_output_text_reg[58]/Q -type DFF DFF
add mapped point csm_inst/output_text[17]/q csm_inst_output_text_reg[17]/Q -type DFF DFF
add mapped point csm_inst/output_text[61]/q csm_inst_output_text_reg[61]/Q -type DFF DFF
add mapped point csm_inst/output_text[63]/q csm_inst_output_text_reg[63]/Q -type DFF DFF
add mapped point csm_inst/output_text[57]/q csm_inst_output_text_reg[57]/Q -type DFF DFF
add mapped point csm_inst/output_text[1]/q csm_inst_output_text_reg[1]/Q -type DFF DFF
add mapped point csm_inst/output_text[14]/q csm_inst_output_text_reg[14]/Q -type DFF DFF
add mapped point csm_inst/output_text[11]/q csm_inst_output_text_reg[11]/Q -type DFF DFF
add mapped point csm_inst/output_text[15]/q csm_inst_output_text_reg[15]/Q -type DFF DFF
add mapped point csm_inst/output_text[53]/q csm_inst_output_text_reg[53]/Q -type DFF DFF
add mapped point csm_inst/output_text[21]/q csm_inst_output_text_reg[21]/Q -type DFF DFF
add mapped point cs_rise_delayed/q cs_rise_delayed_reg/Q -type DFF DFF
add mapped point csm_inst/output_text[7]/q csm_inst_output_text_reg[7]/Q -type DFF DFF
add mapped point csm_inst/output_text[34]/q csm_inst_output_text_reg[34]/Q -type DFF DFF
add mapped point csm_inst/output_text[42]/q csm_inst_output_text_reg[42]/Q -type DFF DFF
add mapped point csm_inst/output_text[35]/q csm_inst_output_text_reg[35]/Q -type DFF DFF
add mapped point csm_inst/state[2]/q csm_inst_state_reg[2]/Q -type DFF DFF
add mapped point csm_inst/output_text[30]/q csm_inst_output_text_reg[30]/Q -type DFF DFF
add mapped point csm_inst/output_text[29]/q csm_inst_output_text_reg[29]/Q -type DFF DFF
add mapped point csm_inst/output_text[26]/q csm_inst_output_text_reg[26]/Q -type DFF DFF
add mapped point csm_inst/output_text[31]/q csm_inst_output_text_reg[31]/Q -type DFF DFF
add mapped point csm_inst/output_text[28]/q csm_inst_output_text_reg[28]/Q -type DFF DFF
add mapped point csm_inst/output_text[9]/q csm_inst_output_text_reg[9]/Q -type DFF DFF
add mapped point csm_inst/output_text[43]/q csm_inst_output_text_reg[43]/Q -type DFF DFF
add mapped point csm_inst/output_text[27]/q csm_inst_output_text_reg[27]/Q -type DFF DFF
add mapped point csm_inst/output_text[24]/q csm_inst_output_text_reg[24]/Q -type DFF DFF
add mapped point csm_inst/output_text[60]/q csm_inst_output_text_reg[60]/Q -type DFF DFF
add mapped point csm_inst/output_text[52]/q csm_inst_output_text_reg[52]/Q -type DFF DFF
add mapped point csm_inst/output_text[23]/q csm_inst_output_text_reg[23]/Q -type DFF DFF
add mapped point csm_inst/output_text[46]/q csm_inst_output_text_reg[46]/Q -type DFF DFF
add mapped point csm_inst/output_text[39]/q csm_inst_output_text_reg[39]/Q -type DFF DFF
add mapped point csm_inst/output_text[19]/q csm_inst_output_text_reg[19]/Q -type DFF DFF
add mapped point csm_inst/output_text[37]/q csm_inst_output_text_reg[37]/Q -type DFF DFF
add mapped point csm_inst/output_text[38]/q csm_inst_output_text_reg[38]/Q -type DFF DFF
add mapped point csm_inst/output_text[12]/q csm_inst_output_text_reg[12]/Q -type DFF DFF
add mapped point csm_inst/output_text[22]/q csm_inst_output_text_reg[22]/Q -type DFF DFF
add mapped point spi_tx_data[41]/q spi_tx_data_reg[41]/Q -type DFF DFF
add mapped point spi_tx_data[0]/q spi_tx_data_reg[0]/Q -type DFF DFF
add mapped point spi_tx_data[42]/q spi_tx_data_reg[42]/Q -type DFF DFF
add mapped point spi_tx_data[60]/q spi_tx_data_reg[60]/Q -type DFF DFF
add mapped point spi_tx_data[23]/q spi_tx_data_reg[23]/Q -type DFF DFF
add mapped point spi_tx_data[56]/q spi_tx_data_reg[56]/Q -type DFF DFF
add mapped point spi_tx_data[50]/q spi_tx_data_reg[50]/Q -type DFF DFF
add mapped point spi_tx_data[45]/q spi_tx_data_reg[45]/Q -type DFF DFF
add mapped point spi_tx_data[37]/q spi_tx_data_reg[37]/Q -type DFF DFF
add mapped point spi_tx_data[33]/q spi_tx_data_reg[33]/Q -type DFF DFF
add mapped point spi_tx_data[26]/q spi_tx_data_reg[26]/Q -type DFF DFF
add mapped point spi_tx_data[16]/q spi_tx_data_reg[16]/Q -type DFF DFF
add mapped point spi_tx_data[13]/q spi_tx_data_reg[13]/Q -type DFF DFF
add mapped point spi_tx_data[2]/q spi_tx_data_reg[2]/Q -type DFF DFF
add mapped point spi_tx_data[32]/q spi_tx_data_reg[32]/Q -type DFF DFF
add mapped point spi_tx_data[48]/q spi_tx_data_reg[48]/Q -type DFF DFF
add mapped point spi_tx_data[39]/q spi_tx_data_reg[39]/Q -type DFF DFF
add mapped point spi_tx_data[12]/q spi_tx_data_reg[12]/Q -type DFF DFF
add mapped point spi_tx_data[7]/q spi_tx_data_reg[7]/Q -type DFF DFF
add mapped point spi_tx_data[63]/q spi_tx_data_reg[63]/Q -type DFF DFF
add mapped point spi_tx_data[11]/q spi_tx_data_reg[11]/Q -type DFF DFF
add mapped point spi_tx_data[5]/q spi_tx_data_reg[5]/Q -type DFF DFF
add mapped point spi_tx_data[8]/q spi_tx_data_reg[8]/Q -type DFF DFF
add mapped point spi_tx_data[9]/q spi_tx_data_reg[9]/Q -type DFF DFF
add mapped point spi_tx_data[27]/q spi_tx_data_reg[27]/Q -type DFF DFF
add mapped point spi_tx_data[14]/q spi_tx_data_reg[14]/Q -type DFF DFF
add mapped point spi_tx_data[15]/q spi_tx_data_reg[15]/Q -type DFF DFF
add mapped point spi_tx_data[17]/q spi_tx_data_reg[17]/Q -type DFF DFF
add mapped point spi_tx_data[18]/q spi_tx_data_reg[18]/Q -type DFF DFF
add mapped point spi_tx_data[19]/q spi_tx_data_reg[19]/Q -type DFF DFF
add mapped point spi_tx_data[21]/q spi_tx_data_reg[21]/Q -type DFF DFF
add mapped point spi_tx_data[22]/q spi_tx_data_reg[22]/Q -type DFF DFF
add mapped point spi_tx_data[24]/q spi_tx_data_reg[24]/Q -type DFF DFF
add mapped point spi_tx_data[25]/q spi_tx_data_reg[25]/Q -type DFF DFF
add mapped point spi_tx_data[58]/q spi_tx_data_reg[58]/Q -type DFF DFF
add mapped point spi_tx_data[30]/q spi_tx_data_reg[30]/Q -type DFF DFF
add mapped point spi_tx_data[31]/q spi_tx_data_reg[31]/Q -type DFF DFF
add mapped point spi_tx_data[34]/q spi_tx_data_reg[34]/Q -type DFF DFF
add mapped point spi_tx_data[35]/q spi_tx_data_reg[35]/Q -type DFF DFF
add mapped point spi_tx_data[36]/q spi_tx_data_reg[36]/Q -type DFF DFF
add mapped point spi_tx_data[40]/q spi_tx_data_reg[40]/Q -type DFF DFF
add mapped point spi_tx_data[43]/q spi_tx_data_reg[43]/Q -type DFF DFF
add mapped point spi_tx_data[46]/q spi_tx_data_reg[46]/Q -type DFF DFF
add mapped point spi_tx_data[47]/q spi_tx_data_reg[47]/Q -type DFF DFF
add mapped point spi_tx_data[49]/q spi_tx_data_reg[49]/Q -type DFF DFF
add mapped point spi_tx_data[51]/q spi_tx_data_reg[51]/Q -type DFF DFF
add mapped point spi_tx_data[53]/q spi_tx_data_reg[53]/Q -type DFF DFF
add mapped point spi_tx_data[54]/q spi_tx_data_reg[54]/Q -type DFF DFF
add mapped point spi_tx_data[57]/q spi_tx_data_reg[57]/Q -type DFF DFF
add mapped point spi_tx_data[59]/q spi_tx_data_reg[59]/Q -type DFF DFF
add mapped point spi_tx_data[62]/q spi_tx_data_reg[62]/Q -type DFF DFF
add mapped point spi_tx_data[55]/q spi_tx_data_reg[55]/Q -type DFF DFF
add mapped point spi_tx_data[29]/q spi_tx_data_reg[29]/Q -type DFF DFF
add mapped point spi_tx_data[61]/q spi_tx_data_reg[61]/Q -type DFF DFF
add mapped point spi_tx_data[52]/q spi_tx_data_reg[52]/Q -type DFF DFF
add mapped point spi_tx_data[38]/q spi_tx_data_reg[38]/Q -type DFF DFF
add mapped point spi_tx_data[20]/q spi_tx_data_reg[20]/Q -type DFF DFF
add mapped point spi_tx_data[44]/q spi_tx_data_reg[44]/Q -type DFF DFF
add mapped point spi_tx_data[28]/q spi_tx_data_reg[28]/Q -type DFF DFF
add mapped point spi_tx_data[6]/q spi_tx_data_reg[6]/Q -type DFF DFF
add mapped point spi_tx_data[3]/q spi_tx_data_reg[3]/Q -type DFF DFF
add mapped point spi_tx_data[4]/q spi_tx_data_reg[4]/Q -type DFF DFF
add mapped point spi_tx_data[10]/q spi_tx_data_reg[10]/Q -type DFF DFF
add mapped point spi_tx_data[1]/q spi_tx_data_reg[1]/Q -type DFF DFF
add mapped point spi_inst/bit_cnt[1]/q spi_inst_bit_cnt_reg[1]/Q -type DFF DFF
add mapped point spi_inst/bit_cnt[2]/q spi_inst_bit_cnt_reg[2]/Q -type DFF DFF
add mapped point cs_prev/q cs_prev_reg/Q -type DFF DFF
add mapped point active/q active_reg/Q -type DFF DFF
add mapped point csm_inst/state[1]/q csm_inst_state_reg[1]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[62]/q spi_inst_shreg_in_reg[62]/Q -type DFF DFF
add mapped point cs_sync/q cs_sync_reg/Q -type DFF DFF
add mapped point spi_inst/shreg_in[34]/q spi_inst_shreg_in_reg[34]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[26]/q spi_inst_shreg_in_reg[26]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[30]/q spi_inst_shreg_in_reg[30]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[51]/q spi_inst_shreg_in_reg[51]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[0]/q spi_inst_shreg_in_reg[0]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[13]/q spi_inst_shreg_in_reg[13]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[18]/q spi_inst_shreg_in_reg[18]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[61]/q spi_inst_shreg_in_reg[61]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[9]/q spi_inst_shreg_in_reg[9]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[10]/q spi_inst_shreg_in_reg[10]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[16]/q spi_inst_shreg_in_reg[16]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[4]/q spi_inst_shreg_in_reg[4]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[57]/q spi_inst_shreg_in_reg[57]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[60]/q spi_inst_shreg_in_reg[60]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[48]/q spi_inst_shreg_in_reg[48]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[27]/q spi_inst_shreg_in_reg[27]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[58]/q spi_inst_shreg_in_reg[58]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[22]/q spi_inst_shreg_in_reg[22]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[45]/q spi_inst_shreg_in_reg[45]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[53]/q spi_inst_shreg_in_reg[53]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[1]/q spi_inst_shreg_in_reg[1]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[8]/q spi_inst_shreg_in_reg[8]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[56]/q spi_inst_shreg_in_reg[56]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[17]/q spi_inst_shreg_in_reg[17]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[21]/q spi_inst_shreg_in_reg[21]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[5]/q spi_inst_shreg_in_reg[5]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[55]/q spi_inst_shreg_in_reg[55]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[50]/q spi_inst_shreg_in_reg[50]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[54]/q spi_inst_shreg_in_reg[54]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[20]/q spi_inst_shreg_in_reg[20]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[29]/q spi_inst_shreg_in_reg[29]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[52]/q spi_inst_shreg_in_reg[52]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[40]/q spi_inst_shreg_in_reg[40]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[31]/q spi_inst_shreg_in_reg[31]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[14]/q spi_inst_shreg_in_reg[14]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[25]/q spi_inst_shreg_in_reg[25]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[46]/q spi_inst_shreg_in_reg[46]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[33]/q spi_inst_shreg_in_reg[33]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[7]/q spi_inst_shreg_in_reg[7]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[19]/q spi_inst_shreg_in_reg[19]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[37]/q spi_inst_shreg_in_reg[37]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[42]/q spi_inst_shreg_in_reg[42]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[28]/q spi_inst_shreg_in_reg[28]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[44]/q spi_inst_shreg_in_reg[44]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[24]/q spi_inst_shreg_in_reg[24]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[2]/q spi_inst_shreg_in_reg[2]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[35]/q spi_inst_shreg_in_reg[35]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[41]/q spi_inst_shreg_in_reg[41]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[47]/q spi_inst_shreg_in_reg[47]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[43]/q spi_inst_shreg_in_reg[43]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[3]/q spi_inst_shreg_in_reg[3]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[59]/q spi_inst_shreg_in_reg[59]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[23]/q spi_inst_shreg_in_reg[23]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[6]/q spi_inst_shreg_in_reg[6]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[32]/q spi_inst_shreg_in_reg[32]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[15]/q spi_inst_shreg_in_reg[15]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[11]/q spi_inst_shreg_in_reg[11]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[38]/q spi_inst_shreg_in_reg[38]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[36]/q spi_inst_shreg_in_reg[36]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[49]/q spi_inst_shreg_in_reg[49]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[12]/q spi_inst_shreg_in_reg[12]/Q -type DFF DFF
add mapped point spi_inst/shreg_in[39]/q spi_inst_shreg_in_reg[39]/Q -type DFF DFF
add mapped point cs_meta/q cs_meta_reg/Q -type DFF DFF
add mapped point spi_inst/bit_cnt[0]/q spi_inst_bit_cnt_reg[0]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
