
// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Nov 22 2025 14:36:19 MST (Nov 22 2025 21:36:19 UTC)

// Verification Directory fv/top_pad 

module TopModule(clk, rst, sclk, cs_n, mosi, miso);
  input clk, rst, sclk, cs_n, mosi;
  output miso;
  wire clk, rst, sclk, cs_n, mosi;
  wire miso;
  wire [63:0] key_reg;
  wire [63:0] data_reg;
  wire [63:0] des_output;
  wire [63:0] spi_tx_data;
  wire [63:0] spi_rx_data;
  wire [1:0] transaction_state;
  wire active, crypt, cs_meta, cs_prev, cs_rise_delayed, cs_sync,
       done_decrypt, done_decrypt_latched;
  wire done_encrypt, done_encrypt_latched, n_0, n_1, n_2, n_3, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_83, n_84, n_85, n_86;
  wire n_87, n_88, n_89, n_90, n_91, n_92, n_93, n_94;
  wire n_95, n_96, n_97, n_98, n_99, n_100, n_101, n_102;
  wire n_103, n_104, n_105, n_106, n_107, n_108, n_109, n_110;
  wire n_111, n_112, n_113, n_114, n_115, n_116, n_117, n_118;
  wire n_119, n_120, n_121, n_122, n_123, n_124, n_125, n_126;
  wire n_127, n_128, n_129, n_130, n_131, n_132, n_133, n_134;
  wire n_135, n_136, n_137, n_138, n_139, n_140, n_141, n_142;
  wire n_143, n_144, n_145, n_146, n_147, n_148, n_149, n_150;
  wire n_151, n_152, n_153, n_154, n_155, n_156, n_157, n_158;
  wire n_159, n_160, n_161, n_162, n_165, n_166, n_167, n_168;
  wire n_169, n_170, n_171, n_172, n_173, n_174, n_175, n_176;
  wire n_177, n_178, n_179, n_180, n_181, n_182, n_183, n_184;
  wire n_185, n_186, n_187, n_188, n_189, n_190, n_191, n_192;
  wire n_193, n_194, n_195, n_196, n_197, n_198, n_199, n_200;
  wire n_201, n_202, n_203, n_204, n_205, n_206, n_207, n_208;
  wire n_209, n_210, n_211, n_212, n_213, n_214, n_215, n_216;
  wire n_217, n_218, n_219, n_220, n_221, n_222, n_223, n_224;
  wire n_225, n_226, n_227, n_228, n_229, n_230, n_231, n_232;
  wire n_233, n_234, n_235, start_decrypt, start_encrypt,
       trigger_operation;
  Control_State_Machine csm_inst(.clk (clk), .rst (rst), .start_encrypt
       (start_encrypt), .start_decrypt (start_decrypt), .key (key_reg),
       .input_text (data_reg), .done_encrypt (done_encrypt),
       .done_decrypt (done_decrypt), .output_text (des_output));
  SPI spi_inst(.rst (n_5), .sclk (sclk), .cs_n (cs_n), .mosi (mosi),
       .miso (miso), .output_text (spi_tx_data), .input_text
       (spi_rx_data));
  DFFQSRX1 trigger_operation_reg(.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_235), .Q (trigger_operation));
  INVX2 g657(.A (n_234), .Z (n_235));
  NAND3X1 g658__2398(.A (n_6), .B (cs_rise_delayed), .C
       (transaction_state[1]), .Z (n_234));
  DFFQSRX1 \spi_tx_data_reg[27] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_182), .Q (spi_tx_data[27]));
  DFFQSRX1 \spi_tx_data_reg[49] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_219), .Q (spi_tx_data[49]));
  DFFQSRX1 \spi_tx_data_reg[1] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_222), .Q (spi_tx_data[1]));
  DFFQSRX1 \spi_tx_data_reg[0] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_224), .Q (spi_tx_data[0]));
  DFFQSRX1 \spi_tx_data_reg[33] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_191), .Q (spi_tx_data[33]));
  DFFQSRX1 \spi_tx_data_reg[32] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_193), .Q (spi_tx_data[32]));
  DFFQSRX1 \spi_tx_data_reg[61] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_228), .Q (spi_tx_data[61]));
  DFFQSRX1 \spi_tx_data_reg[48] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_181), .Q (spi_tx_data[48]));
  DFFQSRX1 \spi_tx_data_reg[31] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_199), .Q (spi_tx_data[31]));
  DFFQSRX1 \spi_tx_data_reg[57] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_227), .Q (spi_tx_data[57]));
  DFFQSRX1 \spi_tx_data_reg[30] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_195), .Q (spi_tx_data[30]));
  DFFQSRX1 \spi_tx_data_reg[56] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_177), .Q (spi_tx_data[56]));
  DFFQSRX1 \spi_tx_data_reg[47] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_220), .Q (spi_tx_data[47]));
  DFFQSRX1 \spi_tx_data_reg[29] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_225), .Q (spi_tx_data[29]));
  DFFQSRX1 \spi_tx_data_reg[28] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_196), .Q (spi_tx_data[28]));
  DFFQSRX1 \spi_tx_data_reg[46] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_183), .Q (spi_tx_data[46]));
  DFFQSRX1 \spi_tx_data_reg[63] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_230), .Q (spi_tx_data[63]));
  DFFQSRX1 \spi_tx_data_reg[26] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_200), .Q (spi_tx_data[26]));
  DFFQSRX1 \spi_tx_data_reg[60] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_174), .Q (spi_tx_data[60]));
  DFFQSRX1 \spi_tx_data_reg[55] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_226), .Q (spi_tx_data[55]));
  DFFQSRX1 \spi_tx_data_reg[45] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_232), .Q (spi_tx_data[45]));
  DFFQSRX1 \spi_tx_data_reg[25] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_185), .Q (spi_tx_data[25]));
  DFFQSRX1 \spi_tx_data_reg[24] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_202), .Q (spi_tx_data[24]));
  DFFQSRX1 \spi_tx_data_reg[44] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_184), .Q (spi_tx_data[44]));
  DFFQSRX1 \spi_tx_data_reg[23] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_179), .Q (spi_tx_data[23]));
  DFFQSRX1 \spi_tx_data_reg[22] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_203), .Q (spi_tx_data[22]));
  DFFQSRX1 \spi_tx_data_reg[54] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_190), .Q (spi_tx_data[54]));
  DFFQSRX1 \spi_tx_data_reg[43] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_209), .Q (spi_tx_data[43]));
  DFFQSRX1 \spi_tx_data_reg[21] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_175), .Q (spi_tx_data[21]));
  DFFQSRX1 \spi_tx_data_reg[20] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_204), .Q (spi_tx_data[20]));
  DFFQSRX1 \spi_tx_data_reg[42] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_201), .Q (spi_tx_data[42]));
  DFFQSRX1 \spi_tx_data_reg[19] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_176), .Q (spi_tx_data[19]));
  DFFQSRX1 \spi_tx_data_reg[10] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_214), .Q (spi_tx_data[10]));
  DFFQSRX1 \spi_tx_data_reg[62] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_194), .Q (spi_tx_data[62]));
  DFFQSRX1 \spi_tx_data_reg[59] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_229), .Q (spi_tx_data[59]));
  DFFQSRX1 \spi_tx_data_reg[53] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_231), .Q (spi_tx_data[53]));
  DFFQSRX1 \spi_tx_data_reg[41] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_205), .Q (spi_tx_data[41]));
  DFFQSRX1 \spi_tx_data_reg[17] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_173), .Q (spi_tx_data[17]));
  DFFQSRX1 \spi_tx_data_reg[16] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_208), .Q (spi_tx_data[16]));
  DFFQSRX1 \spi_tx_data_reg[40] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_186), .Q (spi_tx_data[40]));
  DFFQSRX1 \spi_tx_data_reg[15] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_210), .Q (spi_tx_data[15]));
  DFFQSRX1 \spi_tx_data_reg[14] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_211), .Q (spi_tx_data[14]));
  DFFQSRX1 \spi_tx_data_reg[52] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_178), .Q (spi_tx_data[52]));
  DFFQSRX1 \spi_tx_data_reg[39] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_206), .Q (spi_tx_data[39]));
  DFFQSRX1 \spi_tx_data_reg[13] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_212), .Q (spi_tx_data[13]));
  DFFQSRX1 \spi_tx_data_reg[12] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_213), .Q (spi_tx_data[12]));
  DFFQSRX1 \spi_tx_data_reg[38] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_187), .Q (spi_tx_data[38]));
  DFFQSRX1 \spi_tx_data_reg[11] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_171), .Q (spi_tx_data[11]));
  DFFQSRX1 \spi_tx_data_reg[18] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_207), .Q (spi_tx_data[18]));
  DFFQSRX1 \spi_tx_data_reg[58] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_192), .Q (spi_tx_data[58]));
  DFFQSRX1 \spi_tx_data_reg[51] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_223), .Q (spi_tx_data[51]));
  DFFQSRX1 \spi_tx_data_reg[37] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_197), .Q (spi_tx_data[37]));
  DFFQSRX1 \spi_tx_data_reg[9] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_215), .Q (spi_tx_data[9]));
  DFFQSRX1 \spi_tx_data_reg[8] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_216), .Q (spi_tx_data[8]));
  DFFQSRX1 \spi_tx_data_reg[36] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_188), .Q (spi_tx_data[36]));
  DFFQSRX1 \spi_tx_data_reg[7] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_172), .Q (spi_tx_data[7]));
  DFFQSRX1 \spi_tx_data_reg[6] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_233), .Q (spi_tx_data[6]));
  DFFQSRX1 \spi_tx_data_reg[50] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_180), .Q (spi_tx_data[50]));
  DFFQSRX1 \spi_tx_data_reg[35] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_198), .Q (spi_tx_data[35]));
  DFFQSRX1 \spi_tx_data_reg[5] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_170), .Q (spi_tx_data[5]));
  DFFQSRX1 \spi_tx_data_reg[4] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_218), .Q (spi_tx_data[4]));
  DFFQSRX1 \spi_tx_data_reg[34] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_189), .Q (spi_tx_data[34]));
  DFFQSRX1 \spi_tx_data_reg[3] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_169), .Q (spi_tx_data[3]));
  DFFQSRX1 \spi_tx_data_reg[2] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_221), .Q (spi_tx_data[2]));
  DFFQSRX1 cs_rise_delayed_reg(.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_217), .Q (cs_rise_delayed));
  AND2X1 g724__5107(.A (n_162), .B (des_output[6]), .Z (n_233));
  AND2X1 g725__6260(.A (n_162), .B (des_output[45]), .Z (n_232));
  AND2X1 g726__4319(.A (n_162), .B (des_output[53]), .Z (n_231));
  AND2X1 g727__8428(.A (n_162), .B (des_output[63]), .Z (n_230));
  AND2X1 g728__5526(.A (n_168), .B (des_output[59]), .Z (n_229));
  AND2X1 g729__6783(.A (n_168), .B (des_output[61]), .Z (n_228));
  AND2X1 g730__3680(.A (n_168), .B (des_output[57]), .Z (n_227));
  AND2X1 g731__1617(.A (n_168), .B (des_output[55]), .Z (n_226));
  AND2X1 g732__2802(.A (n_168), .B (des_output[29]), .Z (n_225));
  AND2X1 g733__1705(.A (n_162), .B (des_output[0]), .Z (n_224));
  AND2X1 g734__5122(.A (n_168), .B (des_output[51]), .Z (n_223));
  AND2X1 g735__8246(.A (n_168), .B (des_output[1]), .Z (n_222));
  AND2X1 g736__7098(.A (n_162), .B (des_output[2]), .Z (n_221));
  AND2X1 g737__6131(.A (n_162), .B (des_output[47]), .Z (n_220));
  AND2X1 g738__1881(.A (n_168), .B (des_output[49]), .Z (n_219));
  AND2X1 g739__5115(.A (n_168), .B (des_output[4]), .Z (n_218));
  NOR2X1 g740__7482(.A (cs_prev), .B (n_167), .Z (n_217));
  AND2X1 g741__4733(.A (n_168), .B (des_output[8]), .Z (n_216));
  AND2X1 g742__6161(.A (n_168), .B (des_output[9]), .Z (n_215));
  AND2X1 g743__9315(.A (n_162), .B (des_output[10]), .Z (n_214));
  AND2X1 g744__9945(.A (n_162), .B (des_output[12]), .Z (n_213));
  AND2X1 g745__2883(.A (n_168), .B (des_output[13]), .Z (n_212));
  AND2X1 g746__2346(.A (n_168), .B (des_output[14]), .Z (n_211));
  AND2X1 g747__1666(.A (n_168), .B (des_output[15]), .Z (n_210));
  AND2X1 g748__7410(.A (n_162), .B (des_output[43]), .Z (n_209));
  AND2X1 g749__6417(.A (n_168), .B (des_output[16]), .Z (n_208));
  AND2X1 g750__5477(.A (n_168), .B (des_output[18]), .Z (n_207));
  AND2X1 g751__2398(.A (n_168), .B (des_output[39]), .Z (n_206));
  AND2X1 g752__5107(.A (n_162), .B (des_output[41]), .Z (n_205));
  AND2X1 g753__6260(.A (n_162), .B (des_output[20]), .Z (n_204));
  AND2X1 g754__4319(.A (n_162), .B (des_output[22]), .Z (n_203));
  AND2X1 g755__8428(.A (n_168), .B (des_output[24]), .Z (n_202));
  AND2X1 g756__5526(.A (n_168), .B (des_output[42]), .Z (n_201));
  AND2X1 g757__6783(.A (n_168), .B (des_output[26]), .Z (n_200));
  AND2X1 g758__3680(.A (n_168), .B (des_output[31]), .Z (n_199));
  AND2X1 g759__1617(.A (n_168), .B (des_output[35]), .Z (n_198));
  AND2X1 g760__2802(.A (n_162), .B (des_output[37]), .Z (n_197));
  AND2X1 g761__1705(.A (n_162), .B (des_output[28]), .Z (n_196));
  AND2X1 g762__5122(.A (n_162), .B (des_output[30]), .Z (n_195));
  AND2X1 g763__8246(.A (n_162), .B (des_output[62]), .Z (n_194));
  AND2X1 g764__7098(.A (n_162), .B (des_output[32]), .Z (n_193));
  AND2X1 g765__6131(.A (n_162), .B (des_output[58]), .Z (n_192));
  AND2X1 g766__1881(.A (n_168), .B (des_output[33]), .Z (n_191));
  AND2X1 g767__5115(.A (n_168), .B (des_output[54]), .Z (n_190));
  AND2X1 g768__7482(.A (n_162), .B (des_output[34]), .Z (n_189));
  AND2X1 g769__4733(.A (n_162), .B (des_output[36]), .Z (n_188));
  AND2X1 g770__6161(.A (n_168), .B (des_output[38]), .Z (n_187));
  AND2X1 g771__9315(.A (n_168), .B (des_output[40]), .Z (n_186));
  AND2X1 g772__9945(.A (n_168), .B (des_output[25]), .Z (n_185));
  AND2X1 g773__2883(.A (n_168), .B (des_output[44]), .Z (n_184));
  AND2X1 g774__2346(.A (n_162), .B (des_output[46]), .Z (n_183));
  AND2X1 g775__1666(.A (n_162), .B (des_output[27]), .Z (n_182));
  AND2X1 g776__7410(.A (n_162), .B (des_output[48]), .Z (n_181));
  AND2X1 g777__6417(.A (n_162), .B (des_output[50]), .Z (n_180));
  AND2X1 g778__5477(.A (n_168), .B (des_output[23]), .Z (n_179));
  AND2X1 g779__2398(.A (n_162), .B (des_output[52]), .Z (n_178));
  AND2X1 g780__5107(.A (n_168), .B (des_output[56]), .Z (n_177));
  AND2X1 g781__6260(.A (n_162), .B (des_output[19]), .Z (n_176));
  AND2X1 g782__4319(.A (n_162), .B (des_output[21]), .Z (n_175));
  AND2X1 g783__8428(.A (n_162), .B (des_output[60]), .Z (n_174));
  AND2X1 g784__5526(.A (n_168), .B (des_output[17]), .Z (n_173));
  AND2X1 g785__6783(.A (n_162), .B (des_output[7]), .Z (n_172));
  AND2X1 g786__3680(.A (n_168), .B (des_output[11]), .Z (n_171));
  AND2X1 g787__1617(.A (n_162), .B (des_output[5]), .Z (n_170));
  AND2X1 g788__2802(.A (n_162), .B (des_output[3]), .Z (n_169));
  DFFQSRX1 cs_prev_reg(.RESETB (1'b1), .SETB (n_5), .CLK (clk), .D
       (cs_sync), .Q (cs_prev));
  NOR2X1 g790__1705(.A (n_6), .B (n_166), .Z (n_168));
  INVX2 g791(.A (cs_sync), .Z (n_167));
  DFFQSRX1 cs_sync_reg(.RESETB (1'b1), .SETB (n_5), .CLK (clk), .D
       (cs_meta), .Q (cs_sync));
  NAND2X1 g793__5122(.A (n_165), .B (transaction_state[1]), .Z (n_166));
  DFFQSRX1 cs_meta_reg(.RESETB (1'b1), .SETB (n_5), .CLK (clk), .D
       (cs_n), .Q (cs_meta));
  OR2X1 g795__8246(.A (done_decrypt_latched), .B
       (done_encrypt_latched), .Z (n_165));
  INVX2 g796(.A (rst), .Z (n_5));
  INVX2 g797(.A (transaction_state[0]), .Z (n_6));
  INVX2 drc_bufs808(.A (n_161), .Z (n_162));
  INVX2 drc_bufs810(.A (n_168), .Z (n_161));
  DFFQSRX1 active_reg(.RESETB (n_5), .SETB (1'b1), .CLK (clk), .D
       (n_158), .Q (active));
  DFFQSRX1 \transaction_state_reg[0] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_156), .Q (transaction_state[0]));
  DFFQSRX1 done_decrypt_latched_reg(.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_159), .Q (done_decrypt_latched));
  DFFQSRX1 done_encrypt_latched_reg(.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_160), .Q (done_encrypt_latched));
  DFFQSRX1 \transaction_state_reg[1] (.RESETB (n_5), .SETB (1'b1), .CLK
       (clk), .D (n_157), .Q (transaction_state[1]));
  DFFQSRX1 \data_reg_reg[9] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_91), .Q (data_reg[9]));
  DFFQSRX1 \data_reg_reg[10] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_89), .Q (data_reg[10]));
  DFFQSRX1 \data_reg_reg[11] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_90), .Q (data_reg[11]));
  DFFQSRX1 \key_reg_reg[5] (.RESETB (n_5), .SETB (1'b1), .CLK (clk), .D
       (n_28), .Q (key_reg[5]));
  DFFQSRX1 \key_reg_reg[6] (.RESETB (n_5), .SETB (1'b1), .CLK (clk), .D
       (n_153), .Q (key_reg[6]));
  DFFQSRX1 \key_reg_reg[7] (.RESETB (n_5), .SETB (1'b1), .CLK (clk), .D
       (n_152), .Q (key_reg[7]));
  DFFQSRX1 \key_reg_reg[8] (.RESETB (n_5), .SETB (1'b1), .CLK (clk), .D
       (n_151), .Q (key_reg[8]));
  DFFQSRX1 \key_reg_reg[9] (.RESETB (n_5), .SETB (1'b1), .CLK (clk), .D
       (n_150), .Q (key_reg[9]));
  DFFQSRX1 \key_reg_reg[10] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_149), .Q (key_reg[10]));
  DFFQSRX1 \key_reg_reg[11] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_148), .Q (key_reg[11]));
  DFFQSRX1 \key_reg_reg[12] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_147), .Q (key_reg[12]));
  DFFQSRX1 \data_reg_reg[12] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_88), .Q (data_reg[12]));
  DFFQSRX1 \data_reg_reg[13] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_87), .Q (data_reg[13]));
  DFFQSRX1 \key_reg_reg[13] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_146), .Q (key_reg[13]));
  DFFQSRX1 \key_reg_reg[14] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_145), .Q (key_reg[14]));
  DFFQSRX1 \key_reg_reg[15] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_144), .Q (key_reg[15]));
  DFFQSRX1 \key_reg_reg[16] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_143), .Q (key_reg[16]));
  DFFQSRX1 \data_reg_reg[14] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_86), .Q (data_reg[14]));
  DFFQSRX1 \key_reg_reg[17] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_142), .Q (key_reg[17]));
  DFFQSRX1 \key_reg_reg[18] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_141), .Q (key_reg[18]));
  DFFQSRX1 \data_reg_reg[15] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_85), .Q (data_reg[15]));
  DFFQSRX1 \key_reg_reg[19] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_140), .Q (key_reg[19]));
  DFFQSRX1 \key_reg_reg[20] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_139), .Q (key_reg[20]));
  DFFQSRX1 \data_reg_reg[16] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_84), .Q (data_reg[16]));
  DFFQSRX1 \data_reg_reg[17] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_83), .Q (data_reg[17]));
  DFFQSRX1 \key_reg_reg[21] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_138), .Q (key_reg[21]));
  DFFQSRX1 \key_reg_reg[22] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_137), .Q (key_reg[22]));
  DFFQSRX1 \key_reg_reg[23] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_136), .Q (key_reg[23]));
  DFFQSRX1 \key_reg_reg[24] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_135), .Q (key_reg[24]));
  DFFQSRX1 \data_reg_reg[18] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_82), .Q (data_reg[18]));
  DFFQSRX1 \key_reg_reg[25] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_134), .Q (key_reg[25]));
  DFFQSRX1 \key_reg_reg[26] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_133), .Q (key_reg[26]));
  DFFQSRX1 \data_reg_reg[19] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_81), .Q (data_reg[19]));
  DFFQSRX1 \key_reg_reg[27] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_132), .Q (key_reg[27]));
  DFFQSRX1 \key_reg_reg[28] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_131), .Q (key_reg[28]));
  DFFQSRX1 \data_reg_reg[20] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_79), .Q (data_reg[20]));
  DFFQSRX1 \data_reg_reg[21] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_78), .Q (data_reg[21]));
  DFFQSRX1 \key_reg_reg[29] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_130), .Q (key_reg[29]));
  DFFQSRX1 \key_reg_reg[30] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_129), .Q (key_reg[30]));
  DFFQSRX1 \key_reg_reg[31] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_128), .Q (key_reg[31]));
  DFFQSRX1 \key_reg_reg[32] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_127), .Q (key_reg[32]));
  DFFQSRX1 \data_reg_reg[22] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_77), .Q (data_reg[22]));
  DFFQSRX1 \key_reg_reg[33] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_126), .Q (key_reg[33]));
  DFFQSRX1 \key_reg_reg[34] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_125), .Q (key_reg[34]));
  DFFQSRX1 \data_reg_reg[23] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_76), .Q (data_reg[23]));
  DFFQSRX1 \key_reg_reg[35] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_124), .Q (key_reg[35]));
  DFFQSRX1 \key_reg_reg[36] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_123), .Q (key_reg[36]));
  DFFQSRX1 \data_reg_reg[25] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_72), .Q (data_reg[25]));
  DFFQSRX1 \data_reg_reg[26] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_74), .Q (data_reg[26]));
  DFFQSRX1 \key_reg_reg[37] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_122), .Q (key_reg[37]));
  DFFQSRX1 \key_reg_reg[38] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_121), .Q (key_reg[38]));
  DFFQSRX1 \key_reg_reg[39] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_120), .Q (key_reg[39]));
  DFFQSRX1 \key_reg_reg[40] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_119), .Q (key_reg[40]));
  DFFQSRX1 \data_reg_reg[27] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_73), .Q (data_reg[27]));
  DFFQSRX1 \key_reg_reg[41] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_118), .Q (key_reg[41]));
  DFFQSRX1 \key_reg_reg[42] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_117), .Q (key_reg[42]));
  DFFQSRX1 \key_reg_reg[43] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_116), .Q (key_reg[43]));
  DFFQSRX1 \key_reg_reg[44] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_115), .Q (key_reg[44]));
  DFFQSRX1 \data_reg_reg[28] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_71), .Q (data_reg[28]));
  DFFQSRX1 \data_reg_reg[29] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_70), .Q (data_reg[29]));
  DFFQSRX1 \key_reg_reg[45] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_114), .Q (key_reg[45]));
  DFFQSRX1 \key_reg_reg[46] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_113), .Q (key_reg[46]));
  DFFQSRX1 \key_reg_reg[47] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_112), .Q (key_reg[47]));
  DFFQSRX1 \key_reg_reg[48] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_111), .Q (key_reg[48]));
  DFFQSRX1 \data_reg_reg[30] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_69), .Q (data_reg[30]));
  DFFQSRX1 \key_reg_reg[49] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_110), .Q (key_reg[49]));
  MUX2X1 g815__7098(.A (n_2), .B (done_encrypt_latched), .S (n_22), .Z
       (n_160));
  MUX2X1 g816__6131(.A (n_2), .B (done_decrypt_latched), .S (n_21), .Z
       (n_159));
  MUX2X1 g817__1881(.A (n_10), .B (active), .S (n_25), .Z (n_158));
  MUX2X1 g818__5115(.A (n_13), .B (transaction_state[1]), .S (n_26), .Z
       (n_157));
  XOR2X1 g819__7482(.A (transaction_state[0]), .B (n_27), .Z (n_156));
  DFFQSRX1 \data_reg_reg[33] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_66), .Q (data_reg[33]));
  DFFQSRX1 \key_reg_reg[53] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_106), .Q (key_reg[53]));
  DFFQSRX1 \key_reg_reg[54] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_105), .Q (key_reg[54]));
  DFFQSRX1 \key_reg_reg[55] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_104), .Q (key_reg[55]));
  DFFQSRX1 \key_reg_reg[56] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_103), .Q (key_reg[56]));
  DFFQSRX1 \data_reg_reg[34] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_65), .Q (data_reg[34]));
  DFFQSRX1 \key_reg_reg[57] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_102), .Q (key_reg[57]));
  DFFQSRX1 \key_reg_reg[58] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_101), .Q (key_reg[58]));
  DFFQSRX1 \data_reg_reg[35] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_64), .Q (data_reg[35]));
  DFFQSRX1 \key_reg_reg[59] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_100), .Q (key_reg[59]));
  DFFQSRX1 \key_reg_reg[60] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_99), .Q (key_reg[60]));
  DFFQSRX1 \data_reg_reg[24] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_75), .Q (data_reg[24]));
  DFFQSRX1 \data_reg_reg[37] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_63), .Q (data_reg[37]));
  DFFQSRX1 \key_reg_reg[61] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_98), .Q (key_reg[61]));
  DFFQSRX1 \key_reg_reg[62] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_97), .Q (key_reg[62]));
  DFFQSRX1 \key_reg_reg[63] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_96), .Q (key_reg[63]));
  DFFQSRX1 \data_reg_reg[32] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_68), .Q (data_reg[32]));
  DFFQSRX1 \data_reg_reg[38] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_62), .Q (data_reg[38]));
  DFFQSRX1 \data_reg_reg[36] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_80), .Q (data_reg[36]));
  DFFQSRX1 \data_reg_reg[39] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_61), .Q (data_reg[39]));
  DFFQSRX1 \data_reg_reg[40] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_60), .Q (data_reg[40]));
  DFFQSRX1 \data_reg_reg[41] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_59), .Q (data_reg[41]));
  DFFQSRX1 \data_reg_reg[42] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_58), .Q (data_reg[42]));
  DFFQSRX1 \data_reg_reg[43] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_57), .Q (data_reg[43]));
  DFFQSRX1 \data_reg_reg[44] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_56), .Q (data_reg[44]));
  DFFQSRX1 \data_reg_reg[45] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_55), .Q (data_reg[45]));
  DFFQSRX1 \data_reg_reg[46] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_54), .Q (data_reg[46]));
  DFFQSRX1 \data_reg_reg[47] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_53), .Q (data_reg[47]));
  DFFQSRX1 \key_reg_reg[50] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_109), .Q (key_reg[50]));
  DFFQSRX1 \data_reg_reg[49] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_51), .Q (data_reg[49]));
  DFFQSRX1 \data_reg_reg[50] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_50), .Q (data_reg[50]));
  DFFQSRX1 \data_reg_reg[51] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_49), .Q (data_reg[51]));
  DFFQSRX1 \data_reg_reg[52] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_48), .Q (data_reg[52]));
  DFFQSRX1 \data_reg_reg[53] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_47), .Q (data_reg[53]));
  DFFQSRX1 \data_reg_reg[54] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_45), .Q (data_reg[54]));
  DFFQSRX1 \data_reg_reg[55] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_44), .Q (data_reg[55]));
  DFFQSRX1 \data_reg_reg[2] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_39), .Q (data_reg[2]));
  DFFQSRX1 \data_reg_reg[56] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_43), .Q (data_reg[56]));
  DFFQSRX1 \data_reg_reg[57] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_42), .Q (data_reg[57]));
  DFFQSRX1 \data_reg_reg[58] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_40), .Q (data_reg[58]));
  DFFQSRX1 \data_reg_reg[59] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_38), .Q (data_reg[59]));
  DFFQSRX1 \data_reg_reg[3] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_36), .Q (data_reg[3]));
  DFFQSRX1 \data_reg_reg[60] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_37), .Q (data_reg[60]));
  DFFQSRX1 \data_reg_reg[61] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_35), .Q (data_reg[61]));
  DFFQSRX1 \data_reg_reg[62] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_34), .Q (data_reg[62]));
  DFFQSRX1 \data_reg_reg[63] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_33), .Q (data_reg[63]));
  DFFQSRX1 \data_reg_reg[0] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_46), .Q (data_reg[0]));
  DFFQSRX1 \data_reg_reg[1] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_41), .Q (data_reg[1]));
  DFFQSRX1 \data_reg_reg[5] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_31), .Q (data_reg[5]));
  DFFQSRX1 \data_reg_reg[4] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_32), .Q (data_reg[4]));
  DFFQSRX1 \key_reg_reg[0] (.RESETB (n_5), .SETB (1'b1), .CLK (clk), .D
       (n_95), .Q (key_reg[0]));
  DFFQSRX1 \data_reg_reg[6] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_30), .Q (data_reg[6]));
  DFFQSRX1 \key_reg_reg[1] (.RESETB (n_5), .SETB (1'b1), .CLK (clk), .D
       (n_94), .Q (key_reg[1]));
  DFFQSRX1 \key_reg_reg[2] (.RESETB (n_5), .SETB (1'b1), .CLK (clk), .D
       (n_93), .Q (key_reg[2]));
  DFFQSRX1 \data_reg_reg[7] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_29), .Q (data_reg[7]));
  DFFQSRX1 \key_reg_reg[3] (.RESETB (n_5), .SETB (1'b1), .CLK (clk), .D
       (n_154), .Q (key_reg[3]));
  DFFQSRX1 \key_reg_reg[4] (.RESETB (n_5), .SETB (1'b1), .CLK (clk), .D
       (n_155), .Q (key_reg[4]));
  DFFQSRX1 \data_reg_reg[48] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_52), .Q (data_reg[48]));
  DFFQSRX1 \data_reg_reg[31] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_67), .Q (data_reg[31]));
  DFFQSRX1 \key_reg_reg[51] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_108), .Q (key_reg[51]));
  DFFQSRX1 \key_reg_reg[52] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_107), .Q (key_reg[52]));
  DFFQSRX1 \data_reg_reg[8] (.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_92), .Q (data_reg[8]));
  MUX2X1 g882__4733(.A (spi_rx_data[4]), .B (key_reg[4]), .S (n_2), .Z
       (n_155));
  MUX2X1 g883__6161(.A (spi_rx_data[3]), .B (key_reg[3]), .S (n_2), .Z
       (n_154));
  MUX2X1 g884__9315(.A (spi_rx_data[6]), .B (key_reg[6]), .S (n_2), .Z
       (n_153));
  MUX2X1 g885__9945(.A (spi_rx_data[7]), .B (key_reg[7]), .S (n_16), .Z
       (n_152));
  MUX2X1 g886__2883(.A (spi_rx_data[8]), .B (key_reg[8]), .S (n_16), .Z
       (n_151));
  MUX2X1 g887__2346(.A (spi_rx_data[9]), .B (key_reg[9]), .S (n_16), .Z
       (n_150));
  MUX2X1 g888__1666(.A (spi_rx_data[10]), .B (key_reg[10]), .S (n_2),
       .Z (n_149));
  MUX2X1 g889__7410(.A (spi_rx_data[11]), .B (key_reg[11]), .S (n_2),
       .Z (n_148));
  MUX2X1 g890__6417(.A (spi_rx_data[12]), .B (key_reg[12]), .S (n_2),
       .Z (n_147));
  MUX2X1 g891__5477(.A (spi_rx_data[13]), .B (key_reg[13]), .S (n_16),
       .Z (n_146));
  MUX2X1 g892__2398(.A (spi_rx_data[14]), .B (key_reg[14]), .S (n_16),
       .Z (n_145));
  MUX2X1 g893__5107(.A (spi_rx_data[15]), .B (key_reg[15]), .S (n_2),
       .Z (n_144));
  MUX2X1 g894__6260(.A (spi_rx_data[16]), .B (key_reg[16]), .S (n_16),
       .Z (n_143));
  MUX2X1 g895__4319(.A (spi_rx_data[17]), .B (key_reg[17]), .S (n_2),
       .Z (n_142));
  MUX2X1 g896__8428(.A (spi_rx_data[18]), .B (key_reg[18]), .S (n_2),
       .Z (n_141));
  MUX2X1 g897__5526(.A (spi_rx_data[19]), .B (key_reg[19]), .S (n_16),
       .Z (n_140));
  MUX2X1 g898__6783(.A (spi_rx_data[20]), .B (key_reg[20]), .S (n_16),
       .Z (n_139));
  MUX2X1 g899__3680(.A (spi_rx_data[21]), .B (key_reg[21]), .S (n_16),
       .Z (n_138));
  MUX2X1 g900__1617(.A (spi_rx_data[22]), .B (key_reg[22]), .S (n_2),
       .Z (n_137));
  MUX2X1 g901__2802(.A (spi_rx_data[23]), .B (key_reg[23]), .S (n_16),
       .Z (n_136));
  MUX2X1 g902__1705(.A (spi_rx_data[24]), .B (key_reg[24]), .S (n_2),
       .Z (n_135));
  MUX2X1 g903__5122(.A (spi_rx_data[25]), .B (key_reg[25]), .S (n_2),
       .Z (n_134));
  MUX2X1 g904__8246(.A (spi_rx_data[26]), .B (key_reg[26]), .S (n_2),
       .Z (n_133));
  MUX2X1 g905__7098(.A (spi_rx_data[27]), .B (key_reg[27]), .S (n_2),
       .Z (n_132));
  MUX2X1 g906__6131(.A (spi_rx_data[28]), .B (key_reg[28]), .S (n_2),
       .Z (n_131));
  MUX2X1 g907__1881(.A (spi_rx_data[29]), .B (key_reg[29]), .S (n_2),
       .Z (n_130));
  MUX2X1 g908__5115(.A (spi_rx_data[30]), .B (key_reg[30]), .S (n_2),
       .Z (n_129));
  MUX2X1 g909__7482(.A (spi_rx_data[31]), .B (key_reg[31]), .S (n_2),
       .Z (n_128));
  MUX2X1 g910__4733(.A (spi_rx_data[32]), .B (key_reg[32]), .S (n_2),
       .Z (n_127));
  MUX2X1 g911__6161(.A (spi_rx_data[33]), .B (key_reg[33]), .S (n_2),
       .Z (n_126));
  MUX2X1 g912__9315(.A (spi_rx_data[34]), .B (key_reg[34]), .S (n_2),
       .Z (n_125));
  MUX2X1 g913__9945(.A (spi_rx_data[35]), .B (key_reg[35]), .S (n_2),
       .Z (n_124));
  MUX2X1 g914__2883(.A (spi_rx_data[36]), .B (key_reg[36]), .S (n_2),
       .Z (n_123));
  MUX2X1 g915__2346(.A (spi_rx_data[37]), .B (key_reg[37]), .S (n_2),
       .Z (n_122));
  MUX2X1 g916__1666(.A (spi_rx_data[38]), .B (key_reg[38]), .S (n_16),
       .Z (n_121));
  MUX2X1 g917__7410(.A (spi_rx_data[39]), .B (key_reg[39]), .S (n_16),
       .Z (n_120));
  MUX2X1 g918__6417(.A (spi_rx_data[40]), .B (key_reg[40]), .S (n_2),
       .Z (n_119));
  MUX2X1 g919__5477(.A (spi_rx_data[41]), .B (key_reg[41]), .S (n_2),
       .Z (n_118));
  MUX2X1 g920__2398(.A (spi_rx_data[42]), .B (key_reg[42]), .S (n_2),
       .Z (n_117));
  MUX2X1 g921__5107(.A (spi_rx_data[43]), .B (key_reg[43]), .S (n_2),
       .Z (n_116));
  MUX2X1 g922__6260(.A (spi_rx_data[44]), .B (key_reg[44]), .S (n_2),
       .Z (n_115));
  MUX2X1 g923__4319(.A (spi_rx_data[45]), .B (key_reg[45]), .S (n_16),
       .Z (n_114));
  MUX2X1 g924__8428(.A (spi_rx_data[46]), .B (key_reg[46]), .S (n_2),
       .Z (n_113));
  MUX2X1 g925__5526(.A (spi_rx_data[47]), .B (key_reg[47]), .S (n_2),
       .Z (n_112));
  MUX2X1 g926__6783(.A (spi_rx_data[48]), .B (key_reg[48]), .S (n_2),
       .Z (n_111));
  MUX2X1 g927__3680(.A (spi_rx_data[49]), .B (key_reg[49]), .S (n_2),
       .Z (n_110));
  MUX2X1 g928__1617(.A (spi_rx_data[50]), .B (key_reg[50]), .S (n_2),
       .Z (n_109));
  MUX2X1 g929__2802(.A (spi_rx_data[51]), .B (key_reg[51]), .S (n_2),
       .Z (n_108));
  MUX2X1 g930__1705(.A (spi_rx_data[52]), .B (key_reg[52]), .S (n_2),
       .Z (n_107));
  MUX2X1 g931__5122(.A (spi_rx_data[53]), .B (key_reg[53]), .S (n_2),
       .Z (n_106));
  MUX2X1 g932__8246(.A (spi_rx_data[54]), .B (key_reg[54]), .S (n_2),
       .Z (n_105));
  MUX2X1 g933__7098(.A (spi_rx_data[55]), .B (key_reg[55]), .S (n_2),
       .Z (n_104));
  MUX2X1 g934__6131(.A (spi_rx_data[56]), .B (key_reg[56]), .S (n_2),
       .Z (n_103));
  MUX2X1 g935__1881(.A (spi_rx_data[57]), .B (key_reg[57]), .S (n_2),
       .Z (n_102));
  MUX2X1 g936__5115(.A (spi_rx_data[58]), .B (key_reg[58]), .S (n_2),
       .Z (n_101));
  MUX2X1 g937__7482(.A (spi_rx_data[59]), .B (key_reg[59]), .S (n_2),
       .Z (n_100));
  MUX2X1 g938__4733(.A (spi_rx_data[60]), .B (key_reg[60]), .S (n_2),
       .Z (n_99));
  MUX2X1 g939__6161(.A (spi_rx_data[61]), .B (key_reg[61]), .S (n_2),
       .Z (n_98));
  MUX2X1 g940__9315(.A (spi_rx_data[62]), .B (key_reg[62]), .S (n_16),
       .Z (n_97));
  MUX2X1 g941__9945(.A (spi_rx_data[63]), .B (key_reg[63]), .S (n_2),
       .Z (n_96));
  MUX2X1 g942__2883(.A (spi_rx_data[0]), .B (key_reg[0]), .S (n_2), .Z
       (n_95));
  MUX2X1 g943__2346(.A (spi_rx_data[1]), .B (key_reg[1]), .S (n_2), .Z
       (n_94));
  MUX2X1 g944__1666(.A (spi_rx_data[2]), .B (key_reg[2]), .S (n_2), .Z
       (n_93));
  DFFQSRX1 start_decrypt_reg(.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_23), .Q (start_decrypt));
  DFFQSRX1 start_encrypt_reg(.RESETB (n_5), .SETB (1'b1), .CLK (clk),
       .D (n_24), .Q (start_encrypt));
  MUX2X1 g947__7410(.A (spi_rx_data[8]), .B (data_reg[8]), .S (n_20),
       .Z (n_92));
  MUX2X1 g948__6417(.A (spi_rx_data[9]), .B (data_reg[9]), .S (n_1), .Z
       (n_91));
  MUX2X1 g949__5477(.A (spi_rx_data[11]), .B (data_reg[11]), .S (n_20),
       .Z (n_90));
  MUX2X1 g950__2398(.A (spi_rx_data[10]), .B (data_reg[10]), .S (n_1),
       .Z (n_89));
  MUX2X1 g951__5107(.A (spi_rx_data[12]), .B (data_reg[12]), .S (n_20),
       .Z (n_88));
  MUX2X1 g952__6260(.A (spi_rx_data[13]), .B (data_reg[13]), .S (n_20),
       .Z (n_87));
  MUX2X1 g953__4319(.A (spi_rx_data[14]), .B (data_reg[14]), .S (n_20),
       .Z (n_86));
  MUX2X1 g954__8428(.A (spi_rx_data[15]), .B (data_reg[15]), .S (n_1),
       .Z (n_85));
  MUX2X1 g955__5526(.A (spi_rx_data[16]), .B (data_reg[16]), .S (n_1),
       .Z (n_84));
  MUX2X1 g956__6783(.A (spi_rx_data[17]), .B (data_reg[17]), .S (n_20),
       .Z (n_83));
  MUX2X1 g957__3680(.A (spi_rx_data[18]), .B (data_reg[18]), .S (n_20),
       .Z (n_82));
  MUX2X1 g958__1617(.A (spi_rx_data[19]), .B (data_reg[19]), .S (n_1),
       .Z (n_81));
  MUX2X1 g959__2802(.A (spi_rx_data[36]), .B (data_reg[36]), .S (n_20),
       .Z (n_80));
  MUX2X1 g960__1705(.A (spi_rx_data[20]), .B (data_reg[20]), .S (n_1),
       .Z (n_79));
  MUX2X1 g961__5122(.A (spi_rx_data[21]), .B (data_reg[21]), .S (n_1),
       .Z (n_78));
  MUX2X1 g962__8246(.A (spi_rx_data[22]), .B (data_reg[22]), .S (n_20),
       .Z (n_77));
  MUX2X1 g963__7098(.A (spi_rx_data[23]), .B (data_reg[23]), .S (n_20),
       .Z (n_76));
  MUX2X1 g964__6131(.A (spi_rx_data[24]), .B (data_reg[24]), .S (n_20),
       .Z (n_75));
  MUX2X1 g965__1881(.A (spi_rx_data[26]), .B (data_reg[26]), .S (n_20),
       .Z (n_74));
  MUX2X1 g966__5115(.A (spi_rx_data[27]), .B (data_reg[27]), .S (n_1),
       .Z (n_73));
  MUX2X1 g967__7482(.A (spi_rx_data[25]), .B (data_reg[25]), .S (n_1),
       .Z (n_72));
  MUX2X1 g968__4733(.A (spi_rx_data[28]), .B (data_reg[28]), .S (n_1),
       .Z (n_71));
  MUX2X1 g969__6161(.A (spi_rx_data[29]), .B (data_reg[29]), .S (n_1),
       .Z (n_70));
  MUX2X1 g970__9315(.A (spi_rx_data[30]), .B (data_reg[30]), .S (n_20),
       .Z (n_69));
  MUX2X1 g971__9945(.A (spi_rx_data[32]), .B (data_reg[32]), .S (n_1),
       .Z (n_68));
  MUX2X1 g972__2883(.A (spi_rx_data[31]), .B (data_reg[31]), .S (n_1),
       .Z (n_67));
  MUX2X1 g973__2346(.A (spi_rx_data[33]), .B (data_reg[33]), .S (n_1),
       .Z (n_66));
  MUX2X1 g974__1666(.A (spi_rx_data[34]), .B (data_reg[34]), .S (n_1),
       .Z (n_65));
  MUX2X1 g975__7410(.A (spi_rx_data[35]), .B (data_reg[35]), .S (n_1),
       .Z (n_64));
  MUX2X1 g976__6417(.A (spi_rx_data[37]), .B (data_reg[37]), .S (n_1),
       .Z (n_63));
  MUX2X1 g977__5477(.A (spi_rx_data[38]), .B (data_reg[38]), .S (n_1),
       .Z (n_62));
  MUX2X1 g978__2398(.A (spi_rx_data[39]), .B (data_reg[39]), .S (n_1),
       .Z (n_61));
  MUX2X1 g979__5107(.A (spi_rx_data[40]), .B (data_reg[40]), .S (n_1),
       .Z (n_60));
  MUX2X1 g980__6260(.A (spi_rx_data[41]), .B (data_reg[41]), .S (n_1),
       .Z (n_59));
  MUX2X1 g981__4319(.A (spi_rx_data[42]), .B (data_reg[42]), .S (n_20),
       .Z (n_58));
  MUX2X1 g982__8428(.A (spi_rx_data[43]), .B (data_reg[43]), .S (n_1),
       .Z (n_57));
  MUX2X1 g983__5526(.A (spi_rx_data[44]), .B (data_reg[44]), .S (n_1),
       .Z (n_56));
  MUX2X1 g984__6783(.A (spi_rx_data[45]), .B (data_reg[45]), .S (n_20),
       .Z (n_55));
  MUX2X1 g985__3680(.A (spi_rx_data[46]), .B (data_reg[46]), .S (n_1),
       .Z (n_54));
  MUX2X1 g986__1617(.A (spi_rx_data[47]), .B (data_reg[47]), .S (n_1),
       .Z (n_53));
  MUX2X1 g987__2802(.A (spi_rx_data[48]), .B (data_reg[48]), .S (n_20),
       .Z (n_52));
  MUX2X1 g988__1705(.A (spi_rx_data[49]), .B (data_reg[49]), .S (n_1),
       .Z (n_51));
  MUX2X1 g989__5122(.A (spi_rx_data[50]), .B (data_reg[50]), .S (n_1),
       .Z (n_50));
  MUX2X1 g990__8246(.A (spi_rx_data[51]), .B (data_reg[51]), .S (n_1),
       .Z (n_49));
  MUX2X1 g991__7098(.A (spi_rx_data[52]), .B (data_reg[52]), .S (n_1),
       .Z (n_48));
  MUX2X1 g992__6131(.A (spi_rx_data[53]), .B (data_reg[53]), .S (n_1),
       .Z (n_47));
  MUX2X1 g993__1881(.A (spi_rx_data[0]), .B (data_reg[0]), .S (n_1), .Z
       (n_46));
  MUX2X1 g994__5115(.A (spi_rx_data[54]), .B (data_reg[54]), .S (n_1),
       .Z (n_45));
  MUX2X1 g995__7482(.A (spi_rx_data[55]), .B (data_reg[55]), .S (n_1),
       .Z (n_44));
  MUX2X1 g996__4733(.A (spi_rx_data[56]), .B (data_reg[56]), .S (n_1),
       .Z (n_43));
  MUX2X1 g997__6161(.A (spi_rx_data[57]), .B (data_reg[57]), .S (n_1),
       .Z (n_42));
  MUX2X1 g998__9315(.A (spi_rx_data[1]), .B (data_reg[1]), .S (n_1), .Z
       (n_41));
  MUX2X1 g999__9945(.A (spi_rx_data[58]), .B (data_reg[58]), .S (n_1),
       .Z (n_40));
  MUX2X1 g1000__2883(.A (spi_rx_data[2]), .B (data_reg[2]), .S (n_1),
       .Z (n_39));
  MUX2X1 g1001__2346(.A (spi_rx_data[59]), .B (data_reg[59]), .S (n_1),
       .Z (n_38));
  MUX2X1 g1002__1666(.A (spi_rx_data[60]), .B (data_reg[60]), .S (n_1),
       .Z (n_37));
  MUX2X1 g1003__7410(.A (spi_rx_data[3]), .B (data_reg[3]), .S (n_1),
       .Z (n_36));
  MUX2X1 g1004__6417(.A (spi_rx_data[61]), .B (data_reg[61]), .S (n_1),
       .Z (n_35));
  MUX2X1 g1005__5477(.A (spi_rx_data[62]), .B (data_reg[62]), .S (n_1),
       .Z (n_34));
  MUX2X1 g1006__2398(.A (spi_rx_data[63]), .B (data_reg[63]), .S (n_1),
       .Z (n_33));
  MUX2X1 g1007__5107(.A (spi_rx_data[4]), .B (data_reg[4]), .S (n_1),
       .Z (n_32));
  MUX2X1 g1008__6260(.A (spi_rx_data[5]), .B (data_reg[5]), .S (n_1),
       .Z (n_31));
  MUX2X1 g1009__4319(.A (spi_rx_data[6]), .B (data_reg[6]), .S (n_1),
       .Z (n_30));
  MUX2X1 g1010__8428(.A (spi_rx_data[7]), .B (data_reg[7]), .S (n_1),
       .Z (n_29));
  MUX2X1 g1011__5526(.A (spi_rx_data[5]), .B (key_reg[5]), .S (n_16),
       .Z (n_28));
  INVX2 g1012(.A (n_26), .Z (n_27));
  NOR2X1 g1013__6783(.A (done_encrypt), .B (n_19), .Z (n_25));
  DFFQSRX1 crypt_reg(.RESETB (n_5), .SETB (1'b1), .CLK (clk), .D
       (n_15), .Q (crypt));
  NAND2X1 g1015__3680(.A (n_14), .B (cs_rise_delayed), .Z (n_26));
  NOR2X1 g1016__1617(.A (active), .B (n_17), .Z (n_24));
  NOR2X1 g1017__2802(.A (active), .B (n_18), .Z (n_23));
  NOR2X1 g1018__1705(.A (done_encrypt), .B (n_3), .Z (n_22));
  NOR2X1 g1019__5122(.A (done_decrypt), .B (n_3), .Z (n_21));
  OR2X1 g1020__8246(.A (done_decrypt), .B (n_10), .Z (n_19));
  NAND2X1 g1021__7098(.A (n_9), .B (trigger_operation), .Z (n_18));
  NAND2X1 g1022__6131(.A (n_11), .B (trigger_operation), .Z (n_17));
  OR2X1 g1023__1881(.A (n_6), .B (n_12), .Z (n_20));
  MUX2X1 g1025__5115(.A (crypt), .B (spi_rx_data[0]), .S (n_235), .Z
       (n_15));
  NAND3X1 g1026__7482(.A (transaction_state[0]), .B
       (transaction_state[1]), .C (active), .Z (n_14));
  XOR2X1 g1027__4733(.A (transaction_state[0]), .B
       (transaction_state[1]), .Z (n_13));
  OR2X1 g1028__6161(.A (transaction_state[0]), .B (n_12), .Z (n_16));
  NAND2X1 g1029__9315(.A (n_8), .B (crypt), .Z (n_11));
  NAND2X1 g1030__9945(.A (n_7), .B (cs_rise_delayed), .Z (n_12));
  OR2X1 g1031__2883(.A (crypt), .B (start_decrypt), .Z (n_9));
  OR2X1 g1032__2346(.A (start_encrypt), .B (start_decrypt), .Z (n_10));
  INVX2 g1033(.A (start_encrypt), .Z (n_8));
  INVX2 g1034(.A (transaction_state[1]), .Z (n_7));
  INVX4 drc_bufs1048(.A (n_3), .Z (n_2));
  INVX2 drc_bufs1049(.A (n_16), .Z (n_3));
  INVX4 drc_bufs1059(.A (n_0), .Z (n_1));
  INVX2 drc_bufs1062(.A (n_20), .Z (n_0));
endmodule

module top_pad(clk, rst, sclk, cs_n, mosi, miso);
  input clk, rst, sclk, cs_n, mosi;
  output miso;
  wire clk, rst, sclk, cs_n, mosi;
  wire miso;
  wire clk_PAD, cs_n_PAD, miso_PAD, mosi_PAD, rst_PAD, sclk_PAD;
  pad_in clk_pad(.pad (clk), .DataIn (clk_PAD));
  TopModule core(.clk (clk_PAD), .rst (rst_PAD), .sclk (sclk_PAD),
       .cs_n (cs_n_PAD), .mosi (mosi_PAD), .miso (miso_PAD));
  pad_in cs_n_pad(.pad (cs_n), .DataIn (cs_n_PAD));
  pad_out miso_pad(.pad (miso), .DataOut (miso_PAD));
  pad_in mosi_pad(.pad (mosi), .DataIn (mosi_PAD));
  pad_in rst_pad(.pad (rst), .DataIn (rst_PAD));
  pad_in sclk_pad(.pad (sclk), .DataIn (sclk_PAD));
endmodule

