`timescale 1ns / 1ps

module tb_Feistel_SimpleCase;
      	reg  [31:0] R_in;	// right half input after initial permutation
      	reg  [47:0] subkey;	// generated by subkey generator module
      	wire [31:0] f_out;	// f function output

      	Feistel_Function DUT (.R_in(R_in), .subkey(subkey), .f_out(f_out));

      	initial begin
		// DES Round 1 test
		R_in = 32'hF0AAF0AA;
		subkey = 48'h1B02EFFC7072;
          	#10;
          	if (f_out == 32'h00EF5700)
              	$display("PASS: f_out = %h", f_out);
          	else
              	$display("FAIL: f_out = %h (expected 00EF5700)", f_out);
      	end
  endmodule 
