
//input ports
add mapped point clk clk -type PI PI
add mapped point rst rst -type PI PI
add mapped point sclk sclk -type PI PI
add mapped point cs_n cs_n -type PI PI
add mapped point mosi mosi -type PI PI

//output ports
add mapped point miso miso -type PO PO

//inout ports




//Sequential Pins
add mapped point core/cs_meta_reg/Q core/cs_meta_reg/Q -type DFF DFF
add mapped point core/cs_prev_reg/Q core/cs_prev_reg/Q -type DFF DFF
add mapped point core/cs_rise_delayed_reg/Q core/cs_rise_delayed_reg/Q -type DFF DFF
add mapped point core/cs_sync_reg/Q core/cs_sync_reg/Q -type DFF DFF
add mapped point core/spi_inst_miso_q_reg/Q core/spi_inst_miso_q_reg/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[1]/Q core/spi_inst_shreg_out_reg[1]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[2]/Q core/spi_inst_shreg_out_reg[2]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[3]/Q core/spi_inst_shreg_out_reg[3]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[4]/Q core/spi_inst_shreg_out_reg[4]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[5]/Q core/spi_inst_shreg_out_reg[5]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[6]/Q core/spi_inst_shreg_out_reg[6]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[7]/Q core/spi_inst_shreg_out_reg[7]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[8]/Q core/spi_inst_shreg_out_reg[8]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[9]/Q core/spi_inst_shreg_out_reg[9]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[10]/Q core/spi_inst_shreg_out_reg[10]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[11]/Q core/spi_inst_shreg_out_reg[11]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[12]/Q core/spi_inst_shreg_out_reg[12]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[13]/Q core/spi_inst_shreg_out_reg[13]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[14]/Q core/spi_inst_shreg_out_reg[14]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[15]/Q core/spi_inst_shreg_out_reg[15]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[16]/Q core/spi_inst_shreg_out_reg[16]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[17]/Q core/spi_inst_shreg_out_reg[17]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[18]/Q core/spi_inst_shreg_out_reg[18]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[19]/Q core/spi_inst_shreg_out_reg[19]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[20]/Q core/spi_inst_shreg_out_reg[20]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[21]/Q core/spi_inst_shreg_out_reg[21]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[22]/Q core/spi_inst_shreg_out_reg[22]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[23]/Q core/spi_inst_shreg_out_reg[23]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[24]/Q core/spi_inst_shreg_out_reg[24]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[25]/Q core/spi_inst_shreg_out_reg[25]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[26]/Q core/spi_inst_shreg_out_reg[26]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[27]/Q core/spi_inst_shreg_out_reg[27]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[28]/Q core/spi_inst_shreg_out_reg[28]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[29]/Q core/spi_inst_shreg_out_reg[29]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[30]/Q core/spi_inst_shreg_out_reg[30]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[31]/Q core/spi_inst_shreg_out_reg[31]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[32]/Q core/spi_inst_shreg_out_reg[32]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[33]/Q core/spi_inst_shreg_out_reg[33]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[34]/Q core/spi_inst_shreg_out_reg[34]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[35]/Q core/spi_inst_shreg_out_reg[35]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[36]/Q core/spi_inst_shreg_out_reg[36]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[37]/Q core/spi_inst_shreg_out_reg[37]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[38]/Q core/spi_inst_shreg_out_reg[38]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[39]/Q core/spi_inst_shreg_out_reg[39]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[40]/Q core/spi_inst_shreg_out_reg[40]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[41]/Q core/spi_inst_shreg_out_reg[41]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[42]/Q core/spi_inst_shreg_out_reg[42]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[43]/Q core/spi_inst_shreg_out_reg[43]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[44]/Q core/spi_inst_shreg_out_reg[44]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[45]/Q core/spi_inst_shreg_out_reg[45]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[46]/Q core/spi_inst_shreg_out_reg[46]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[47]/Q core/spi_inst_shreg_out_reg[47]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[48]/Q core/spi_inst_shreg_out_reg[48]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[49]/Q core/spi_inst_shreg_out_reg[49]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[50]/Q core/spi_inst_shreg_out_reg[50]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[51]/Q core/spi_inst_shreg_out_reg[51]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[52]/Q core/spi_inst_shreg_out_reg[52]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[53]/Q core/spi_inst_shreg_out_reg[53]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[54]/Q core/spi_inst_shreg_out_reg[54]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[55]/Q core/spi_inst_shreg_out_reg[55]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[56]/Q core/spi_inst_shreg_out_reg[56]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[57]/Q core/spi_inst_shreg_out_reg[57]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[58]/Q core/spi_inst_shreg_out_reg[58]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[59]/Q core/spi_inst_shreg_out_reg[59]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[60]/Q core/spi_inst_shreg_out_reg[60]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[61]/Q core/spi_inst_shreg_out_reg[61]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[62]/Q core/spi_inst_shreg_out_reg[62]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_out_reg[63]/Q core/spi_inst_shreg_out_reg[63]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[0]/Q core/spi_tx_data_reg[0]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[1]/Q core/spi_tx_data_reg[1]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[2]/Q core/spi_tx_data_reg[2]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[3]/Q core/spi_tx_data_reg[3]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[4]/Q core/spi_tx_data_reg[4]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[5]/Q core/spi_tx_data_reg[5]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[6]/Q core/spi_tx_data_reg[6]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[7]/Q core/spi_tx_data_reg[7]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[8]/Q core/spi_tx_data_reg[8]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[9]/Q core/spi_tx_data_reg[9]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[10]/Q core/spi_tx_data_reg[10]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[11]/Q core/spi_tx_data_reg[11]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[12]/Q core/spi_tx_data_reg[12]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[13]/Q core/spi_tx_data_reg[13]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[14]/Q core/spi_tx_data_reg[14]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[15]/Q core/spi_tx_data_reg[15]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[16]/Q core/spi_tx_data_reg[16]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[17]/Q core/spi_tx_data_reg[17]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[18]/Q core/spi_tx_data_reg[18]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[19]/Q core/spi_tx_data_reg[19]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[20]/Q core/spi_tx_data_reg[20]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[21]/Q core/spi_tx_data_reg[21]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[22]/Q core/spi_tx_data_reg[22]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[23]/Q core/spi_tx_data_reg[23]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[24]/Q core/spi_tx_data_reg[24]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[25]/Q core/spi_tx_data_reg[25]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[26]/Q core/spi_tx_data_reg[26]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[27]/Q core/spi_tx_data_reg[27]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[28]/Q core/spi_tx_data_reg[28]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[29]/Q core/spi_tx_data_reg[29]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[30]/Q core/spi_tx_data_reg[30]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[31]/Q core/spi_tx_data_reg[31]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[32]/Q core/spi_tx_data_reg[32]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[33]/Q core/spi_tx_data_reg[33]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[34]/Q core/spi_tx_data_reg[34]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[35]/Q core/spi_tx_data_reg[35]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[36]/Q core/spi_tx_data_reg[36]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[37]/Q core/spi_tx_data_reg[37]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[38]/Q core/spi_tx_data_reg[38]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[39]/Q core/spi_tx_data_reg[39]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[40]/Q core/spi_tx_data_reg[40]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[41]/Q core/spi_tx_data_reg[41]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[42]/Q core/spi_tx_data_reg[42]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[43]/Q core/spi_tx_data_reg[43]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[44]/Q core/spi_tx_data_reg[44]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[45]/Q core/spi_tx_data_reg[45]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[46]/Q core/spi_tx_data_reg[46]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[47]/Q core/spi_tx_data_reg[47]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[48]/Q core/spi_tx_data_reg[48]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[49]/Q core/spi_tx_data_reg[49]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[50]/Q core/spi_tx_data_reg[50]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[51]/Q core/spi_tx_data_reg[51]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[52]/Q core/spi_tx_data_reg[52]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[53]/Q core/spi_tx_data_reg[53]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[54]/Q core/spi_tx_data_reg[54]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[55]/Q core/spi_tx_data_reg[55]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[56]/Q core/spi_tx_data_reg[56]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[57]/Q core/spi_tx_data_reg[57]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[58]/Q core/spi_tx_data_reg[58]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[59]/Q core/spi_tx_data_reg[59]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[60]/Q core/spi_tx_data_reg[60]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[61]/Q core/spi_tx_data_reg[61]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[62]/Q core/spi_tx_data_reg[62]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[63]/Q core/spi_tx_data_reg[63]/Q -type DFF DFF
add mapped point core/trigger_operation_reg/Q core/trigger_operation_reg/Q -type DFF DFF
add mapped point core/active_reg/Q core/active_reg/Q -type DFF DFF
add mapped point core/crypt_reg/Q core/crypt_reg/Q -type DFF DFF
add mapped point core/csm_inst_done_decrypt_reg/Q core/csm_inst_done_decrypt_reg/Q -type DFF DFF
add mapped point core/csm_inst_done_encrypt_reg/Q core/csm_inst_done_encrypt_reg/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[0]/Q core/csm_inst_left_reg_reg[0]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[1]/Q core/csm_inst_left_reg_reg[1]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[2]/Q core/csm_inst_left_reg_reg[2]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[3]/Q core/csm_inst_left_reg_reg[3]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[4]/Q core/csm_inst_left_reg_reg[4]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[5]/Q core/csm_inst_left_reg_reg[5]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[6]/Q core/csm_inst_left_reg_reg[6]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[7]/Q core/csm_inst_left_reg_reg[7]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[8]/Q core/csm_inst_left_reg_reg[8]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[9]/Q core/csm_inst_left_reg_reg[9]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[10]/Q core/csm_inst_left_reg_reg[10]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[11]/Q core/csm_inst_left_reg_reg[11]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[12]/Q core/csm_inst_left_reg_reg[12]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[13]/Q core/csm_inst_left_reg_reg[13]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[14]/Q core/csm_inst_left_reg_reg[14]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[15]/Q core/csm_inst_left_reg_reg[15]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[16]/Q core/csm_inst_left_reg_reg[16]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[17]/Q core/csm_inst_left_reg_reg[17]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[18]/Q core/csm_inst_left_reg_reg[18]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[19]/Q core/csm_inst_left_reg_reg[19]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[20]/Q core/csm_inst_left_reg_reg[20]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[21]/Q core/csm_inst_left_reg_reg[21]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[22]/Q core/csm_inst_left_reg_reg[22]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[23]/Q core/csm_inst_left_reg_reg[23]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[24]/Q core/csm_inst_left_reg_reg[24]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[25]/Q core/csm_inst_left_reg_reg[25]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[26]/Q core/csm_inst_left_reg_reg[26]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[27]/Q core/csm_inst_left_reg_reg[27]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[28]/Q core/csm_inst_left_reg_reg[28]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[29]/Q core/csm_inst_left_reg_reg[29]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[30]/Q core/csm_inst_left_reg_reg[30]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[31]/Q core/csm_inst_left_reg_reg[31]/Q -type DFF DFF
add mapped point core/csm_inst_mode_reg/Q core/csm_inst_mode_reg/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[0]/Q core/csm_inst_output_text_reg[0]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[1]/Q core/csm_inst_output_text_reg[1]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[2]/Q core/csm_inst_output_text_reg[2]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[3]/Q core/csm_inst_output_text_reg[3]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[4]/Q core/csm_inst_output_text_reg[4]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[5]/Q core/csm_inst_output_text_reg[5]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[6]/Q core/csm_inst_output_text_reg[6]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[7]/Q core/csm_inst_output_text_reg[7]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[8]/Q core/csm_inst_output_text_reg[8]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[9]/Q core/csm_inst_output_text_reg[9]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[10]/Q core/csm_inst_output_text_reg[10]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[11]/Q core/csm_inst_output_text_reg[11]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[12]/Q core/csm_inst_output_text_reg[12]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[13]/Q core/csm_inst_output_text_reg[13]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[14]/Q core/csm_inst_output_text_reg[14]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[15]/Q core/csm_inst_output_text_reg[15]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[16]/Q core/csm_inst_output_text_reg[16]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[17]/Q core/csm_inst_output_text_reg[17]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[18]/Q core/csm_inst_output_text_reg[18]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[19]/Q core/csm_inst_output_text_reg[19]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[20]/Q core/csm_inst_output_text_reg[20]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[21]/Q core/csm_inst_output_text_reg[21]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[22]/Q core/csm_inst_output_text_reg[22]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[23]/Q core/csm_inst_output_text_reg[23]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[24]/Q core/csm_inst_output_text_reg[24]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[25]/Q core/csm_inst_output_text_reg[25]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[26]/Q core/csm_inst_output_text_reg[26]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[27]/Q core/csm_inst_output_text_reg[27]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[28]/Q core/csm_inst_output_text_reg[28]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[29]/Q core/csm_inst_output_text_reg[29]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[30]/Q core/csm_inst_output_text_reg[30]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[31]/Q core/csm_inst_output_text_reg[31]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[32]/Q core/csm_inst_output_text_reg[32]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[33]/Q core/csm_inst_output_text_reg[33]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[34]/Q core/csm_inst_output_text_reg[34]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[35]/Q core/csm_inst_output_text_reg[35]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[36]/Q core/csm_inst_output_text_reg[36]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[37]/Q core/csm_inst_output_text_reg[37]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[38]/Q core/csm_inst_output_text_reg[38]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[39]/Q core/csm_inst_output_text_reg[39]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[40]/Q core/csm_inst_output_text_reg[40]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[41]/Q core/csm_inst_output_text_reg[41]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[42]/Q core/csm_inst_output_text_reg[42]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[43]/Q core/csm_inst_output_text_reg[43]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[44]/Q core/csm_inst_output_text_reg[44]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[45]/Q core/csm_inst_output_text_reg[45]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[46]/Q core/csm_inst_output_text_reg[46]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[47]/Q core/csm_inst_output_text_reg[47]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[48]/Q core/csm_inst_output_text_reg[48]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[49]/Q core/csm_inst_output_text_reg[49]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[50]/Q core/csm_inst_output_text_reg[50]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[51]/Q core/csm_inst_output_text_reg[51]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[52]/Q core/csm_inst_output_text_reg[52]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[53]/Q core/csm_inst_output_text_reg[53]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[54]/Q core/csm_inst_output_text_reg[54]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[55]/Q core/csm_inst_output_text_reg[55]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[56]/Q core/csm_inst_output_text_reg[56]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[57]/Q core/csm_inst_output_text_reg[57]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[58]/Q core/csm_inst_output_text_reg[58]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[59]/Q core/csm_inst_output_text_reg[59]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[60]/Q core/csm_inst_output_text_reg[60]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[61]/Q core/csm_inst_output_text_reg[61]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[62]/Q core/csm_inst_output_text_reg[62]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[63]/Q core/csm_inst_output_text_reg[63]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[0]/Q core/csm_inst_right_reg_reg[0]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[1]/Q core/csm_inst_right_reg_reg[1]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[2]/Q core/csm_inst_right_reg_reg[2]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[3]/Q core/csm_inst_right_reg_reg[3]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[4]/Q core/csm_inst_right_reg_reg[4]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[5]/Q core/csm_inst_right_reg_reg[5]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[6]/Q core/csm_inst_right_reg_reg[6]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[7]/Q core/csm_inst_right_reg_reg[7]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[8]/Q core/csm_inst_right_reg_reg[8]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[9]/Q core/csm_inst_right_reg_reg[9]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[10]/Q core/csm_inst_right_reg_reg[10]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[11]/Q core/csm_inst_right_reg_reg[11]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[12]/Q core/csm_inst_right_reg_reg[12]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[13]/Q core/csm_inst_right_reg_reg[13]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[14]/Q core/csm_inst_right_reg_reg[14]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[15]/Q core/csm_inst_right_reg_reg[15]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[16]/Q core/csm_inst_right_reg_reg[16]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[17]/Q core/csm_inst_right_reg_reg[17]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[18]/Q core/csm_inst_right_reg_reg[18]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[19]/Q core/csm_inst_right_reg_reg[19]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[20]/Q core/csm_inst_right_reg_reg[20]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[21]/Q core/csm_inst_right_reg_reg[21]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[22]/Q core/csm_inst_right_reg_reg[22]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[23]/Q core/csm_inst_right_reg_reg[23]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[24]/Q core/csm_inst_right_reg_reg[24]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[25]/Q core/csm_inst_right_reg_reg[25]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[26]/Q core/csm_inst_right_reg_reg[26]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[27]/Q core/csm_inst_right_reg_reg[27]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[28]/Q core/csm_inst_right_reg_reg[28]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[29]/Q core/csm_inst_right_reg_reg[29]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[30]/Q core/csm_inst_right_reg_reg[30]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[31]/Q core/csm_inst_right_reg_reg[31]/Q -type DFF DFF
add mapped point core/csm_inst_round_counter_reg[0]/Q core/csm_inst_round_counter_reg[0]/Q -type DFF DFF
add mapped point core/csm_inst_round_counter_reg[1]/Q core/csm_inst_round_counter_reg[1]/Q -type DFF DFF
add mapped point core/csm_inst_round_counter_reg[2]/Q core/csm_inst_round_counter_reg[2]/Q -type DFF DFF
add mapped point core/csm_inst_round_counter_reg[3]/Q core/csm_inst_round_counter_reg[3]/Q -type DFF DFF
add mapped point core/csm_inst_state_reg[0]/Q core/csm_inst_state_reg[0]/Q -type DFF DFF
add mapped point core/csm_inst_state_reg[1]/Q core/csm_inst_state_reg[1]/Q -type DFF DFF
add mapped point core/csm_inst_state_reg[2]/Q core/csm_inst_state_reg[2]/Q -type DFF DFF
add mapped point core/data_reg_reg[0]/Q core/data_reg_reg[0]/Q -type DFF DFF
add mapped point core/data_reg_reg[1]/Q core/data_reg_reg[1]/Q -type DFF DFF
add mapped point core/data_reg_reg[2]/Q core/data_reg_reg[2]/Q -type DFF DFF
add mapped point core/data_reg_reg[3]/Q core/data_reg_reg[3]/Q -type DFF DFF
add mapped point core/data_reg_reg[4]/Q core/data_reg_reg[4]/Q -type DFF DFF
add mapped point core/data_reg_reg[5]/Q core/data_reg_reg[5]/Q -type DFF DFF
add mapped point core/data_reg_reg[6]/Q core/data_reg_reg[6]/Q -type DFF DFF
add mapped point core/data_reg_reg[7]/Q core/data_reg_reg[7]/Q -type DFF DFF
add mapped point core/data_reg_reg[8]/Q core/data_reg_reg[8]/Q -type DFF DFF
add mapped point core/data_reg_reg[9]/Q core/data_reg_reg[9]/Q -type DFF DFF
add mapped point core/data_reg_reg[10]/Q core/data_reg_reg[10]/Q -type DFF DFF
add mapped point core/data_reg_reg[11]/Q core/data_reg_reg[11]/Q -type DFF DFF
add mapped point core/data_reg_reg[12]/Q core/data_reg_reg[12]/Q -type DFF DFF
add mapped point core/data_reg_reg[13]/Q core/data_reg_reg[13]/Q -type DFF DFF
add mapped point core/data_reg_reg[14]/Q core/data_reg_reg[14]/Q -type DFF DFF
add mapped point core/data_reg_reg[15]/Q core/data_reg_reg[15]/Q -type DFF DFF
add mapped point core/data_reg_reg[16]/Q core/data_reg_reg[16]/Q -type DFF DFF
add mapped point core/data_reg_reg[17]/Q core/data_reg_reg[17]/Q -type DFF DFF
add mapped point core/data_reg_reg[18]/Q core/data_reg_reg[18]/Q -type DFF DFF
add mapped point core/data_reg_reg[19]/Q core/data_reg_reg[19]/Q -type DFF DFF
add mapped point core/data_reg_reg[20]/Q core/data_reg_reg[20]/Q -type DFF DFF
add mapped point core/data_reg_reg[21]/Q core/data_reg_reg[21]/Q -type DFF DFF
add mapped point core/data_reg_reg[22]/Q core/data_reg_reg[22]/Q -type DFF DFF
add mapped point core/data_reg_reg[23]/Q core/data_reg_reg[23]/Q -type DFF DFF
add mapped point core/data_reg_reg[24]/Q core/data_reg_reg[24]/Q -type DFF DFF
add mapped point core/data_reg_reg[25]/Q core/data_reg_reg[25]/Q -type DFF DFF
add mapped point core/data_reg_reg[26]/Q core/data_reg_reg[26]/Q -type DFF DFF
add mapped point core/data_reg_reg[27]/Q core/data_reg_reg[27]/Q -type DFF DFF
add mapped point core/data_reg_reg[28]/Q core/data_reg_reg[28]/Q -type DFF DFF
add mapped point core/data_reg_reg[29]/Q core/data_reg_reg[29]/Q -type DFF DFF
add mapped point core/data_reg_reg[30]/Q core/data_reg_reg[30]/Q -type DFF DFF
add mapped point core/data_reg_reg[31]/Q core/data_reg_reg[31]/Q -type DFF DFF
add mapped point core/data_reg_reg[32]/Q core/data_reg_reg[32]/Q -type DFF DFF
add mapped point core/data_reg_reg[33]/Q core/data_reg_reg[33]/Q -type DFF DFF
add mapped point core/data_reg_reg[34]/Q core/data_reg_reg[34]/Q -type DFF DFF
add mapped point core/data_reg_reg[35]/Q core/data_reg_reg[35]/Q -type DFF DFF
add mapped point core/data_reg_reg[36]/Q core/data_reg_reg[36]/Q -type DFF DFF
add mapped point core/data_reg_reg[37]/Q core/data_reg_reg[37]/Q -type DFF DFF
add mapped point core/data_reg_reg[38]/Q core/data_reg_reg[38]/Q -type DFF DFF
add mapped point core/data_reg_reg[39]/Q core/data_reg_reg[39]/Q -type DFF DFF
add mapped point core/data_reg_reg[40]/Q core/data_reg_reg[40]/Q -type DFF DFF
add mapped point core/data_reg_reg[41]/Q core/data_reg_reg[41]/Q -type DFF DFF
add mapped point core/data_reg_reg[42]/Q core/data_reg_reg[42]/Q -type DFF DFF
add mapped point core/data_reg_reg[43]/Q core/data_reg_reg[43]/Q -type DFF DFF
add mapped point core/data_reg_reg[44]/Q core/data_reg_reg[44]/Q -type DFF DFF
add mapped point core/data_reg_reg[45]/Q core/data_reg_reg[45]/Q -type DFF DFF
add mapped point core/data_reg_reg[46]/Q core/data_reg_reg[46]/Q -type DFF DFF
add mapped point core/data_reg_reg[47]/Q core/data_reg_reg[47]/Q -type DFF DFF
add mapped point core/data_reg_reg[48]/Q core/data_reg_reg[48]/Q -type DFF DFF
add mapped point core/data_reg_reg[49]/Q core/data_reg_reg[49]/Q -type DFF DFF
add mapped point core/data_reg_reg[50]/Q core/data_reg_reg[50]/Q -type DFF DFF
add mapped point core/data_reg_reg[51]/Q core/data_reg_reg[51]/Q -type DFF DFF
add mapped point core/data_reg_reg[52]/Q core/data_reg_reg[52]/Q -type DFF DFF
add mapped point core/data_reg_reg[53]/Q core/data_reg_reg[53]/Q -type DFF DFF
add mapped point core/data_reg_reg[54]/Q core/data_reg_reg[54]/Q -type DFF DFF
add mapped point core/data_reg_reg[55]/Q core/data_reg_reg[55]/Q -type DFF DFF
add mapped point core/data_reg_reg[56]/Q core/data_reg_reg[56]/Q -type DFF DFF
add mapped point core/data_reg_reg[57]/Q core/data_reg_reg[57]/Q -type DFF DFF
add mapped point core/data_reg_reg[58]/Q core/data_reg_reg[58]/Q -type DFF DFF
add mapped point core/data_reg_reg[59]/Q core/data_reg_reg[59]/Q -type DFF DFF
add mapped point core/data_reg_reg[60]/Q core/data_reg_reg[60]/Q -type DFF DFF
add mapped point core/data_reg_reg[61]/Q core/data_reg_reg[61]/Q -type DFF DFF
add mapped point core/data_reg_reg[62]/Q core/data_reg_reg[62]/Q -type DFF DFF
add mapped point core/data_reg_reg[63]/Q core/data_reg_reg[63]/Q -type DFF DFF
add mapped point core/done_decrypt_latched_reg/Q core/done_decrypt_latched_reg/Q -type DFF DFF
add mapped point core/done_encrypt_latched_reg/Q core/done_encrypt_latched_reg/Q -type DFF DFF
add mapped point core/key_reg_reg[1]/Q core/key_reg_reg[1]/Q -type DFF DFF
add mapped point core/key_reg_reg[2]/Q core/key_reg_reg[2]/Q -type DFF DFF
add mapped point core/key_reg_reg[3]/Q core/key_reg_reg[3]/Q -type DFF DFF
add mapped point core/key_reg_reg[4]/Q core/key_reg_reg[4]/Q -type DFF DFF
add mapped point core/key_reg_reg[5]/Q core/key_reg_reg[5]/Q -type DFF DFF
add mapped point core/key_reg_reg[6]/Q core/key_reg_reg[6]/Q -type DFF DFF
add mapped point core/key_reg_reg[7]/Q core/key_reg_reg[7]/Q -type DFF DFF
add mapped point core/key_reg_reg[9]/Q core/key_reg_reg[9]/Q -type DFF DFF
add mapped point core/key_reg_reg[10]/Q core/key_reg_reg[10]/Q -type DFF DFF
add mapped point core/key_reg_reg[11]/Q core/key_reg_reg[11]/Q -type DFF DFF
add mapped point core/key_reg_reg[12]/Q core/key_reg_reg[12]/Q -type DFF DFF
add mapped point core/key_reg_reg[13]/Q core/key_reg_reg[13]/Q -type DFF DFF
add mapped point core/key_reg_reg[14]/Q core/key_reg_reg[14]/Q -type DFF DFF
add mapped point core/key_reg_reg[15]/Q core/key_reg_reg[15]/Q -type DFF DFF
add mapped point core/key_reg_reg[17]/Q core/key_reg_reg[17]/Q -type DFF DFF
add mapped point core/key_reg_reg[18]/Q core/key_reg_reg[18]/Q -type DFF DFF
add mapped point core/key_reg_reg[19]/Q core/key_reg_reg[19]/Q -type DFF DFF
add mapped point core/key_reg_reg[20]/Q core/key_reg_reg[20]/Q -type DFF DFF
add mapped point core/key_reg_reg[21]/Q core/key_reg_reg[21]/Q -type DFF DFF
add mapped point core/key_reg_reg[22]/Q core/key_reg_reg[22]/Q -type DFF DFF
add mapped point core/key_reg_reg[23]/Q core/key_reg_reg[23]/Q -type DFF DFF
add mapped point core/key_reg_reg[25]/Q core/key_reg_reg[25]/Q -type DFF DFF
add mapped point core/key_reg_reg[26]/Q core/key_reg_reg[26]/Q -type DFF DFF
add mapped point core/key_reg_reg[27]/Q core/key_reg_reg[27]/Q -type DFF DFF
add mapped point core/key_reg_reg[28]/Q core/key_reg_reg[28]/Q -type DFF DFF
add mapped point core/key_reg_reg[29]/Q core/key_reg_reg[29]/Q -type DFF DFF
add mapped point core/key_reg_reg[30]/Q core/key_reg_reg[30]/Q -type DFF DFF
add mapped point core/key_reg_reg[31]/Q core/key_reg_reg[31]/Q -type DFF DFF
add mapped point core/key_reg_reg[33]/Q core/key_reg_reg[33]/Q -type DFF DFF
add mapped point core/key_reg_reg[34]/Q core/key_reg_reg[34]/Q -type DFF DFF
add mapped point core/key_reg_reg[35]/Q core/key_reg_reg[35]/Q -type DFF DFF
add mapped point core/key_reg_reg[36]/Q core/key_reg_reg[36]/Q -type DFF DFF
add mapped point core/key_reg_reg[37]/Q core/key_reg_reg[37]/Q -type DFF DFF
add mapped point core/key_reg_reg[38]/Q core/key_reg_reg[38]/Q -type DFF DFF
add mapped point core/key_reg_reg[39]/Q core/key_reg_reg[39]/Q -type DFF DFF
add mapped point core/key_reg_reg[41]/Q core/key_reg_reg[41]/Q -type DFF DFF
add mapped point core/key_reg_reg[42]/Q core/key_reg_reg[42]/Q -type DFF DFF
add mapped point core/key_reg_reg[43]/Q core/key_reg_reg[43]/Q -type DFF DFF
add mapped point core/key_reg_reg[44]/Q core/key_reg_reg[44]/Q -type DFF DFF
add mapped point core/key_reg_reg[45]/Q core/key_reg_reg[45]/Q -type DFF DFF
add mapped point core/key_reg_reg[46]/Q core/key_reg_reg[46]/Q -type DFF DFF
add mapped point core/key_reg_reg[47]/Q core/key_reg_reg[47]/Q -type DFF DFF
add mapped point core/key_reg_reg[49]/Q core/key_reg_reg[49]/Q -type DFF DFF
add mapped point core/key_reg_reg[50]/Q core/key_reg_reg[50]/Q -type DFF DFF
add mapped point core/key_reg_reg[51]/Q core/key_reg_reg[51]/Q -type DFF DFF
add mapped point core/key_reg_reg[52]/Q core/key_reg_reg[52]/Q -type DFF DFF
add mapped point core/key_reg_reg[53]/Q core/key_reg_reg[53]/Q -type DFF DFF
add mapped point core/key_reg_reg[54]/Q core/key_reg_reg[54]/Q -type DFF DFF
add mapped point core/key_reg_reg[55]/Q core/key_reg_reg[55]/Q -type DFF DFF
add mapped point core/key_reg_reg[57]/Q core/key_reg_reg[57]/Q -type DFF DFF
add mapped point core/key_reg_reg[58]/Q core/key_reg_reg[58]/Q -type DFF DFF
add mapped point core/key_reg_reg[59]/Q core/key_reg_reg[59]/Q -type DFF DFF
add mapped point core/key_reg_reg[60]/Q core/key_reg_reg[60]/Q -type DFF DFF
add mapped point core/key_reg_reg[61]/Q core/key_reg_reg[61]/Q -type DFF DFF
add mapped point core/key_reg_reg[62]/Q core/key_reg_reg[62]/Q -type DFF DFF
add mapped point core/key_reg_reg[63]/Q core/key_reg_reg[63]/Q -type DFF DFF
add mapped point core/spi_inst_bit_cnt_reg[0]/Q core/spi_inst_bit_cnt_reg[0]/Q -type DFF DFF
add mapped point core/spi_inst_bit_cnt_reg[1]/Q core/spi_inst_bit_cnt_reg[1]/Q -type DFF DFF
add mapped point core/spi_inst_bit_cnt_reg[2]/Q core/spi_inst_bit_cnt_reg[2]/Q -type DFF DFF
add mapped point core/spi_inst_bit_cnt_reg[3]/Q core/spi_inst_bit_cnt_reg[3]/Q -type DFF DFF
add mapped point core/spi_inst_bit_cnt_reg[4]/Q core/spi_inst_bit_cnt_reg[4]/Q -type DFF DFF
add mapped point core/spi_inst_bit_cnt_reg[5]/Q core/spi_inst_bit_cnt_reg[5]/Q -type DFF DFF
add mapped point core/spi_inst_bit_cnt_reg[6]/Q core/spi_inst_bit_cnt_reg[6]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[0]/Q core/spi_inst_input_text_reg[0]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[1]/Q core/spi_inst_input_text_reg[1]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[2]/Q core/spi_inst_input_text_reg[2]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[3]/Q core/spi_inst_input_text_reg[3]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[4]/Q core/spi_inst_input_text_reg[4]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[5]/Q core/spi_inst_input_text_reg[5]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[6]/Q core/spi_inst_input_text_reg[6]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[7]/Q core/spi_inst_input_text_reg[7]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[8]/Q core/spi_inst_input_text_reg[8]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[9]/Q core/spi_inst_input_text_reg[9]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[10]/Q core/spi_inst_input_text_reg[10]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[11]/Q core/spi_inst_input_text_reg[11]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[12]/Q core/spi_inst_input_text_reg[12]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[13]/Q core/spi_inst_input_text_reg[13]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[14]/Q core/spi_inst_input_text_reg[14]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[15]/Q core/spi_inst_input_text_reg[15]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[16]/Q core/spi_inst_input_text_reg[16]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[17]/Q core/spi_inst_input_text_reg[17]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[18]/Q core/spi_inst_input_text_reg[18]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[19]/Q core/spi_inst_input_text_reg[19]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[20]/Q core/spi_inst_input_text_reg[20]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[21]/Q core/spi_inst_input_text_reg[21]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[22]/Q core/spi_inst_input_text_reg[22]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[23]/Q core/spi_inst_input_text_reg[23]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[24]/Q core/spi_inst_input_text_reg[24]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[25]/Q core/spi_inst_input_text_reg[25]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[26]/Q core/spi_inst_input_text_reg[26]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[27]/Q core/spi_inst_input_text_reg[27]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[28]/Q core/spi_inst_input_text_reg[28]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[29]/Q core/spi_inst_input_text_reg[29]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[30]/Q core/spi_inst_input_text_reg[30]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[31]/Q core/spi_inst_input_text_reg[31]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[32]/Q core/spi_inst_input_text_reg[32]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[33]/Q core/spi_inst_input_text_reg[33]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[34]/Q core/spi_inst_input_text_reg[34]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[35]/Q core/spi_inst_input_text_reg[35]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[36]/Q core/spi_inst_input_text_reg[36]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[37]/Q core/spi_inst_input_text_reg[37]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[38]/Q core/spi_inst_input_text_reg[38]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[39]/Q core/spi_inst_input_text_reg[39]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[40]/Q core/spi_inst_input_text_reg[40]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[41]/Q core/spi_inst_input_text_reg[41]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[42]/Q core/spi_inst_input_text_reg[42]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[43]/Q core/spi_inst_input_text_reg[43]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[44]/Q core/spi_inst_input_text_reg[44]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[45]/Q core/spi_inst_input_text_reg[45]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[46]/Q core/spi_inst_input_text_reg[46]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[47]/Q core/spi_inst_input_text_reg[47]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[48]/Q core/spi_inst_input_text_reg[48]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[49]/Q core/spi_inst_input_text_reg[49]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[50]/Q core/spi_inst_input_text_reg[50]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[51]/Q core/spi_inst_input_text_reg[51]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[52]/Q core/spi_inst_input_text_reg[52]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[53]/Q core/spi_inst_input_text_reg[53]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[54]/Q core/spi_inst_input_text_reg[54]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[55]/Q core/spi_inst_input_text_reg[55]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[56]/Q core/spi_inst_input_text_reg[56]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[57]/Q core/spi_inst_input_text_reg[57]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[58]/Q core/spi_inst_input_text_reg[58]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[59]/Q core/spi_inst_input_text_reg[59]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[60]/Q core/spi_inst_input_text_reg[60]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[61]/Q core/spi_inst_input_text_reg[61]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[62]/Q core/spi_inst_input_text_reg[62]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[63]/Q core/spi_inst_input_text_reg[63]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[0]/Q core/spi_inst_shreg_in_reg[0]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[1]/Q core/spi_inst_shreg_in_reg[1]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[2]/Q core/spi_inst_shreg_in_reg[2]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[3]/Q core/spi_inst_shreg_in_reg[3]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[4]/Q core/spi_inst_shreg_in_reg[4]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[5]/Q core/spi_inst_shreg_in_reg[5]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[6]/Q core/spi_inst_shreg_in_reg[6]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[7]/Q core/spi_inst_shreg_in_reg[7]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[8]/Q core/spi_inst_shreg_in_reg[8]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[9]/Q core/spi_inst_shreg_in_reg[9]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[10]/Q core/spi_inst_shreg_in_reg[10]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[11]/Q core/spi_inst_shreg_in_reg[11]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[12]/Q core/spi_inst_shreg_in_reg[12]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[13]/Q core/spi_inst_shreg_in_reg[13]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[14]/Q core/spi_inst_shreg_in_reg[14]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[15]/Q core/spi_inst_shreg_in_reg[15]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[16]/Q core/spi_inst_shreg_in_reg[16]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[17]/Q core/spi_inst_shreg_in_reg[17]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[18]/Q core/spi_inst_shreg_in_reg[18]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[19]/Q core/spi_inst_shreg_in_reg[19]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[20]/Q core/spi_inst_shreg_in_reg[20]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[21]/Q core/spi_inst_shreg_in_reg[21]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[22]/Q core/spi_inst_shreg_in_reg[22]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[23]/Q core/spi_inst_shreg_in_reg[23]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[24]/Q core/spi_inst_shreg_in_reg[24]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[25]/Q core/spi_inst_shreg_in_reg[25]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[26]/Q core/spi_inst_shreg_in_reg[26]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[27]/Q core/spi_inst_shreg_in_reg[27]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[28]/Q core/spi_inst_shreg_in_reg[28]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[29]/Q core/spi_inst_shreg_in_reg[29]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[30]/Q core/spi_inst_shreg_in_reg[30]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[31]/Q core/spi_inst_shreg_in_reg[31]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[32]/Q core/spi_inst_shreg_in_reg[32]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[33]/Q core/spi_inst_shreg_in_reg[33]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[34]/Q core/spi_inst_shreg_in_reg[34]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[35]/Q core/spi_inst_shreg_in_reg[35]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[36]/Q core/spi_inst_shreg_in_reg[36]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[37]/Q core/spi_inst_shreg_in_reg[37]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[38]/Q core/spi_inst_shreg_in_reg[38]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[39]/Q core/spi_inst_shreg_in_reg[39]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[40]/Q core/spi_inst_shreg_in_reg[40]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[41]/Q core/spi_inst_shreg_in_reg[41]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[42]/Q core/spi_inst_shreg_in_reg[42]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[43]/Q core/spi_inst_shreg_in_reg[43]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[44]/Q core/spi_inst_shreg_in_reg[44]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[45]/Q core/spi_inst_shreg_in_reg[45]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[46]/Q core/spi_inst_shreg_in_reg[46]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[47]/Q core/spi_inst_shreg_in_reg[47]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[48]/Q core/spi_inst_shreg_in_reg[48]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[49]/Q core/spi_inst_shreg_in_reg[49]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[50]/Q core/spi_inst_shreg_in_reg[50]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[51]/Q core/spi_inst_shreg_in_reg[51]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[52]/Q core/spi_inst_shreg_in_reg[52]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[53]/Q core/spi_inst_shreg_in_reg[53]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[54]/Q core/spi_inst_shreg_in_reg[54]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[55]/Q core/spi_inst_shreg_in_reg[55]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[56]/Q core/spi_inst_shreg_in_reg[56]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[57]/Q core/spi_inst_shreg_in_reg[57]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[58]/Q core/spi_inst_shreg_in_reg[58]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[59]/Q core/spi_inst_shreg_in_reg[59]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[60]/Q core/spi_inst_shreg_in_reg[60]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[61]/Q core/spi_inst_shreg_in_reg[61]/Q -type DFF DFF
add mapped point core/spi_inst_shreg_in_reg[62]/Q core/spi_inst_shreg_in_reg[62]/Q -type DFF DFF
add mapped point core/start_decrypt_reg/Q core/start_decrypt_reg/Q -type DFF DFF
add mapped point core/start_encrypt_reg/Q core/start_encrypt_reg/Q -type DFF DFF
add mapped point core/transaction_state_reg[0]/Q core/transaction_state_reg[0]/Q -type DFF DFF
add mapped point core/transaction_state_reg[1]/Q core/transaction_state_reg[1]/Q -type DFF DFF



//Black Boxes
add mapped point clk_pad clk_pad -type BBOX BBOX
add mapped point cs_n_pad cs_n_pad -type BBOX BBOX
add mapped point miso_pad miso_pad -type BBOX BBOX
add mapped point mosi_pad mosi_pad -type BBOX BBOX
add mapped point rst_pad rst_pad -type BBOX BBOX
add mapped point sclk_pad sclk_pad -type BBOX BBOX



//Empty Modules as Blackboxes
