
//input ports
add mapped point clk clk -type PI PI
add mapped point rst rst -type PI PI
add mapped point sclk sclk -type PI PI
add mapped point cs_n cs_n -type PI PI
add mapped point mosi mosi -type PI PI

//output ports
add mapped point miso miso -type PO PO

//inout ports




//Sequential Pins
add mapped point core/active_reg/Q core/active_reg/Q -type DFF DFF
add mapped point core/crypt_reg/Q core/crypt_reg/Q -type DFF DFF
add mapped point core/cs_meta_reg/Q core/cs_meta_reg/Q -type DFF DFF
add mapped point core/cs_prev_reg/Q core/cs_prev_reg/Q -type DFF DFF
add mapped point core/cs_rise_delayed_reg/Q core/cs_rise_delayed_reg/Q -type DFF DFF
add mapped point core/cs_sync_reg/Q core/cs_sync_reg/Q -type DFF DFF
add mapped point core/csm_inst_done_decrypt_reg/Q core/csm_inst_done_decrypt_reg/Q -type DFF DFF
add mapped point core/csm_inst_done_encrypt_reg/Q core/csm_inst_done_encrypt_reg/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[0]/Q core/csm_inst_left_reg_reg[0]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[1]/Q core/csm_inst_left_reg_reg[1]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[2]/Q core/csm_inst_left_reg_reg[2]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[3]/Q core/csm_inst_left_reg_reg[3]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[4]/Q core/csm_inst_left_reg_reg[4]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[5]/Q core/csm_inst_left_reg_reg[5]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[6]/Q core/csm_inst_left_reg_reg[6]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[7]/Q core/csm_inst_left_reg_reg[7]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[8]/Q core/csm_inst_left_reg_reg[8]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[9]/Q core/csm_inst_left_reg_reg[9]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[10]/Q core/csm_inst_left_reg_reg[10]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[11]/Q core/csm_inst_left_reg_reg[11]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[12]/Q core/csm_inst_left_reg_reg[12]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[13]/Q core/csm_inst_left_reg_reg[13]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[14]/Q core/csm_inst_left_reg_reg[14]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[15]/Q core/csm_inst_left_reg_reg[15]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[16]/Q core/csm_inst_left_reg_reg[16]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[17]/Q core/csm_inst_left_reg_reg[17]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[18]/Q core/csm_inst_left_reg_reg[18]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[19]/Q core/csm_inst_left_reg_reg[19]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[20]/Q core/csm_inst_left_reg_reg[20]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[21]/Q core/csm_inst_left_reg_reg[21]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[22]/Q core/csm_inst_left_reg_reg[22]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[23]/Q core/csm_inst_left_reg_reg[23]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[24]/Q core/csm_inst_left_reg_reg[24]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[25]/Q core/csm_inst_left_reg_reg[25]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[26]/Q core/csm_inst_left_reg_reg[26]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[27]/Q core/csm_inst_left_reg_reg[27]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[28]/Q core/csm_inst_left_reg_reg[28]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[29]/Q core/csm_inst_left_reg_reg[29]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[30]/Q core/csm_inst_left_reg_reg[30]/Q -type DFF DFF
add mapped point core/csm_inst_left_reg_reg[31]/Q core/csm_inst_left_reg_reg[31]/Q -type DFF DFF
add mapped point core/csm_inst_mode_reg/Q core/csm_inst_mode_reg/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[0]/Q core/csm_inst_output_text_reg[0]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[1]/Q core/csm_inst_output_text_reg[1]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[2]/Q core/csm_inst_output_text_reg[2]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[3]/Q core/csm_inst_output_text_reg[3]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[4]/Q core/csm_inst_output_text_reg[4]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[5]/Q core/csm_inst_output_text_reg[5]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[6]/Q core/csm_inst_output_text_reg[6]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[7]/Q core/csm_inst_output_text_reg[7]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[8]/Q core/csm_inst_output_text_reg[8]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[9]/Q core/csm_inst_output_text_reg[9]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[10]/Q core/csm_inst_output_text_reg[10]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[11]/Q core/csm_inst_output_text_reg[11]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[12]/Q core/csm_inst_output_text_reg[12]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[13]/Q core/csm_inst_output_text_reg[13]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[14]/Q core/csm_inst_output_text_reg[14]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[15]/Q core/csm_inst_output_text_reg[15]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[16]/Q core/csm_inst_output_text_reg[16]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[17]/Q core/csm_inst_output_text_reg[17]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[18]/Q core/csm_inst_output_text_reg[18]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[19]/Q core/csm_inst_output_text_reg[19]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[20]/Q core/csm_inst_output_text_reg[20]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[21]/Q core/csm_inst_output_text_reg[21]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[22]/Q core/csm_inst_output_text_reg[22]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[23]/Q core/csm_inst_output_text_reg[23]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[24]/Q core/csm_inst_output_text_reg[24]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[25]/Q core/csm_inst_output_text_reg[25]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[26]/Q core/csm_inst_output_text_reg[26]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[27]/Q core/csm_inst_output_text_reg[27]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[28]/Q core/csm_inst_output_text_reg[28]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[29]/Q core/csm_inst_output_text_reg[29]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[30]/Q core/csm_inst_output_text_reg[30]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[31]/Q core/csm_inst_output_text_reg[31]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[32]/Q core/csm_inst_output_text_reg[32]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[33]/Q core/csm_inst_output_text_reg[33]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[34]/Q core/csm_inst_output_text_reg[34]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[35]/Q core/csm_inst_output_text_reg[35]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[36]/Q core/csm_inst_output_text_reg[36]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[37]/Q core/csm_inst_output_text_reg[37]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[38]/Q core/csm_inst_output_text_reg[38]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[39]/Q core/csm_inst_output_text_reg[39]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[40]/Q core/csm_inst_output_text_reg[40]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[41]/Q core/csm_inst_output_text_reg[41]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[42]/Q core/csm_inst_output_text_reg[42]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[43]/Q core/csm_inst_output_text_reg[43]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[44]/Q core/csm_inst_output_text_reg[44]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[45]/Q core/csm_inst_output_text_reg[45]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[46]/Q core/csm_inst_output_text_reg[46]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[47]/Q core/csm_inst_output_text_reg[47]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[48]/Q core/csm_inst_output_text_reg[48]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[49]/Q core/csm_inst_output_text_reg[49]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[50]/Q core/csm_inst_output_text_reg[50]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[51]/Q core/csm_inst_output_text_reg[51]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[52]/Q core/csm_inst_output_text_reg[52]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[53]/Q core/csm_inst_output_text_reg[53]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[54]/Q core/csm_inst_output_text_reg[54]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[55]/Q core/csm_inst_output_text_reg[55]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[56]/Q core/csm_inst_output_text_reg[56]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[57]/Q core/csm_inst_output_text_reg[57]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[58]/Q core/csm_inst_output_text_reg[58]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[59]/Q core/csm_inst_output_text_reg[59]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[60]/Q core/csm_inst_output_text_reg[60]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[61]/Q core/csm_inst_output_text_reg[61]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[62]/Q core/csm_inst_output_text_reg[62]/Q -type DFF DFF
add mapped point core/csm_inst_output_text_reg[63]/Q core/csm_inst_output_text_reg[63]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[0]/Q core/csm_inst_right_reg_reg[0]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[1]/Q core/csm_inst_right_reg_reg[1]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[2]/Q core/csm_inst_right_reg_reg[2]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[3]/Q core/csm_inst_right_reg_reg[3]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[4]/Q core/csm_inst_right_reg_reg[4]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[5]/Q core/csm_inst_right_reg_reg[5]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[6]/Q core/csm_inst_right_reg_reg[6]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[7]/Q core/csm_inst_right_reg_reg[7]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[8]/Q core/csm_inst_right_reg_reg[8]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[9]/Q core/csm_inst_right_reg_reg[9]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[10]/Q core/csm_inst_right_reg_reg[10]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[11]/Q core/csm_inst_right_reg_reg[11]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[12]/Q core/csm_inst_right_reg_reg[12]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[13]/Q core/csm_inst_right_reg_reg[13]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[14]/Q core/csm_inst_right_reg_reg[14]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[15]/Q core/csm_inst_right_reg_reg[15]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[16]/Q core/csm_inst_right_reg_reg[16]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[17]/Q core/csm_inst_right_reg_reg[17]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[18]/Q core/csm_inst_right_reg_reg[18]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[19]/Q core/csm_inst_right_reg_reg[19]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[20]/Q core/csm_inst_right_reg_reg[20]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[21]/Q core/csm_inst_right_reg_reg[21]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[22]/Q core/csm_inst_right_reg_reg[22]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[23]/Q core/csm_inst_right_reg_reg[23]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[24]/Q core/csm_inst_right_reg_reg[24]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[25]/Q core/csm_inst_right_reg_reg[25]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[26]/Q core/csm_inst_right_reg_reg[26]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[27]/Q core/csm_inst_right_reg_reg[27]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[28]/Q core/csm_inst_right_reg_reg[28]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[29]/Q core/csm_inst_right_reg_reg[29]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[30]/Q core/csm_inst_right_reg_reg[30]/Q -type DFF DFF
add mapped point core/csm_inst_right_reg_reg[31]/Q core/csm_inst_right_reg_reg[31]/Q -type DFF DFF
add mapped point core/csm_inst_round_counter_reg[0]/Q core/csm_inst_round_counter_reg[0]/Q -type DFF DFF
add mapped point core/csm_inst_round_counter_reg[1]/Q core/csm_inst_round_counter_reg[1]/Q -type DFF DFF
add mapped point core/csm_inst_round_counter_reg[2]/Q core/csm_inst_round_counter_reg[2]/Q -type DFF DFF
add mapped point core/csm_inst_round_counter_reg[3]/Q core/csm_inst_round_counter_reg[3]/Q -type DFF DFF
add mapped point core/csm_inst_state_reg[0]/Q core/csm_inst_state_reg[0]/Q -type DFF DFF
add mapped point core/csm_inst_state_reg[1]/Q core/csm_inst_state_reg[1]/Q -type DFF DFF
add mapped point core/csm_inst_state_reg[2]/Q core/csm_inst_state_reg[2]/Q -type DFF DFF
add mapped point core/data_reg_reg[0]/Q core/data_reg_reg[0]/Q -type DFF DFF
add mapped point core/data_reg_reg[1]/Q core/data_reg_reg[1]/Q -type DFF DFF
add mapped point core/data_reg_reg[2]/Q core/data_reg_reg[2]/Q -type DFF DFF
add mapped point core/data_reg_reg[3]/Q core/data_reg_reg[3]/Q -type DFF DFF
add mapped point core/data_reg_reg[4]/Q core/data_reg_reg[4]/Q -type DFF DFF
add mapped point core/data_reg_reg[5]/Q core/data_reg_reg[5]/Q -type DFF DFF
add mapped point core/data_reg_reg[6]/Q core/data_reg_reg[6]/Q -type DFF DFF
add mapped point core/data_reg_reg[7]/Q core/data_reg_reg[7]/Q -type DFF DFF
add mapped point core/data_reg_reg[8]/Q core/data_reg_reg[8]/Q -type DFF DFF
add mapped point core/data_reg_reg[9]/Q core/data_reg_reg[9]/Q -type DFF DFF
add mapped point core/data_reg_reg[10]/Q core/data_reg_reg[10]/Q -type DFF DFF
add mapped point core/data_reg_reg[11]/Q core/data_reg_reg[11]/Q -type DFF DFF
add mapped point core/data_reg_reg[12]/Q core/data_reg_reg[12]/Q -type DFF DFF
add mapped point core/data_reg_reg[13]/Q core/data_reg_reg[13]/Q -type DFF DFF
add mapped point core/data_reg_reg[14]/Q core/data_reg_reg[14]/Q -type DFF DFF
add mapped point core/data_reg_reg[15]/Q core/data_reg_reg[15]/Q -type DFF DFF
add mapped point core/data_reg_reg[16]/Q core/data_reg_reg[16]/Q -type DFF DFF
add mapped point core/data_reg_reg[17]/Q core/data_reg_reg[17]/Q -type DFF DFF
add mapped point core/data_reg_reg[18]/Q core/data_reg_reg[18]/Q -type DFF DFF
add mapped point core/data_reg_reg[19]/Q core/data_reg_reg[19]/Q -type DFF DFF
add mapped point core/data_reg_reg[20]/Q core/data_reg_reg[20]/Q -type DFF DFF
add mapped point core/data_reg_reg[21]/Q core/data_reg_reg[21]/Q -type DFF DFF
add mapped point core/data_reg_reg[22]/Q core/data_reg_reg[22]/Q -type DFF DFF
add mapped point core/data_reg_reg[23]/Q core/data_reg_reg[23]/Q -type DFF DFF
add mapped point core/data_reg_reg[24]/Q core/data_reg_reg[24]/Q -type DFF DFF
add mapped point core/data_reg_reg[25]/Q core/data_reg_reg[25]/Q -type DFF DFF
add mapped point core/data_reg_reg[26]/Q core/data_reg_reg[26]/Q -type DFF DFF
add mapped point core/data_reg_reg[27]/Q core/data_reg_reg[27]/Q -type DFF DFF
add mapped point core/data_reg_reg[28]/Q core/data_reg_reg[28]/Q -type DFF DFF
add mapped point core/data_reg_reg[29]/Q core/data_reg_reg[29]/Q -type DFF DFF
add mapped point core/data_reg_reg[30]/Q core/data_reg_reg[30]/Q -type DFF DFF
add mapped point core/data_reg_reg[31]/Q core/data_reg_reg[31]/Q -type DFF DFF
add mapped point core/data_reg_reg[32]/Q core/data_reg_reg[32]/Q -type DFF DFF
add mapped point core/data_reg_reg[33]/Q core/data_reg_reg[33]/Q -type DFF DFF
add mapped point core/data_reg_reg[34]/Q core/data_reg_reg[34]/Q -type DFF DFF
add mapped point core/data_reg_reg[35]/Q core/data_reg_reg[35]/Q -type DFF DFF
add mapped point core/data_reg_reg[36]/Q core/data_reg_reg[36]/Q -type DFF DFF
add mapped point core/data_reg_reg[37]/Q core/data_reg_reg[37]/Q -type DFF DFF
add mapped point core/data_reg_reg[38]/Q core/data_reg_reg[38]/Q -type DFF DFF
add mapped point core/data_reg_reg[39]/Q core/data_reg_reg[39]/Q -type DFF DFF
add mapped point core/data_reg_reg[40]/Q core/data_reg_reg[40]/Q -type DFF DFF
add mapped point core/data_reg_reg[41]/Q core/data_reg_reg[41]/Q -type DFF DFF
add mapped point core/data_reg_reg[42]/Q core/data_reg_reg[42]/Q -type DFF DFF
add mapped point core/data_reg_reg[43]/Q core/data_reg_reg[43]/Q -type DFF DFF
add mapped point core/data_reg_reg[44]/Q core/data_reg_reg[44]/Q -type DFF DFF
add mapped point core/data_reg_reg[45]/Q core/data_reg_reg[45]/Q -type DFF DFF
add mapped point core/data_reg_reg[46]/Q core/data_reg_reg[46]/Q -type DFF DFF
add mapped point core/data_reg_reg[47]/Q core/data_reg_reg[47]/Q -type DFF DFF
add mapped point core/data_reg_reg[48]/Q core/data_reg_reg[48]/Q -type DFF DFF
add mapped point core/data_reg_reg[49]/Q core/data_reg_reg[49]/Q -type DFF DFF
add mapped point core/data_reg_reg[50]/Q core/data_reg_reg[50]/Q -type DFF DFF
add mapped point core/data_reg_reg[51]/Q core/data_reg_reg[51]/Q -type DFF DFF
add mapped point core/data_reg_reg[52]/Q core/data_reg_reg[52]/Q -type DFF DFF
add mapped point core/data_reg_reg[53]/Q core/data_reg_reg[53]/Q -type DFF DFF
add mapped point core/data_reg_reg[54]/Q core/data_reg_reg[54]/Q -type DFF DFF
add mapped point core/data_reg_reg[55]/Q core/data_reg_reg[55]/Q -type DFF DFF
add mapped point core/data_reg_reg[56]/Q core/data_reg_reg[56]/Q -type DFF DFF
add mapped point core/data_reg_reg[57]/Q core/data_reg_reg[57]/Q -type DFF DFF
add mapped point core/data_reg_reg[58]/Q core/data_reg_reg[58]/Q -type DFF DFF
add mapped point core/data_reg_reg[59]/Q core/data_reg_reg[59]/Q -type DFF DFF
add mapped point core/data_reg_reg[60]/Q core/data_reg_reg[60]/Q -type DFF DFF
add mapped point core/data_reg_reg[61]/Q core/data_reg_reg[61]/Q -type DFF DFF
add mapped point core/data_reg_reg[62]/Q core/data_reg_reg[62]/Q -type DFF DFF
add mapped point core/data_reg_reg[63]/Q core/data_reg_reg[63]/Q -type DFF DFF
add mapped point core/done_decrypt_latched_reg/Q core/done_decrypt_latched_reg/Q -type DFF DFF
add mapped point core/done_encrypt_latched_reg/Q core/done_encrypt_latched_reg/Q -type DFF DFF
add mapped point core/key_reg_reg[1]/Q core/key_reg_reg[1]/Q -type DFF DFF
add mapped point core/key_reg_reg[2]/Q core/key_reg_reg[2]/Q -type DFF DFF
add mapped point core/key_reg_reg[3]/Q core/key_reg_reg[3]/Q -type DFF DFF
add mapped point core/key_reg_reg[4]/Q core/key_reg_reg[4]/Q -type DFF DFF
add mapped point core/key_reg_reg[5]/Q core/key_reg_reg[5]/Q -type DFF DFF
add mapped point core/key_reg_reg[6]/Q core/key_reg_reg[6]/Q -type DFF DFF
add mapped point core/key_reg_reg[7]/Q core/key_reg_reg[7]/Q -type DFF DFF
add mapped point core/key_reg_reg[9]/Q core/key_reg_reg[9]/Q -type DFF DFF
add mapped point core/key_reg_reg[10]/Q core/key_reg_reg[10]/Q -type DFF DFF
add mapped point core/key_reg_reg[11]/Q core/key_reg_reg[11]/Q -type DFF DFF
add mapped point core/key_reg_reg[12]/Q core/key_reg_reg[12]/Q -type DFF DFF
add mapped point core/key_reg_reg[13]/Q core/key_reg_reg[13]/Q -type DFF DFF
add mapped point core/key_reg_reg[14]/Q core/key_reg_reg[14]/Q -type DFF DFF
add mapped point core/key_reg_reg[15]/Q core/key_reg_reg[15]/Q -type DFF DFF
add mapped point core/key_reg_reg[17]/Q core/key_reg_reg[17]/Q -type DFF DFF
add mapped point core/key_reg_reg[18]/Q core/key_reg_reg[18]/Q -type DFF DFF
add mapped point core/key_reg_reg[19]/Q core/key_reg_reg[19]/Q -type DFF DFF
add mapped point core/key_reg_reg[20]/Q core/key_reg_reg[20]/Q -type DFF DFF
add mapped point core/key_reg_reg[21]/Q core/key_reg_reg[21]/Q -type DFF DFF
add mapped point core/key_reg_reg[22]/Q core/key_reg_reg[22]/Q -type DFF DFF
add mapped point core/key_reg_reg[23]/Q core/key_reg_reg[23]/Q -type DFF DFF
add mapped point core/key_reg_reg[25]/Q core/key_reg_reg[25]/Q -type DFF DFF
add mapped point core/key_reg_reg[26]/Q core/key_reg_reg[26]/Q -type DFF DFF
add mapped point core/key_reg_reg[27]/Q core/key_reg_reg[27]/Q -type DFF DFF
add mapped point core/key_reg_reg[28]/Q core/key_reg_reg[28]/Q -type DFF DFF
add mapped point core/key_reg_reg[29]/Q core/key_reg_reg[29]/Q -type DFF DFF
add mapped point core/key_reg_reg[30]/Q core/key_reg_reg[30]/Q -type DFF DFF
add mapped point core/key_reg_reg[31]/Q core/key_reg_reg[31]/Q -type DFF DFF
add mapped point core/key_reg_reg[33]/Q core/key_reg_reg[33]/Q -type DFF DFF
add mapped point core/key_reg_reg[34]/Q core/key_reg_reg[34]/Q -type DFF DFF
add mapped point core/key_reg_reg[35]/Q core/key_reg_reg[35]/Q -type DFF DFF
add mapped point core/key_reg_reg[36]/Q core/key_reg_reg[36]/Q -type DFF DFF
add mapped point core/key_reg_reg[37]/Q core/key_reg_reg[37]/Q -type DFF DFF
add mapped point core/key_reg_reg[38]/Q core/key_reg_reg[38]/Q -type DFF DFF
add mapped point core/key_reg_reg[39]/Q core/key_reg_reg[39]/Q -type DFF DFF
add mapped point core/key_reg_reg[41]/Q core/key_reg_reg[41]/Q -type DFF DFF
add mapped point core/key_reg_reg[42]/Q core/key_reg_reg[42]/Q -type DFF DFF
add mapped point core/key_reg_reg[43]/Q core/key_reg_reg[43]/Q -type DFF DFF
add mapped point core/key_reg_reg[44]/Q core/key_reg_reg[44]/Q -type DFF DFF
add mapped point core/key_reg_reg[45]/Q core/key_reg_reg[45]/Q -type DFF DFF
add mapped point core/key_reg_reg[46]/Q core/key_reg_reg[46]/Q -type DFF DFF
add mapped point core/key_reg_reg[47]/Q core/key_reg_reg[47]/Q -type DFF DFF
add mapped point core/key_reg_reg[49]/Q core/key_reg_reg[49]/Q -type DFF DFF
add mapped point core/key_reg_reg[50]/Q core/key_reg_reg[50]/Q -type DFF DFF
add mapped point core/key_reg_reg[51]/Q core/key_reg_reg[51]/Q -type DFF DFF
add mapped point core/key_reg_reg[52]/Q core/key_reg_reg[52]/Q -type DFF DFF
add mapped point core/key_reg_reg[53]/Q core/key_reg_reg[53]/Q -type DFF DFF
add mapped point core/key_reg_reg[54]/Q core/key_reg_reg[54]/Q -type DFF DFF
add mapped point core/key_reg_reg[55]/Q core/key_reg_reg[55]/Q -type DFF DFF
add mapped point core/key_reg_reg[57]/Q core/key_reg_reg[57]/Q -type DFF DFF
add mapped point core/key_reg_reg[58]/Q core/key_reg_reg[58]/Q -type DFF DFF
add mapped point core/key_reg_reg[59]/Q core/key_reg_reg[59]/Q -type DFF DFF
add mapped point core/key_reg_reg[60]/Q core/key_reg_reg[60]/Q -type DFF DFF
add mapped point core/key_reg_reg[61]/Q core/key_reg_reg[61]/Q -type DFF DFF
add mapped point core/key_reg_reg[62]/Q core/key_reg_reg[62]/Q -type DFF DFF
add mapped point core/key_reg_reg[63]/Q core/key_reg_reg[63]/Q -type DFF DFF
add mapped point core/spi_inst_cs_prev_reg/Q core/spi_inst_cs_prev_reg/Q -type DFF DFF
add mapped point core/spi_inst_in_count_reg[0]/Q core/spi_inst_in_count_reg[0]/Q -type DFF DFF
add mapped point core/spi_inst_in_count_reg[1]/Q core/spi_inst_in_count_reg[1]/Q -type DFF DFF
add mapped point core/spi_inst_in_count_reg[2]/Q core/spi_inst_in_count_reg[2]/Q -type DFF DFF
add mapped point core/spi_inst_in_count_reg[3]/Q core/spi_inst_in_count_reg[3]/Q -type DFF DFF
add mapped point core/spi_inst_in_count_reg[4]/Q core/spi_inst_in_count_reg[4]/Q -type DFF DFF
add mapped point core/spi_inst_in_count_reg[5]/Q core/spi_inst_in_count_reg[5]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[0]/Q core/spi_inst_input_text_reg[0]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[1]/Q core/spi_inst_input_text_reg[1]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[2]/Q core/spi_inst_input_text_reg[2]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[3]/Q core/spi_inst_input_text_reg[3]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[4]/Q core/spi_inst_input_text_reg[4]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[5]/Q core/spi_inst_input_text_reg[5]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[6]/Q core/spi_inst_input_text_reg[6]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[7]/Q core/spi_inst_input_text_reg[7]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[8]/Q core/spi_inst_input_text_reg[8]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[9]/Q core/spi_inst_input_text_reg[9]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[10]/Q core/spi_inst_input_text_reg[10]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[11]/Q core/spi_inst_input_text_reg[11]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[12]/Q core/spi_inst_input_text_reg[12]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[13]/Q core/spi_inst_input_text_reg[13]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[14]/Q core/spi_inst_input_text_reg[14]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[15]/Q core/spi_inst_input_text_reg[15]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[16]/Q core/spi_inst_input_text_reg[16]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[17]/Q core/spi_inst_input_text_reg[17]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[18]/Q core/spi_inst_input_text_reg[18]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[19]/Q core/spi_inst_input_text_reg[19]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[20]/Q core/spi_inst_input_text_reg[20]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[21]/Q core/spi_inst_input_text_reg[21]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[22]/Q core/spi_inst_input_text_reg[22]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[23]/Q core/spi_inst_input_text_reg[23]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[24]/Q core/spi_inst_input_text_reg[24]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[25]/Q core/spi_inst_input_text_reg[25]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[26]/Q core/spi_inst_input_text_reg[26]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[27]/Q core/spi_inst_input_text_reg[27]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[28]/Q core/spi_inst_input_text_reg[28]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[29]/Q core/spi_inst_input_text_reg[29]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[30]/Q core/spi_inst_input_text_reg[30]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[31]/Q core/spi_inst_input_text_reg[31]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[32]/Q core/spi_inst_input_text_reg[32]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[33]/Q core/spi_inst_input_text_reg[33]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[34]/Q core/spi_inst_input_text_reg[34]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[35]/Q core/spi_inst_input_text_reg[35]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[36]/Q core/spi_inst_input_text_reg[36]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[37]/Q core/spi_inst_input_text_reg[37]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[38]/Q core/spi_inst_input_text_reg[38]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[39]/Q core/spi_inst_input_text_reg[39]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[40]/Q core/spi_inst_input_text_reg[40]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[41]/Q core/spi_inst_input_text_reg[41]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[42]/Q core/spi_inst_input_text_reg[42]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[43]/Q core/spi_inst_input_text_reg[43]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[44]/Q core/spi_inst_input_text_reg[44]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[45]/Q core/spi_inst_input_text_reg[45]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[46]/Q core/spi_inst_input_text_reg[46]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[47]/Q core/spi_inst_input_text_reg[47]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[48]/Q core/spi_inst_input_text_reg[48]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[49]/Q core/spi_inst_input_text_reg[49]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[50]/Q core/spi_inst_input_text_reg[50]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[51]/Q core/spi_inst_input_text_reg[51]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[52]/Q core/spi_inst_input_text_reg[52]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[53]/Q core/spi_inst_input_text_reg[53]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[54]/Q core/spi_inst_input_text_reg[54]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[55]/Q core/spi_inst_input_text_reg[55]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[56]/Q core/spi_inst_input_text_reg[56]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[57]/Q core/spi_inst_input_text_reg[57]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[58]/Q core/spi_inst_input_text_reg[58]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[59]/Q core/spi_inst_input_text_reg[59]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[60]/Q core/spi_inst_input_text_reg[60]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[61]/Q core/spi_inst_input_text_reg[61]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[62]/Q core/spi_inst_input_text_reg[62]/Q -type DFF DFF
add mapped point core/spi_inst_input_text_reg[63]/Q core/spi_inst_input_text_reg[63]/Q -type DFF DFF
add mapped point core/spi_inst_miso_reg_reg/Q core/spi_inst_miso_reg_reg/Q -type DFF DFF
add mapped point core/spi_inst_miso_reg_reg368/Q core/spi_inst_miso_reg_reg368/Q -type DFF DFF
add mapped point core/spi_inst_out_count_reg[0]354/Q core/spi_inst_out_count_reg[0]354/Q -type DFF DFF
add mapped point core/spi_inst_out_count_reg[1]355/Q core/spi_inst_out_count_reg[1]355/Q -type DFF DFF
add mapped point core/spi_inst_out_count_reg[2]356/Q core/spi_inst_out_count_reg[2]356/Q -type DFF DFF
add mapped point core/spi_inst_out_count_reg[3]357/Q core/spi_inst_out_count_reg[3]357/Q -type DFF DFF
add mapped point core/spi_inst_out_count_reg[4]358/Q core/spi_inst_out_count_reg[4]358/Q -type DFF DFF
add mapped point core/spi_inst_out_count_reg[5]359/Q core/spi_inst_out_count_reg[5]359/Q -type DFF DFF
add mapped point core/spi_inst_out_count_reg[6]360/Q core/spi_inst_out_count_reg[6]360/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[0]/Q core/spi_inst_shift_in_reg[0]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[1]/Q core/spi_inst_shift_in_reg[1]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[2]/Q core/spi_inst_shift_in_reg[2]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[3]/Q core/spi_inst_shift_in_reg[3]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[4]/Q core/spi_inst_shift_in_reg[4]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[5]/Q core/spi_inst_shift_in_reg[5]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[6]/Q core/spi_inst_shift_in_reg[6]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[7]/Q core/spi_inst_shift_in_reg[7]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[8]/Q core/spi_inst_shift_in_reg[8]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[9]/Q core/spi_inst_shift_in_reg[9]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[10]/Q core/spi_inst_shift_in_reg[10]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[11]/Q core/spi_inst_shift_in_reg[11]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[12]/Q core/spi_inst_shift_in_reg[12]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[13]/Q core/spi_inst_shift_in_reg[13]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[14]/Q core/spi_inst_shift_in_reg[14]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[15]/Q core/spi_inst_shift_in_reg[15]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[16]/Q core/spi_inst_shift_in_reg[16]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[17]/Q core/spi_inst_shift_in_reg[17]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[18]/Q core/spi_inst_shift_in_reg[18]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[19]/Q core/spi_inst_shift_in_reg[19]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[20]/Q core/spi_inst_shift_in_reg[20]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[21]/Q core/spi_inst_shift_in_reg[21]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[22]/Q core/spi_inst_shift_in_reg[22]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[23]/Q core/spi_inst_shift_in_reg[23]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[24]/Q core/spi_inst_shift_in_reg[24]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[25]/Q core/spi_inst_shift_in_reg[25]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[26]/Q core/spi_inst_shift_in_reg[26]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[27]/Q core/spi_inst_shift_in_reg[27]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[28]/Q core/spi_inst_shift_in_reg[28]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[29]/Q core/spi_inst_shift_in_reg[29]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[30]/Q core/spi_inst_shift_in_reg[30]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[31]/Q core/spi_inst_shift_in_reg[31]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[32]/Q core/spi_inst_shift_in_reg[32]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[33]/Q core/spi_inst_shift_in_reg[33]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[34]/Q core/spi_inst_shift_in_reg[34]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[35]/Q core/spi_inst_shift_in_reg[35]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[36]/Q core/spi_inst_shift_in_reg[36]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[37]/Q core/spi_inst_shift_in_reg[37]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[38]/Q core/spi_inst_shift_in_reg[38]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[39]/Q core/spi_inst_shift_in_reg[39]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[40]/Q core/spi_inst_shift_in_reg[40]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[41]/Q core/spi_inst_shift_in_reg[41]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[42]/Q core/spi_inst_shift_in_reg[42]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[43]/Q core/spi_inst_shift_in_reg[43]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[44]/Q core/spi_inst_shift_in_reg[44]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[45]/Q core/spi_inst_shift_in_reg[45]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[46]/Q core/spi_inst_shift_in_reg[46]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[47]/Q core/spi_inst_shift_in_reg[47]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[48]/Q core/spi_inst_shift_in_reg[48]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[49]/Q core/spi_inst_shift_in_reg[49]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[50]/Q core/spi_inst_shift_in_reg[50]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[51]/Q core/spi_inst_shift_in_reg[51]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[52]/Q core/spi_inst_shift_in_reg[52]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[53]/Q core/spi_inst_shift_in_reg[53]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[54]/Q core/spi_inst_shift_in_reg[54]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[55]/Q core/spi_inst_shift_in_reg[55]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[56]/Q core/spi_inst_shift_in_reg[56]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[57]/Q core/spi_inst_shift_in_reg[57]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[58]/Q core/spi_inst_shift_in_reg[58]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[59]/Q core/spi_inst_shift_in_reg[59]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[60]/Q core/spi_inst_shift_in_reg[60]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[61]/Q core/spi_inst_shift_in_reg[61]/Q -type DFF DFF
add mapped point core/spi_inst_shift_in_reg[62]/Q core/spi_inst_shift_in_reg[62]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[1]/Q core/spi_inst_shift_out_reg[1]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[2]/Q core/spi_inst_shift_out_reg[2]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[2]233/Q core/spi_inst_shift_out_reg[2]233/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[3]/Q core/spi_inst_shift_out_reg[3]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[3]234/Q core/spi_inst_shift_out_reg[3]234/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[4]/Q core/spi_inst_shift_out_reg[4]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[4]235/Q core/spi_inst_shift_out_reg[4]235/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[5]/Q core/spi_inst_shift_out_reg[5]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[5]236/Q core/spi_inst_shift_out_reg[5]236/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[6]/Q core/spi_inst_shift_out_reg[6]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[6]237/Q core/spi_inst_shift_out_reg[6]237/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[7]/Q core/spi_inst_shift_out_reg[7]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[7]238/Q core/spi_inst_shift_out_reg[7]238/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[8]/Q core/spi_inst_shift_out_reg[8]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[8]239/Q core/spi_inst_shift_out_reg[8]239/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[9]/Q core/spi_inst_shift_out_reg[9]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[9]240/Q core/spi_inst_shift_out_reg[9]240/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[10]/Q core/spi_inst_shift_out_reg[10]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[10]241/Q core/spi_inst_shift_out_reg[10]241/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[11]/Q core/spi_inst_shift_out_reg[11]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[11]242/Q core/spi_inst_shift_out_reg[11]242/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[12]/Q core/spi_inst_shift_out_reg[12]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[12]243/Q core/spi_inst_shift_out_reg[12]243/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[13]/Q core/spi_inst_shift_out_reg[13]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[13]244/Q core/spi_inst_shift_out_reg[13]244/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[14]/Q core/spi_inst_shift_out_reg[14]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[14]245/Q core/spi_inst_shift_out_reg[14]245/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[15]/Q core/spi_inst_shift_out_reg[15]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[15]246/Q core/spi_inst_shift_out_reg[15]246/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[16]/Q core/spi_inst_shift_out_reg[16]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[16]247/Q core/spi_inst_shift_out_reg[16]247/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[17]/Q core/spi_inst_shift_out_reg[17]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[17]248/Q core/spi_inst_shift_out_reg[17]248/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[18]/Q core/spi_inst_shift_out_reg[18]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[18]249/Q core/spi_inst_shift_out_reg[18]249/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[19]/Q core/spi_inst_shift_out_reg[19]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[19]250/Q core/spi_inst_shift_out_reg[19]250/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[20]/Q core/spi_inst_shift_out_reg[20]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[20]251/Q core/spi_inst_shift_out_reg[20]251/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[21]/Q core/spi_inst_shift_out_reg[21]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[21]252/Q core/spi_inst_shift_out_reg[21]252/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[22]/Q core/spi_inst_shift_out_reg[22]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[22]253/Q core/spi_inst_shift_out_reg[22]253/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[23]/Q core/spi_inst_shift_out_reg[23]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[23]254/Q core/spi_inst_shift_out_reg[23]254/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[24]/Q core/spi_inst_shift_out_reg[24]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[24]255/Q core/spi_inst_shift_out_reg[24]255/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[25]/Q core/spi_inst_shift_out_reg[25]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[25]256/Q core/spi_inst_shift_out_reg[25]256/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[26]/Q core/spi_inst_shift_out_reg[26]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[26]257/Q core/spi_inst_shift_out_reg[26]257/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[27]/Q core/spi_inst_shift_out_reg[27]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[27]258/Q core/spi_inst_shift_out_reg[27]258/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[28]/Q core/spi_inst_shift_out_reg[28]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[28]259/Q core/spi_inst_shift_out_reg[28]259/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[29]/Q core/spi_inst_shift_out_reg[29]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[29]260/Q core/spi_inst_shift_out_reg[29]260/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[30]/Q core/spi_inst_shift_out_reg[30]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[30]261/Q core/spi_inst_shift_out_reg[30]261/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[31]/Q core/spi_inst_shift_out_reg[31]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[31]262/Q core/spi_inst_shift_out_reg[31]262/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[32]/Q core/spi_inst_shift_out_reg[32]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[32]263/Q core/spi_inst_shift_out_reg[32]263/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[33]/Q core/spi_inst_shift_out_reg[33]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[33]264/Q core/spi_inst_shift_out_reg[33]264/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[34]/Q core/spi_inst_shift_out_reg[34]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[34]265/Q core/spi_inst_shift_out_reg[34]265/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[35]/Q core/spi_inst_shift_out_reg[35]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[35]266/Q core/spi_inst_shift_out_reg[35]266/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[36]/Q core/spi_inst_shift_out_reg[36]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[36]267/Q core/spi_inst_shift_out_reg[36]267/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[37]/Q core/spi_inst_shift_out_reg[37]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[37]268/Q core/spi_inst_shift_out_reg[37]268/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[38]/Q core/spi_inst_shift_out_reg[38]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[38]269/Q core/spi_inst_shift_out_reg[38]269/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[39]/Q core/spi_inst_shift_out_reg[39]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[39]270/Q core/spi_inst_shift_out_reg[39]270/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[40]/Q core/spi_inst_shift_out_reg[40]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[40]271/Q core/spi_inst_shift_out_reg[40]271/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[41]/Q core/spi_inst_shift_out_reg[41]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[41]272/Q core/spi_inst_shift_out_reg[41]272/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[42]/Q core/spi_inst_shift_out_reg[42]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[42]273/Q core/spi_inst_shift_out_reg[42]273/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[43]/Q core/spi_inst_shift_out_reg[43]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[43]274/Q core/spi_inst_shift_out_reg[43]274/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[44]/Q core/spi_inst_shift_out_reg[44]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[44]275/Q core/spi_inst_shift_out_reg[44]275/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[45]/Q core/spi_inst_shift_out_reg[45]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[45]276/Q core/spi_inst_shift_out_reg[45]276/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[46]/Q core/spi_inst_shift_out_reg[46]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[46]277/Q core/spi_inst_shift_out_reg[46]277/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[47]/Q core/spi_inst_shift_out_reg[47]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[47]278/Q core/spi_inst_shift_out_reg[47]278/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[48]/Q core/spi_inst_shift_out_reg[48]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[48]279/Q core/spi_inst_shift_out_reg[48]279/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[49]/Q core/spi_inst_shift_out_reg[49]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[49]280/Q core/spi_inst_shift_out_reg[49]280/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[50]/Q core/spi_inst_shift_out_reg[50]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[50]281/Q core/spi_inst_shift_out_reg[50]281/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[51]/Q core/spi_inst_shift_out_reg[51]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[51]282/Q core/spi_inst_shift_out_reg[51]282/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[52]/Q core/spi_inst_shift_out_reg[52]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[52]283/Q core/spi_inst_shift_out_reg[52]283/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[53]/Q core/spi_inst_shift_out_reg[53]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[53]284/Q core/spi_inst_shift_out_reg[53]284/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[54]/Q core/spi_inst_shift_out_reg[54]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[54]285/Q core/spi_inst_shift_out_reg[54]285/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[55]/Q core/spi_inst_shift_out_reg[55]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[55]286/Q core/spi_inst_shift_out_reg[55]286/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[56]/Q core/spi_inst_shift_out_reg[56]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[56]287/Q core/spi_inst_shift_out_reg[56]287/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[57]/Q core/spi_inst_shift_out_reg[57]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[57]288/Q core/spi_inst_shift_out_reg[57]288/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[58]/Q core/spi_inst_shift_out_reg[58]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[58]289/Q core/spi_inst_shift_out_reg[58]289/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[59]/Q core/spi_inst_shift_out_reg[59]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[59]290/Q core/spi_inst_shift_out_reg[59]290/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[60]/Q core/spi_inst_shift_out_reg[60]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[60]291/Q core/spi_inst_shift_out_reg[60]291/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[61]/Q core/spi_inst_shift_out_reg[61]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[61]292/Q core/spi_inst_shift_out_reg[61]292/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[62]/Q core/spi_inst_shift_out_reg[62]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[62]293/Q core/spi_inst_shift_out_reg[62]293/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[63]/Q core/spi_inst_shift_out_reg[63]/Q -type DFF DFF
add mapped point core/spi_inst_shift_out_reg[63]294/Q core/spi_inst_shift_out_reg[63]294/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[0]/Q core/spi_tx_data_reg[0]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[1]/Q core/spi_tx_data_reg[1]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[2]/Q core/spi_tx_data_reg[2]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[3]/Q core/spi_tx_data_reg[3]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[4]/Q core/spi_tx_data_reg[4]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[5]/Q core/spi_tx_data_reg[5]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[6]/Q core/spi_tx_data_reg[6]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[7]/Q core/spi_tx_data_reg[7]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[8]/Q core/spi_tx_data_reg[8]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[9]/Q core/spi_tx_data_reg[9]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[10]/Q core/spi_tx_data_reg[10]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[11]/Q core/spi_tx_data_reg[11]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[12]/Q core/spi_tx_data_reg[12]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[13]/Q core/spi_tx_data_reg[13]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[14]/Q core/spi_tx_data_reg[14]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[15]/Q core/spi_tx_data_reg[15]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[16]/Q core/spi_tx_data_reg[16]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[17]/Q core/spi_tx_data_reg[17]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[18]/Q core/spi_tx_data_reg[18]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[19]/Q core/spi_tx_data_reg[19]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[20]/Q core/spi_tx_data_reg[20]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[21]/Q core/spi_tx_data_reg[21]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[22]/Q core/spi_tx_data_reg[22]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[23]/Q core/spi_tx_data_reg[23]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[24]/Q core/spi_tx_data_reg[24]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[25]/Q core/spi_tx_data_reg[25]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[26]/Q core/spi_tx_data_reg[26]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[27]/Q core/spi_tx_data_reg[27]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[28]/Q core/spi_tx_data_reg[28]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[29]/Q core/spi_tx_data_reg[29]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[30]/Q core/spi_tx_data_reg[30]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[31]/Q core/spi_tx_data_reg[31]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[32]/Q core/spi_tx_data_reg[32]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[33]/Q core/spi_tx_data_reg[33]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[34]/Q core/spi_tx_data_reg[34]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[35]/Q core/spi_tx_data_reg[35]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[36]/Q core/spi_tx_data_reg[36]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[37]/Q core/spi_tx_data_reg[37]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[38]/Q core/spi_tx_data_reg[38]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[39]/Q core/spi_tx_data_reg[39]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[40]/Q core/spi_tx_data_reg[40]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[41]/Q core/spi_tx_data_reg[41]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[42]/Q core/spi_tx_data_reg[42]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[43]/Q core/spi_tx_data_reg[43]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[44]/Q core/spi_tx_data_reg[44]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[45]/Q core/spi_tx_data_reg[45]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[46]/Q core/spi_tx_data_reg[46]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[47]/Q core/spi_tx_data_reg[47]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[48]/Q core/spi_tx_data_reg[48]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[49]/Q core/spi_tx_data_reg[49]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[50]/Q core/spi_tx_data_reg[50]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[51]/Q core/spi_tx_data_reg[51]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[52]/Q core/spi_tx_data_reg[52]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[53]/Q core/spi_tx_data_reg[53]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[54]/Q core/spi_tx_data_reg[54]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[55]/Q core/spi_tx_data_reg[55]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[56]/Q core/spi_tx_data_reg[56]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[57]/Q core/spi_tx_data_reg[57]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[58]/Q core/spi_tx_data_reg[58]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[59]/Q core/spi_tx_data_reg[59]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[60]/Q core/spi_tx_data_reg[60]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[61]/Q core/spi_tx_data_reg[61]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[62]/Q core/spi_tx_data_reg[62]/Q -type DFF DFF
add mapped point core/spi_tx_data_reg[63]/Q core/spi_tx_data_reg[63]/Q -type DFF DFF
add mapped point core/start_decrypt_reg/Q core/start_decrypt_reg/Q -type DFF DFF
add mapped point core/start_encrypt_reg/Q core/start_encrypt_reg/Q -type DFF DFF
add mapped point core/transaction_state_reg[0]/Q core/transaction_state_reg[0]/Q -type DFF DFF
add mapped point core/transaction_state_reg[1]/Q core/transaction_state_reg[1]/Q -type DFF DFF
add mapped point core/trigger_operation_reg/Q core/trigger_operation_reg/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
