
//input ports
add mapped point clk clk -type PI PI
add mapped point rst rst -type PI PI
add mapped point sclk sclk -type PI PI
add mapped point cs_n cs_n -type PI PI
add mapped point mosi mosi -type PI PI

//output ports
add mapped point miso miso -type PO PO

//inout ports




//Sequential Pins
add mapped point core/trigger_operation/q core/trigger_operation_reg/Q -type DFF DFF
add mapped point core/spi_tx_data[27]/q core/spi_tx_data_reg[27]/Q -type DFF DFF
add mapped point core/spi_tx_data[49]/q core/spi_tx_data_reg[49]/Q -type DFF DFF
add mapped point core/spi_tx_data[1]/q core/spi_tx_data_reg[1]/Q -type DFF DFF
add mapped point core/spi_tx_data[0]/q core/spi_tx_data_reg[0]/Q -type DFF DFF
add mapped point core/spi_tx_data[33]/q core/spi_tx_data_reg[33]/Q -type DFF DFF
add mapped point core/spi_tx_data[32]/q core/spi_tx_data_reg[32]/Q -type DFF DFF
add mapped point core/spi_tx_data[61]/q core/spi_tx_data_reg[61]/Q -type DFF DFF
add mapped point core/spi_tx_data[48]/q core/spi_tx_data_reg[48]/Q -type DFF DFF
add mapped point core/spi_tx_data[31]/q core/spi_tx_data_reg[31]/Q -type DFF DFF
add mapped point core/spi_tx_data[57]/q core/spi_tx_data_reg[57]/Q -type DFF DFF
add mapped point core/spi_tx_data[30]/q core/spi_tx_data_reg[30]/Q -type DFF DFF
add mapped point core/spi_tx_data[56]/q core/spi_tx_data_reg[56]/Q -type DFF DFF
add mapped point core/spi_tx_data[47]/q core/spi_tx_data_reg[47]/Q -type DFF DFF
add mapped point core/spi_tx_data[29]/q core/spi_tx_data_reg[29]/Q -type DFF DFF
add mapped point core/spi_tx_data[28]/q core/spi_tx_data_reg[28]/Q -type DFF DFF
add mapped point core/spi_tx_data[46]/q core/spi_tx_data_reg[46]/Q -type DFF DFF
add mapped point core/spi_tx_data[63]/q core/spi_tx_data_reg[63]/Q -type DFF DFF
add mapped point core/spi_tx_data[26]/q core/spi_tx_data_reg[26]/Q -type DFF DFF
add mapped point core/spi_tx_data[60]/q core/spi_tx_data_reg[60]/Q -type DFF DFF
add mapped point core/spi_tx_data[55]/q core/spi_tx_data_reg[55]/Q -type DFF DFF
add mapped point core/spi_tx_data[45]/q core/spi_tx_data_reg[45]/Q -type DFF DFF
add mapped point core/spi_tx_data[25]/q core/spi_tx_data_reg[25]/Q -type DFF DFF
add mapped point core/spi_tx_data[24]/q core/spi_tx_data_reg[24]/Q -type DFF DFF
add mapped point core/spi_tx_data[44]/q core/spi_tx_data_reg[44]/Q -type DFF DFF
add mapped point core/spi_tx_data[23]/q core/spi_tx_data_reg[23]/Q -type DFF DFF
add mapped point core/spi_tx_data[22]/q core/spi_tx_data_reg[22]/Q -type DFF DFF
add mapped point core/spi_tx_data[54]/q core/spi_tx_data_reg[54]/Q -type DFF DFF
add mapped point core/spi_tx_data[43]/q core/spi_tx_data_reg[43]/Q -type DFF DFF
add mapped point core/spi_tx_data[21]/q core/spi_tx_data_reg[21]/Q -type DFF DFF
add mapped point core/spi_tx_data[20]/q core/spi_tx_data_reg[20]/Q -type DFF DFF
add mapped point core/spi_tx_data[42]/q core/spi_tx_data_reg[42]/Q -type DFF DFF
add mapped point core/spi_tx_data[19]/q core/spi_tx_data_reg[19]/Q -type DFF DFF
add mapped point core/spi_tx_data[10]/q core/spi_tx_data_reg[10]/Q -type DFF DFF
add mapped point core/spi_tx_data[62]/q core/spi_tx_data_reg[62]/Q -type DFF DFF
add mapped point core/spi_tx_data[59]/q core/spi_tx_data_reg[59]/Q -type DFF DFF
add mapped point core/spi_tx_data[53]/q core/spi_tx_data_reg[53]/Q -type DFF DFF
add mapped point core/spi_tx_data[41]/q core/spi_tx_data_reg[41]/Q -type DFF DFF
add mapped point core/spi_tx_data[17]/q core/spi_tx_data_reg[17]/Q -type DFF DFF
add mapped point core/spi_tx_data[16]/q core/spi_tx_data_reg[16]/Q -type DFF DFF
add mapped point core/spi_tx_data[40]/q core/spi_tx_data_reg[40]/Q -type DFF DFF
add mapped point core/spi_tx_data[15]/q core/spi_tx_data_reg[15]/Q -type DFF DFF
add mapped point core/spi_tx_data[14]/q core/spi_tx_data_reg[14]/Q -type DFF DFF
add mapped point core/spi_tx_data[52]/q core/spi_tx_data_reg[52]/Q -type DFF DFF
add mapped point core/spi_tx_data[39]/q core/spi_tx_data_reg[39]/Q -type DFF DFF
add mapped point core/spi_tx_data[13]/q core/spi_tx_data_reg[13]/Q -type DFF DFF
add mapped point core/spi_tx_data[12]/q core/spi_tx_data_reg[12]/Q -type DFF DFF
add mapped point core/spi_tx_data[38]/q core/spi_tx_data_reg[38]/Q -type DFF DFF
add mapped point core/spi_tx_data[11]/q core/spi_tx_data_reg[11]/Q -type DFF DFF
add mapped point core/spi_tx_data[18]/q core/spi_tx_data_reg[18]/Q -type DFF DFF
add mapped point core/spi_tx_data[58]/q core/spi_tx_data_reg[58]/Q -type DFF DFF
add mapped point core/spi_tx_data[51]/q core/spi_tx_data_reg[51]/Q -type DFF DFF
add mapped point core/spi_tx_data[37]/q core/spi_tx_data_reg[37]/Q -type DFF DFF
add mapped point core/spi_tx_data[9]/q core/spi_tx_data_reg[9]/Q -type DFF DFF
add mapped point core/spi_tx_data[8]/q core/spi_tx_data_reg[8]/Q -type DFF DFF
add mapped point core/spi_tx_data[36]/q core/spi_tx_data_reg[36]/Q -type DFF DFF
add mapped point core/spi_tx_data[7]/q core/spi_tx_data_reg[7]/Q -type DFF DFF
add mapped point core/spi_tx_data[6]/q core/spi_tx_data_reg[6]/Q -type DFF DFF
add mapped point core/spi_tx_data[50]/q core/spi_tx_data_reg[50]/Q -type DFF DFF
add mapped point core/spi_tx_data[35]/q core/spi_tx_data_reg[35]/Q -type DFF DFF
add mapped point core/spi_tx_data[5]/q core/spi_tx_data_reg[5]/Q -type DFF DFF
add mapped point core/spi_tx_data[4]/q core/spi_tx_data_reg[4]/Q -type DFF DFF
add mapped point core/spi_tx_data[34]/q core/spi_tx_data_reg[34]/Q -type DFF DFF
add mapped point core/spi_tx_data[3]/q core/spi_tx_data_reg[3]/Q -type DFF DFF
add mapped point core/spi_tx_data[2]/q core/spi_tx_data_reg[2]/Q -type DFF DFF
add mapped point core/cs_rise_delayed/q core/cs_rise_delayed_reg/Q -type DFF DFF
add mapped point core/cs_prev/q core/cs_prev_reg/Q -type DFF DFF
add mapped point core/cs_sync/q core/cs_sync_reg/Q -type DFF DFF
add mapped point core/cs_meta/q core/cs_meta_reg/Q -type DFF DFF
add mapped point core/active/q core/active_reg/Q -type DFF DFF
add mapped point core/transaction_state[0]/q core/transaction_state_reg[0]/Q -type DFF DFF
add mapped point core/done_decrypt_latched/q core/done_decrypt_latched_reg/Q -type DFF DFF
add mapped point core/done_encrypt_latched/q core/done_encrypt_latched_reg/Q -type DFF DFF
add mapped point core/transaction_state[1]/q core/transaction_state_reg[1]/Q -type DFF DFF
add mapped point core/data_reg[9]/q core/data_reg_reg[9]/Q -type DFF DFF
add mapped point core/data_reg[10]/q core/data_reg_reg[10]/Q -type DFF DFF
add mapped point core/data_reg[11]/q core/data_reg_reg[11]/Q -type DFF DFF
add mapped point core/key_reg[5]/q core/key_reg_reg[5]/Q -type DFF DFF
add mapped point core/key_reg[6]/q core/key_reg_reg[6]/Q -type DFF DFF
add mapped point core/key_reg[7]/q core/key_reg_reg[7]/Q -type DFF DFF
add mapped point core/key_reg[8]/q core/key_reg_reg[8]/Q -type DFF DFF
add mapped point core/key_reg[9]/q core/key_reg_reg[9]/Q -type DFF DFF
add mapped point core/key_reg[10]/q core/key_reg_reg[10]/Q -type DFF DFF
add mapped point core/key_reg[11]/q core/key_reg_reg[11]/Q -type DFF DFF
add mapped point core/key_reg[12]/q core/key_reg_reg[12]/Q -type DFF DFF
add mapped point core/data_reg[12]/q core/data_reg_reg[12]/Q -type DFF DFF
add mapped point core/data_reg[13]/q core/data_reg_reg[13]/Q -type DFF DFF
add mapped point core/key_reg[13]/q core/key_reg_reg[13]/Q -type DFF DFF
add mapped point core/key_reg[14]/q core/key_reg_reg[14]/Q -type DFF DFF
add mapped point core/key_reg[15]/q core/key_reg_reg[15]/Q -type DFF DFF
add mapped point core/key_reg[16]/q core/key_reg_reg[16]/Q -type DFF DFF
add mapped point core/data_reg[14]/q core/data_reg_reg[14]/Q -type DFF DFF
add mapped point core/key_reg[17]/q core/key_reg_reg[17]/Q -type DFF DFF
add mapped point core/key_reg[18]/q core/key_reg_reg[18]/Q -type DFF DFF
add mapped point core/data_reg[15]/q core/data_reg_reg[15]/Q -type DFF DFF
add mapped point core/key_reg[19]/q core/key_reg_reg[19]/Q -type DFF DFF
add mapped point core/key_reg[20]/q core/key_reg_reg[20]/Q -type DFF DFF
add mapped point core/data_reg[16]/q core/data_reg_reg[16]/Q -type DFF DFF
add mapped point core/data_reg[17]/q core/data_reg_reg[17]/Q -type DFF DFF
add mapped point core/key_reg[21]/q core/key_reg_reg[21]/Q -type DFF DFF
add mapped point core/key_reg[22]/q core/key_reg_reg[22]/Q -type DFF DFF
add mapped point core/key_reg[23]/q core/key_reg_reg[23]/Q -type DFF DFF
add mapped point core/key_reg[24]/q core/key_reg_reg[24]/Q -type DFF DFF
add mapped point core/data_reg[18]/q core/data_reg_reg[18]/Q -type DFF DFF
add mapped point core/key_reg[25]/q core/key_reg_reg[25]/Q -type DFF DFF
add mapped point core/key_reg[26]/q core/key_reg_reg[26]/Q -type DFF DFF
add mapped point core/data_reg[19]/q core/data_reg_reg[19]/Q -type DFF DFF
add mapped point core/key_reg[27]/q core/key_reg_reg[27]/Q -type DFF DFF
add mapped point core/key_reg[28]/q core/key_reg_reg[28]/Q -type DFF DFF
add mapped point core/data_reg[20]/q core/data_reg_reg[20]/Q -type DFF DFF
add mapped point core/data_reg[21]/q core/data_reg_reg[21]/Q -type DFF DFF
add mapped point core/key_reg[29]/q core/key_reg_reg[29]/Q -type DFF DFF
add mapped point core/key_reg[30]/q core/key_reg_reg[30]/Q -type DFF DFF
add mapped point core/key_reg[31]/q core/key_reg_reg[31]/Q -type DFF DFF
add mapped point core/key_reg[32]/q core/key_reg_reg[32]/Q -type DFF DFF
add mapped point core/data_reg[22]/q core/data_reg_reg[22]/Q -type DFF DFF
add mapped point core/key_reg[33]/q core/key_reg_reg[33]/Q -type DFF DFF
add mapped point core/key_reg[34]/q core/key_reg_reg[34]/Q -type DFF DFF
add mapped point core/data_reg[23]/q core/data_reg_reg[23]/Q -type DFF DFF
add mapped point core/key_reg[35]/q core/key_reg_reg[35]/Q -type DFF DFF
add mapped point core/key_reg[36]/q core/key_reg_reg[36]/Q -type DFF DFF
add mapped point core/data_reg[25]/q core/data_reg_reg[25]/Q -type DFF DFF
add mapped point core/data_reg[26]/q core/data_reg_reg[26]/Q -type DFF DFF
add mapped point core/key_reg[37]/q core/key_reg_reg[37]/Q -type DFF DFF
add mapped point core/key_reg[38]/q core/key_reg_reg[38]/Q -type DFF DFF
add mapped point core/key_reg[39]/q core/key_reg_reg[39]/Q -type DFF DFF
add mapped point core/key_reg[40]/q core/key_reg_reg[40]/Q -type DFF DFF
add mapped point core/data_reg[27]/q core/data_reg_reg[27]/Q -type DFF DFF
add mapped point core/key_reg[41]/q core/key_reg_reg[41]/Q -type DFF DFF
add mapped point core/key_reg[42]/q core/key_reg_reg[42]/Q -type DFF DFF
add mapped point core/key_reg[43]/q core/key_reg_reg[43]/Q -type DFF DFF
add mapped point core/key_reg[44]/q core/key_reg_reg[44]/Q -type DFF DFF
add mapped point core/data_reg[28]/q core/data_reg_reg[28]/Q -type DFF DFF
add mapped point core/data_reg[29]/q core/data_reg_reg[29]/Q -type DFF DFF
add mapped point core/key_reg[45]/q core/key_reg_reg[45]/Q -type DFF DFF
add mapped point core/key_reg[46]/q core/key_reg_reg[46]/Q -type DFF DFF
add mapped point core/key_reg[47]/q core/key_reg_reg[47]/Q -type DFF DFF
add mapped point core/key_reg[48]/q core/key_reg_reg[48]/Q -type DFF DFF
add mapped point core/data_reg[30]/q core/data_reg_reg[30]/Q -type DFF DFF
add mapped point core/key_reg[49]/q core/key_reg_reg[49]/Q -type DFF DFF
add mapped point core/data_reg[33]/q core/data_reg_reg[33]/Q -type DFF DFF
add mapped point core/key_reg[53]/q core/key_reg_reg[53]/Q -type DFF DFF
add mapped point core/key_reg[54]/q core/key_reg_reg[54]/Q -type DFF DFF
add mapped point core/key_reg[55]/q core/key_reg_reg[55]/Q -type DFF DFF
add mapped point core/key_reg[56]/q core/key_reg_reg[56]/Q -type DFF DFF
add mapped point core/data_reg[34]/q core/data_reg_reg[34]/Q -type DFF DFF
add mapped point core/key_reg[57]/q core/key_reg_reg[57]/Q -type DFF DFF
add mapped point core/key_reg[58]/q core/key_reg_reg[58]/Q -type DFF DFF
add mapped point core/data_reg[35]/q core/data_reg_reg[35]/Q -type DFF DFF
add mapped point core/key_reg[59]/q core/key_reg_reg[59]/Q -type DFF DFF
add mapped point core/key_reg[60]/q core/key_reg_reg[60]/Q -type DFF DFF
add mapped point core/data_reg[24]/q core/data_reg_reg[24]/Q -type DFF DFF
add mapped point core/data_reg[37]/q core/data_reg_reg[37]/Q -type DFF DFF
add mapped point core/key_reg[61]/q core/key_reg_reg[61]/Q -type DFF DFF
add mapped point core/key_reg[62]/q core/key_reg_reg[62]/Q -type DFF DFF
add mapped point core/key_reg[63]/q core/key_reg_reg[63]/Q -type DFF DFF
add mapped point core/data_reg[32]/q core/data_reg_reg[32]/Q -type DFF DFF
add mapped point core/data_reg[38]/q core/data_reg_reg[38]/Q -type DFF DFF
add mapped point core/data_reg[36]/q core/data_reg_reg[36]/Q -type DFF DFF
add mapped point core/data_reg[39]/q core/data_reg_reg[39]/Q -type DFF DFF
add mapped point core/data_reg[40]/q core/data_reg_reg[40]/Q -type DFF DFF
add mapped point core/data_reg[41]/q core/data_reg_reg[41]/Q -type DFF DFF
add mapped point core/data_reg[42]/q core/data_reg_reg[42]/Q -type DFF DFF
add mapped point core/data_reg[43]/q core/data_reg_reg[43]/Q -type DFF DFF
add mapped point core/data_reg[44]/q core/data_reg_reg[44]/Q -type DFF DFF
add mapped point core/data_reg[45]/q core/data_reg_reg[45]/Q -type DFF DFF
add mapped point core/data_reg[46]/q core/data_reg_reg[46]/Q -type DFF DFF
add mapped point core/data_reg[47]/q core/data_reg_reg[47]/Q -type DFF DFF
add mapped point core/key_reg[50]/q core/key_reg_reg[50]/Q -type DFF DFF
add mapped point core/data_reg[49]/q core/data_reg_reg[49]/Q -type DFF DFF
add mapped point core/data_reg[50]/q core/data_reg_reg[50]/Q -type DFF DFF
add mapped point core/data_reg[51]/q core/data_reg_reg[51]/Q -type DFF DFF
add mapped point core/data_reg[52]/q core/data_reg_reg[52]/Q -type DFF DFF
add mapped point core/data_reg[53]/q core/data_reg_reg[53]/Q -type DFF DFF
add mapped point core/data_reg[54]/q core/data_reg_reg[54]/Q -type DFF DFF
add mapped point core/data_reg[55]/q core/data_reg_reg[55]/Q -type DFF DFF
add mapped point core/data_reg[2]/q core/data_reg_reg[2]/Q -type DFF DFF
add mapped point core/data_reg[56]/q core/data_reg_reg[56]/Q -type DFF DFF
add mapped point core/data_reg[57]/q core/data_reg_reg[57]/Q -type DFF DFF
add mapped point core/data_reg[58]/q core/data_reg_reg[58]/Q -type DFF DFF
add mapped point core/data_reg[59]/q core/data_reg_reg[59]/Q -type DFF DFF
add mapped point core/data_reg[3]/q core/data_reg_reg[3]/Q -type DFF DFF
add mapped point core/data_reg[60]/q core/data_reg_reg[60]/Q -type DFF DFF
add mapped point core/data_reg[61]/q core/data_reg_reg[61]/Q -type DFF DFF
add mapped point core/data_reg[62]/q core/data_reg_reg[62]/Q -type DFF DFF
add mapped point core/data_reg[63]/q core/data_reg_reg[63]/Q -type DFF DFF
add mapped point core/data_reg[0]/q core/data_reg_reg[0]/Q -type DFF DFF
add mapped point core/data_reg[1]/q core/data_reg_reg[1]/Q -type DFF DFF
add mapped point core/data_reg[5]/q core/data_reg_reg[5]/Q -type DFF DFF
add mapped point core/data_reg[4]/q core/data_reg_reg[4]/Q -type DFF DFF
add mapped point core/key_reg[0]/q core/key_reg_reg[0]/Q -type DFF DFF
add mapped point core/data_reg[6]/q core/data_reg_reg[6]/Q -type DFF DFF
add mapped point core/key_reg[1]/q core/key_reg_reg[1]/Q -type DFF DFF
add mapped point core/key_reg[2]/q core/key_reg_reg[2]/Q -type DFF DFF
add mapped point core/data_reg[7]/q core/data_reg_reg[7]/Q -type DFF DFF
add mapped point core/key_reg[3]/q core/key_reg_reg[3]/Q -type DFF DFF
add mapped point core/key_reg[4]/q core/key_reg_reg[4]/Q -type DFF DFF
add mapped point core/data_reg[48]/q core/data_reg_reg[48]/Q -type DFF DFF
add mapped point core/data_reg[31]/q core/data_reg_reg[31]/Q -type DFF DFF
add mapped point core/key_reg[51]/q core/key_reg_reg[51]/Q -type DFF DFF
add mapped point core/key_reg[52]/q core/key_reg_reg[52]/Q -type DFF DFF
add mapped point core/data_reg[8]/q core/data_reg_reg[8]/Q -type DFF DFF
add mapped point core/start_decrypt/q core/start_decrypt_reg/Q -type DFF DFF
add mapped point core/start_encrypt/q core/start_encrypt_reg/Q -type DFF DFF
add mapped point core/crypt/q core/crypt_reg/Q -type DFF DFF



//Black Boxes
add mapped point clk_pad clk_pad -type BBOX BBOX
add mapped point core/csm_inst core/csm_inst -type BBOX BBOX
add mapped point core/spi_inst core/spi_inst -type BBOX BBOX
add mapped point cs_n_pad cs_n_pad -type BBOX BBOX
add mapped point miso_pad miso_pad -type BBOX BBOX
add mapped point mosi_pad mosi_pad -type BBOX BBOX
add mapped point rst_pad rst_pad -type BBOX BBOX
add mapped point sclk_pad sclk_pad -type BBOX BBOX



//Empty Modules as Blackboxes
